//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PresentNaviViewController.h"

@interface AddressBookNaviViewController : PresentNaviViewController
{
}

+ (id)addressBookControllerPresent:(id)arg1 animated:(_Bool)arg2;
- (void)viewDidDisappear:(_Bool)arg1;
- (id)init;

@end

