//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdrGuideAnimationView.h"

@class UIImageView;

@interface AdrAppCenterGuideAnimationView : AdrGuideAnimationView
{
    UIImageView *_guideLabelImg;
    UIImageView *_guideHeadImg;
}

+ (struct CGRect)calculateGuideViewFrameWithDependFrame:(struct CGRect)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)animationViewShowDone;
- (void)delayToDisappear;
- (void)startAnimation;
- (void)registNotification;
- (void)guideAnimationConfig;
- (void)buildUI;
- (id)initWithFrame:(struct CGRect)arg1 type:(long long)arg2;

@end

