//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AdrDatabaseServer.h"

@interface AdrBannerAdvertDatabaseServer : AdrDatabaseServer
{
}

+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)sharedAdrBannerAdvertDatabaseServer;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (void)updateRequestDataDate:(id)arg1;
- (id)requestDataDate;
- (void)updateBannerAdvertListTableVersion:(id)arg1;
- (id)bannerAdvertListTableVersion;
- (void)updatebannerAdvertListRequestStatus:(_Bool)arg1;
- (_Bool)bannerAdvertListRequestStatus;
- (_Bool)updateTableWithItems:(id)arg1;
- (id)queryAllItems;
- (id)getBannerItemByPluginID:(id)arg1;
- (_Bool)clearAllItems;
- (_Bool)dropTable;
- (_Bool)createTable;

@end

