//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AdrEasyJSWebView, NSString;

@interface AdrEasyJSDataFunction : NSObject
{
    _Bool removeAfterExecute;
    NSString *funcID;
    AdrEasyJSWebView *webView;
}

@property(nonatomic) _Bool removeAfterExecute; // @synthesize removeAfterExecute;
@property(retain, nonatomic) AdrEasyJSWebView *webView; // @synthesize webView;
@property(retain, nonatomic) NSString *funcID; // @synthesize funcID;
- (id)executeWithParams:(id)arg1;
- (id)executeWithParam:(id)arg1;
- (id)execute;
- (id)initWithWebView:(id)arg1;

@end

