//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSArray, NSString;

@interface AdrInterface_GPS : NSObject <CLLocationManagerDelegate>
{
    NSArray *_GPSArgs;
    CLLocationManager *_locationManager;
}

+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)sharedAdrInterface_GPS;
+ (id)allocWithZone:(struct _NSZone *)arg1;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSArray *GPSArgs; // @synthesize GPSArgs=_GPSArgs;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stopUpdatingLocation;
- (void)didFailGettingCurrentLocation:(int)arg1 description:(id)arg2;
- (void)didFinishedGettingCurrentLocation:(id)arg1;
- (void)locationManager:(id)arg1 monitoringDidFailForRegion:(id)arg2 withError:(id)arg3;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)startGettingCurrentLocation;
- (void)getCurrentPosition:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

