//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView, UILabel, UITapGestureRecognizer;

@interface AdrMsgCenterUserInfoView : UIView
{
    UIImageView *_headerView;
    UILabel *_nameLabel;
    UITapGestureRecognizer *_gesture;
    CDUnknownBlockType _clickBlock;
}

@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void).cxx_destruct;
- (void)dealloc;
- (id)getScaleImage:(id)arg1 frame:(struct CGRect)arg2;
- (void)resetUserInfo;
- (void)setPersonalData:(id)arg1;
- (void)userInfoClicked;
- (void)initSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

