//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AdrPluginView, UIImageView;

@interface AdrNewPluginGuideAnimationView : UIView
{
    UIImageView *_guideImageView;
    AdrPluginView *_shakePluginView;
}

+ (void)doGuideAnimationWithPluginView:(id)arg1;
- (void).cxx_destruct;
- (void)dealloc;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)stopShakeAnimation;
- (void)doGuideAnimation;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)loadGuideImageWithPluginWidth:(double)arg1;
- (void)registerNotification;
- (id)initWithDependPluginView:(id)arg1;

@end

