//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface AdrReflection : NSObject
{
}

+ (id)copyWithZone:(struct _NSZone *)arg1;
+ (id)sharedAdrReflection;
+ (id)allocWithZone:(struct _NSZone *)arg1;
- (id)classPropertiesArray:(Class)arg1;
- (id)objPropertiesAndValues:(id)arg1;

@end

