//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface AdrShareModel : NSObject
{
    int _shareMessageType;
    NSString *_shareTitle;
    NSString *_shareDescription;
    NSString *_shareUrl;
    NSString *_shareThumbImageUrl;
    NSData *_shareThumbImageData;
}

@property(nonatomic) int shareMessageType; // @synthesize shareMessageType=_shareMessageType;
@property(retain, nonatomic) NSData *shareThumbImageData; // @synthesize shareThumbImageData=_shareThumbImageData;
@property(retain, nonatomic) NSString *shareThumbImageUrl; // @synthesize shareThumbImageUrl=_shareThumbImageUrl;
@property(retain, nonatomic) NSString *shareUrl; // @synthesize shareUrl=_shareUrl;
@property(retain, nonatomic) NSString *shareDescription; // @synthesize shareDescription=_shareDescription;
@property(retain, nonatomic) NSString *shareTitle; // @synthesize shareTitle=_shareTitle;
- (void).cxx_destruct;
- (int)checkShareModel;
- (id)dictFromModel;

@end

