//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AdrSpitslotModel, UIImageView;

@interface AdrSpitslotView : UIView
{
    UIImageView *_iconImageView;
    struct CGRect viewFrame;
    CDUnknownBlockType _clickBlock;
    AdrSpitslotModel *_model;
}

@property(retain, nonatomic) AdrSpitslotModel *model; // @synthesize model=_model;
@property(copy, nonatomic) CDUnknownBlockType clickBlock; // @synthesize clickBlock=_clickBlock;
- (void).cxx_destruct;
- (void)dealloc;
- (void)handleTap;
- (void)handleIconPosition:(id)arg1;
- (void)handleIconMove:(id)arg1;
- (void)handlePanGesture:(id)arg1;
- (void)addGesture;
- (struct CGSize)getSizeImage:(id)arg1 frame:(struct CGRect)arg2;
- (double)sizeRatioBaseIphone6;
- (void)initSubView;
- (id)initWithSpitslotModel:(id)arg1;

@end

