//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AdrSignTicket : NSObject
{
    NSString *_timestamp;
}

@property(retain, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
- (id)getMcSign;
- (id)getSignTicket;
- (id)init;

@end

