//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class UIColor;

@interface AdrViewInfo : NSObject
{
    _Bool _isFromTop;
    _Bool _isFullScreenMask;
    _Bool _isShowDoraemon;
    _Bool _isPluginLengthForPlus;
    int _pluginCenterStyleForInit;
    int _pluginOpenStyle;
    int _pluginOpenDirection;
    UIColor *_pluginViewStatusBarColor;
    UIColor *_pluginViewNavigationBarColor;
    UIColor *_navigationBarTitleColor;
    struct CGRect _viewframe;
}

@property(nonatomic) int pluginOpenDirection; // @synthesize pluginOpenDirection=_pluginOpenDirection;
@property(nonatomic) int pluginOpenStyle; // @synthesize pluginOpenStyle=_pluginOpenStyle;
@property(retain, nonatomic) UIColor *navigationBarTitleColor; // @synthesize navigationBarTitleColor=_navigationBarTitleColor;
@property(retain, nonatomic) UIColor *pluginViewNavigationBarColor; // @synthesize pluginViewNavigationBarColor=_pluginViewNavigationBarColor;
@property(nonatomic) _Bool isPluginLengthForPlus; // @synthesize isPluginLengthForPlus=_isPluginLengthForPlus;
@property(nonatomic) _Bool isShowDoraemon; // @synthesize isShowDoraemon=_isShowDoraemon;
@property(nonatomic) int pluginCenterStyleForInit; // @synthesize pluginCenterStyleForInit=_pluginCenterStyleForInit;
@property(nonatomic) _Bool isFullScreenMask; // @synthesize isFullScreenMask=_isFullScreenMask;
@property(retain, nonatomic) UIColor *pluginViewStatusBarColor; // @synthesize pluginViewStatusBarColor=_pluginViewStatusBarColor;
@property(nonatomic) _Bool isFromTop; // @synthesize isFromTop=_isFromTop;
@property(nonatomic) struct CGRect viewframe; // @synthesize viewframe=_viewframe;
- (void).cxx_destruct;
- (id)init;

@end

