//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AdrVoiceDelegate.h"

@class AdrUnderstandVoice, AdrVoiceRecordHUD, NSArray, NSString, UIWebView;

@interface AdrVoiceManager : NSObject <AdrVoiceDelegate>
{
    AdrUnderstandVoice *_understandVoice;
    id <AdrVoiceManagerDelegate> _delegate;
    NSArray *_voiceArgArr;
    UIWebView *_webView;
    NSString *_pluginId;
    AdrVoiceRecordHUD *_voiceRecordHUD;
    long long _voiceState;
}

@property(nonatomic) long long voiceState; // @synthesize voiceState=_voiceState;
@property(retain, nonatomic) AdrVoiceRecordHUD *voiceRecordHUD; // @synthesize voiceRecordHUD=_voiceRecordHUD;
@property(retain, nonatomic) NSString *pluginId; // @synthesize pluginId=_pluginId;
@property(retain, nonatomic) UIWebView *webView; // @synthesize webView=_webView;
@property(retain, nonatomic) NSArray *voiceArgArr; // @synthesize voiceArgArr=_voiceArgArr;
@property(nonatomic) __weak id <AdrVoiceManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)hideVoiceRecordHUD;
- (void)showVoiceRecordHUD;
- (void)stopRecord;
- (void)volumeChanged:(long long)arg1;
- (void)commitErrorMessageToH5:(id)arg1;
- (void)endOfSpeech;
- (void)showResults:(id)arg1;
- (void)commitErrorToH5:(id)arg1;
- (void)startUnderstandVoice;
- (void)startRecord;
- (void)initIFlyVoice;
- (id)initWithPlugiId:(id)arg1 withWebView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

