//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITextViewDelegate.h"

@class AdrVoiceTextView, NSString, UIButton;

@interface AdrVoiceInputPanel : UIView <UITextViewDelegate>
{
    AdrVoiceTextView *_inputTextView;
    UIButton *_voiceButton;
    UIButton *_sendButton;
    long long _voiceInputPanelHeight;
    long long _voiceButtonHeight;
    long long _sendButtonWidth;
    long long _voiceTextViewHeight;
    long long _voiceTextViewMaxHeight;
    long long _difValue;
    long long _xOriginOfVoiceButton;
    long long _yOriginOfVoiceButton;
    long long _gapOfVoiceBtnAndTextview;
    long long _gapOfSendBtnAndTextview;
    double _fontOfSend;
    long long _textViewMaxHeight;
    double _webViewHeight;
    id <AdrVoiceInputPanelDelegate> _delegate;
}

@property(nonatomic) id <AdrVoiceInputPanelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)changeChatViewHeight;
- (double)measureHeight;
- (void)changeSendButtonColor;
- (void)textViewDidChange:(id)arg1;
- (_Bool)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)changePanelHeight:(double)arg1;
- (void)clearTextView;
- (void)showKeyboard;
- (void)sendMessageToH5;
- (void)keyboardStateChange:(id)arg1;
- (void)changeToVoiceInput:(id)arg1;
- (void)addNotification;
- (void)initSendButton;
- (void)initInputTextView;
- (void)initVoiceButton;
- (void)adaptLayout;
- (id)initWithWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

