//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIImageView;

@interface AdrVoiceAnimationButton : UIButton
{
    UIImageView *_buttonBgImgView;
    UIImageView *_animationImgView;
    _Bool _isAnimation;
}

@property(nonatomic) _Bool isAnimation; // @synthesize isAnimation=_isAnimation;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)startAnimation;
- (id)initWithFrame:(struct CGRect)arg1;

@end

