//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface AreaItem : NSObject
{
    NSString *_des;
    NSString *_areaId;
}

+ (id)initWithDes:(id)arg1 andArea:(id)arg2;
@property(retain, nonatomic) NSString *areaId; // @synthesize areaId=_areaId;
@property(retain, nonatomic) NSString *des; // @synthesize des=_des;
- (void).cxx_destruct;

@end

