//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "CLLocationManagerDelegate.h"

@class CLLocationManager, NSMutableDictionary, NSMutableString, NSString;

@interface ASPingAnSecurity : NSObject <CLLocationManagerDelegate>
{
    _Bool ready;
    NSMutableString *locationStorege;
    CLLocationManager *locManager;
    id <ASSecurityDelegate> securityDelegate;
    NSMutableDictionary *mServices;
}

+ (id)sharedSecurityAgent;
@property(retain, nonatomic) NSMutableDictionary *mServices; // @synthesize mServices;
@property(nonatomic) id <ASSecurityDelegate> securityDelegate; // @synthesize securityDelegate;
@property(nonatomic) _Bool ready; // @synthesize ready;
@property(retain, nonatomic) CLLocationManager *locManager; // @synthesize locManager;
@property(retain, nonatomic) NSMutableString *locationStorege; // @synthesize locationStorege;
- (void).cxx_destruct;
- (void)setAppId:(id)arg1;
- (void)setAdId:(id)arg1;
- (void)setVendorId:(id)arg1;
- (void)setDisplay:(id)arg1;
- (void)setMem:(id)arg1;
- (void)setDisk:(id)arg1;
- (void)setBatteryInfo:(id)arg1;
- (void)setRoot:(id)arg1;
- (void)setGatWay:(id)arg1;
- (void)setDNS:(id)arg1;
- (void)setCellNo:(id)arg1:(id)arg2;
- (id)getDeviceInfo:(id)arg1;
- (id)getRegiterData:(id)arg1;
- (id)getLoginData:(id)arg1;
- (void)setPin:(id)arg1:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (id)getCollectData:(id)arg1:(id)arg2;
- (void)setSysSpec:(id)arg1;
- (id)getEncryptData:(id)arg1;
- (id)getUUIData;
- (id)encryptRSAData:(id)arg1;
- (id)getDeviceInfo;
- (void)getLocation:(id)arg1;
- (id)getCurrentTime;
- (void)setUserName:(id)arg1:(id)arg2;
- (void)stop:(id)arg1;
- (void)start:(id)arg1;
- (id)checkService:(id)arg1;
- (_Bool)uninitService;
- (_Bool)initService;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

