//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CALayer.h"

@class UIColor;

@interface BlurClearLayer : CALayer
{
    struct CGRect clearRect;
    UIColor *_blurColor;
    UIColor *_outlineColor;
}

@property(retain, nonatomic) UIColor *outlineColor; // @synthesize outlineColor=_outlineColor;
@property(retain, nonatomic) UIColor *blurColor; // @synthesize blurColor=_blurColor;
- (void).cxx_destruct;
- (void)drawLineFrom:(struct CGPoint)arg1 pass:(struct CGPoint)arg2 to:(struct CGPoint)arg3 linewidth:(double)arg4 context:(struct CGContext *)arg5 index:(long long)arg6;
- (void)drawRestrictionCornersContext:(struct CGContext *)arg1;
- (void)drawDisplayRectContext:(struct CGContext *)arg1;
- (void)drawBlurContext:(struct CGContext *)arg1;
- (void)drawInContext:(struct CGContext *)arg1;
- (void)clearRect:(struct CGRect)arg1;
- (id)initWithOutlineColor:(id)arg1 blurColor:(id)arg2;

@end

