//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, UITableView;

@interface CCSFeedBackPolsListView : UIView <UITableViewDataSource, UITableViewDelegate>
{
    UITableView *polListTable;
    id <CCSFeedBackPolsListViewDelegate> _delegate;
    NSMutableArray *_ccsPolArray;
}

@property(copy, nonatomic) NSMutableArray *ccsPolArray; // @synthesize ccsPolArray=_ccsPolArray;
@property(nonatomic) __weak id <CCSFeedBackPolsListViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITableView *polListTable; // @synthesize polListTable;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

