//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

#import "AVAudioPlayerDelegate.h"
#import "AVAudioRecorderDelegate.h"

@class AVAudioSession, NSMutableDictionary, NSString;

@interface CDVSound : CDVPlugin <AVAudioPlayerDelegate, AVAudioRecorderDelegate>
{
    NSMutableDictionary *soundCache;
    AVAudioSession *avSession;
}

@property(retain, nonatomic) AVAudioSession *avSession; // @synthesize avSession;
@property(retain, nonatomic) NSMutableDictionary *soundCache; // @synthesize soundCache;
- (void).cxx_destruct;
- (void)onReset;
- (void)dealloc;
- (void)onMemoryWarning;
- (void)audioPlayerDidFinishPlaying:(id)arg1 successfully:(_Bool)arg2;
- (void)audioRecorderDidFinishRecording:(id)arg1 successfully:(_Bool)arg2;
- (void)stopRecordingAudio:(id)arg1;
- (void)startRecordingAudio:(id)arg1;
- (void)getCurrentPositionAudio:(id)arg1;
- (void)release:(id)arg1;
- (void)seekToAudio:(id)arg1;
- (void)pausePlayingAudio:(id)arg1;
- (void)stopPlayingAudio:(id)arg1;
- (_Bool)prepareToPlay:(id)arg1 withId:(id)arg2;
- (void)startPlayingAudio:(id)arg1;
- (void)setVolume:(id)arg1;
- (void)create:(id)arg1;
- (id)createMediaErrorWithCode:(unsigned long long)arg1 message:(id)arg2;
- (_Bool)hasAudioSession;
- (id)audioFileForResource:(id)arg1 withId:(id)arg2 doValidation:(_Bool)arg3 forRecording:(_Bool)arg4;
- (id)audioFileForResource:(id)arg1 withId:(id)arg2;
- (id)urlForPlaying:(id)arg1;
- (id)urlForRecording:(id)arg1;
- (id)urlForResource:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

