//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "CDVPlugin.h"

@class JKNPluginAssistant;

@interface ChannelPlugin : CDVPlugin
{
    JKNPluginAssistant *_assistant;
}

@property(retain, nonatomic) JKNPluginAssistant *assistant; // @synthesize assistant=_assistant;
- (void).cxx_destruct;
- (_Bool)openSafairWithUrl:(id)arg1;
- (void)exitApp:(id)arg1;
- (void)refreshUserToken:(id)arg1;
- (void)sendJson:(id)arg1;
- (void)openSystemBrowser:(id)arg1;
- (void)getJKNSDKVersionCode:(id)arg1;
- (void)getVersionCode:(id)arg1;
- (void)sendCurrPage:(id)arg1;
- (void)shareWithType:(long long)arg1 shareData:(id)arg2;
- (void)shareWeixin:(id)arg1;
- (void)sharePengyou:(id)arg1;
- (void)shareWeibo:(id)arg1;
- (void)pajkPostMessage:(id)arg1;
- (id)init;

@end

