//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString, NSURL, PAIMChatMessageView;

@protocol ChatMessageViewDelegate <NSObject>

@optional
- (void)didTapRedPacketPromptWithId:(NSString *)arg1;
- (void)pushWebViewWithUrl:(NSURL *)arg1 title:(NSString *)arg2;
- (void)voiceMessagePlaying:(PAIMChatMessageView *)arg1;
- (void)voiceMessageTapped:(PAIMChatMessageView *)arg1;
- (void)stopAllVoice;
- (void)photoLongPressHandlerWithFriendName:(NSString *)arg1 friendID:(NSString *)arg2;
- (void)dissmissAllView;
- (void)selectedMessage:(PAIMChatMessageView *)arg1 withEmail:(NSString *)arg2;
- (void)selectedMessage:(PAIMChatMessageView *)arg1 withPhoneNumber:(NSString *)arg2;
- (void)testGameMessage:(PAIMChatMessageView *)arg1;
- (void)changeVoicePlayMode;
- (void)selectHedeImage:(NSString *)arg1;
- (void)resendFailMessage:(PAIMChatMessageView *)arg1;
- (void)bubbleTouchDown:(PAIMChatMessageView *)arg1;
- (void)deleteMSG:(PAIMChatMessageView *)arg1;
- (void)changePlayMode:(PAIMChatMessageView *)arg1;
- (void)resendMSG:(PAIMChatMessageView *)arg1;
- (void)copyMSG:(PAIMChatMessageView *)arg1;
- (void)selectTemplateMessage:(PAIMChatMessageView *)arg1;
- (void)selectAdMessage:(PAIMChatMessageView *)arg1 atIndex:(NSNumber *)arg2;
- (void)voiceMessageSelect:(PAIMChatMessageView *)arg1;
- (void)videoMessageSelect:(PAIMChatMessageView *)arg1;
- (void)locationMessageSelect:(PAIMChatMessageView *)arg1;
- (void)imageMessageSelect:(PAIMChatMessageView *)arg1;
@end

