//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface Common : NSObject
{
    NSMutableDictionary *_publicPropertyDic;
}

+ (_Bool)IsFirstOpen:(id)arg1 userPhoneNumber:(id)arg2;
+ (id)checkNull:(id)arg1;
+ (id)shareCommon;
@property(retain) NSMutableDictionary *publicPropertyDic; // @synthesize publicPropertyDic=_publicPropertyDic;
- (void).cxx_destruct;
- (_Bool)getPolicyGuideSecondNotShow;
- (void)setPolicyGuideSecondNotShow:(_Bool)arg1;
- (_Bool)getPolicyGuideFirstNotShow;
- (void)setPolicyGuideFirstNotShow:(_Bool)arg1;
- (void)setPolicyIsShowRealNameAlert;
- (_Bool)getPolicyIsShowRealNameAlert;
- (_Bool)getIsFirstUseApp;
- (void)setIsFirstUseApp:(_Bool)arg1;
- (_Bool)getIsFirstLogin;
- (void)setIsFirstLogin:(_Bool)arg1;
- (id)getHealthToken;
- (void)setHealthToken;
- (_Bool)isDidShowFeaturesUpdateGuide;
- (void)setFeaturesUpdateGuideVersion;
- (id)getAgentNo;
- (id)getAgentPhoneNO;
- (id)getUserName;
- (id)getDefaultEncryptedUserPhoneNO;
- (id)getUserPhoneNO;
- (id)getDocumentPath;
- (void)hideLoadingAnimation;
- (void)showLoadingAnimation;
- (void)deletePropertyForPublicDic;
- (void)getPropertyForPublicDic:(id)arg1;
- (void)addPropertyForPublicDic:(id)arg1 property:(id)arg2;

@end

