//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class UIView<CustomIOSAlertDataProvider>;

@protocol CustomIOSAlertViewDelegate
- (void)customIOS7dialog:(UIView<CustomIOSAlertDataProvider> *)arg1 buttonTouchUpInside:(id)arg2 clickedButtonAtIndex:(long long)arg3;
@end

