//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class NSMutableArray, NSString, UIImageView;

@interface CustomView : UIScrollView <UIScrollViewDelegate>
{
    UIScrollView *scrollView;
    UIImageView *imageView;
    NSMutableArray *img;
    NSMutableArray *location;
    NSMutableArray *oldImg;
    UIImageView *cursor;
    unsigned long long index;
    float offset;
    double width;
    double scrollWidth;
    unsigned long long divisorPre;
    int picCount;
    id <CustomViewDelegate> _CVdelegate;
}

@property(retain, nonatomic) id <CustomViewDelegate> CVdelegate; // @synthesize CVdelegate=_CVdelegate;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView;
- (id)getImage;
- (void)Hiddencursor;
- (void)setoffsetWithPich:(double)arg1;
- (void)RemoveCursor;
- (struct CGRect)getScrollInfo;
- (id)reset:(unsigned long long)arg1;
- (void)deletePic;
- (int)getimageCount;
- (void)addSubPic:(id)arg1;
- (void)setCursor:(struct CGPoint)arg1;
- (void)setScrollWidth:(double)arg1;
- (void)setLocationArry:(struct CGRect)arg1;
- (void)setOldImgArry:(id)arg1;
- (void)setpicArry:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)releaseData;
- (void)reset;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

