//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIColor;

@interface DGActivityIndicatorView : UIView
{
    _Bool _animating;
    unsigned long long _type;
    UIColor *_tintColor;
    double _size;
}

+ (id)activityIndicatorAnimationForAnimationType:(unsigned long long)arg1;
@property(readonly, nonatomic) _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) double size; // @synthesize size=_size;
@property(retain, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)setupAnimation;
- (id)initWithType:(unsigned long long)arg1 tintColor:(id)arg2 size:(double)arg3;
- (id)initWithType:(unsigned long long)arg1 tintColor:(id)arg2;
- (id)initWithType:(unsigned long long)arg1;

@end

