//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSOperationQueue;

@interface FileLog : NSObject
{
    NSOperationQueue *_queue;
}

+ (void)Log:(id)arg1;
+ (id)allocWithZone:(struct _NSZone *)arg1;
+ (id)logManager;
- (void).cxx_destruct;
- (id)formatLogEntry:(id)arg1;
- (void)writeLogToFile:(id)arg1;
- (void)writeLogToFileBlock:(id)arg1;
- (id)init;

@end

