//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UITextFieldDelegate.h"
#import "addFriendSuccessDelegate.h"

@class NSString, UIButton, UIImageView, UILabel, UITextField;

@interface HealthWalkingSecondInviteCell : UITableViewCell <UITextFieldDelegate, addFriendSuccessDelegate>
{
    UITextField *_nameTextField;
    UITextField *_telephoneTextField;
    id <addFriendDelegate> _delegate;
    UIImageView *_textFieldBgView;
    UILabel *_titleLabel;
    UIButton *_addButton;
    UIButton *_addFromButton;
}

@property(retain, nonatomic) UIButton *addFromButton; // @synthesize addFromButton=_addFromButton;
@property(retain, nonatomic) UIButton *addButton; // @synthesize addButton=_addButton;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *textFieldBgView; // @synthesize textFieldBgView=_textFieldBgView;
@property(nonatomic) __weak id <addFriendDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) UITextField *telephoneTextField; // @synthesize telephoneTextField=_telephoneTextField;
@property(retain, nonatomic) UITextField *nameTextField; // @synthesize nameTextField=_nameTextField;
- (void).cxx_destruct;
- (void)addFriendSuccessToRemoveTextField;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)buttonTapped:(id)arg1;
- (void)setupSubviews;
- (id)buildButtonWithImageName:(id)arg1 bgImageName:(id)arg2 title:(id)arg3;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

