//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AFHTTPRequestOperation, HMError;

@interface HMConnectionTask : NSObject
{
    _Bool _synchronous;
    _Bool _cancel;
    AFHTTPRequestOperation *_operation;
    CDUnknownBlockType _loadBlock;
    CDUnknownBlockType _followingWorkBlock;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failureBlock;
    id _responseObj;
    HMError *_error;
}

@property(retain, nonatomic) HMError *error; // @synthesize error=_error;
@property(retain, nonatomic) id responseObj; // @synthesize responseObj=_responseObj;
@property(copy, nonatomic) CDUnknownBlockType failureBlock; // @synthesize failureBlock=_failureBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(copy, nonatomic) CDUnknownBlockType followingWorkBlock; // @synthesize followingWorkBlock=_followingWorkBlock;
@property(copy, nonatomic) CDUnknownBlockType loadBlock; // @synthesize loadBlock=_loadBlock;
@property(nonatomic) __weak AFHTTPRequestOperation *operation; // @synthesize operation=_operation;
@property(nonatomic, getter=isCancelled) _Bool cancel; // @synthesize cancel=_cancel;
@property(nonatomic) _Bool synchronous; // @synthesize synchronous=_synchronous;
- (void).cxx_destruct;
- (void)failWithNotReachable;
- (id)init;

@end

