//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITextFieldDelegate.h"

@class NSLayoutConstraint, NSString, NSTimer, PARSActivityDetailModel, PARSAgentCardView, PARSCustomerAgentInfo, UIButton, UIImageView, UILabel, UITextField, UIView;

@interface HWSignUpViewController : UIViewController <UITextFieldDelegate>
{
    UIButton *_checkButton;
    UIButton *_sendButton;
    UITextField *_nameTF;
    UITextField *_agentTF;
    UITextField *_phoneNoTF;
    UITextField *_authCodeTF;
    UIButton *_signUpButton;
    UIImageView *_agentNoIcon;
    UIView *_topContainerView;
    UILabel *_tipAgentQuitLabel;
    unsigned long long _countDownTime;
    NSTimer *_timer;
    NSString *_nickName;
    NSString *_agentName;
    NSString *_departmentName;
    NSString *_staffGroupID;
    _Bool _hasPassword;
    _Bool _hideOTP;
    _Bool _tipAgentQuit;
    _Bool _needQuitGroup;
    int _fromType;
    NSString *_activityID;
    id <SignUpDidFinish> _delegate;
    NSString *_groupID;
    PARSActivityDetailModel *_activityInfo;
    NSString *_circleAgentNo;
    long long _agentNoCanModify;
    CDUnknownBlockType _signUpHandler;
    UIView *_agentCardBgv;
    NSLayoutConstraint *_agentCardBgvHeight;
    UILabel *_activityProvision;
    PARSAgentCardView *_agentCardView;
    PARSCustomerAgentInfo *_agentInfo;
}

@property(retain, nonatomic) PARSCustomerAgentInfo *agentInfo; // @synthesize agentInfo=_agentInfo;
@property(retain, nonatomic) PARSAgentCardView *agentCardView; // @synthesize agentCardView=_agentCardView;
@property(nonatomic) __weak UILabel *activityProvision; // @synthesize activityProvision=_activityProvision;
@property(nonatomic) __weak NSLayoutConstraint *agentCardBgvHeight; // @synthesize agentCardBgvHeight=_agentCardBgvHeight;
@property(retain, nonatomic) UIView *agentCardBgv; // @synthesize agentCardBgv=_agentCardBgv;
@property(copy, nonatomic) CDUnknownBlockType signUpHandler; // @synthesize signUpHandler=_signUpHandler;
@property(nonatomic) long long agentNoCanModify; // @synthesize agentNoCanModify=_agentNoCanModify;
@property(copy, nonatomic) NSString *circleAgentNo; // @synthesize circleAgentNo=_circleAgentNo;
@property(retain, nonatomic) PARSActivityDetailModel *activityInfo; // @synthesize activityInfo=_activityInfo;
@property(copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(nonatomic) _Bool needQuitGroup; // @synthesize needQuitGroup=_needQuitGroup;
@property(nonatomic) _Bool tipAgentQuit; // @synthesize tipAgentQuit=_tipAgentQuit;
@property(nonatomic) _Bool hideOTP; // @synthesize hideOTP=_hideOTP;
@property(nonatomic) int fromType; // @synthesize fromType=_fromType;
@property(nonatomic) __weak id <SignUpDidFinish> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *activityID; // @synthesize activityID=_activityID;
- (void).cxx_destruct;
- (void)sjyLoginCompletion:(_Bool)arg1;
- (void)textEditingChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)CountdownTime;
- (void)showDialog;
- (void)sendClick;
- (void)checkClick;
- (void)verifyCustomerAgent:(id)arg1 activityId:(id)arg2;
- (_Bool)checkInput;
- (void)gotoFriendCircle;
- (void)joinMoments;
- (void)enroll:(double)arg1;
- (void)signUpClick;
- (void)didReceiveMemoryWarning;
- (void)clauseTap:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dismissSelf;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

