//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "IDPhotoDelegate.h"
#import "IDRecDelegate.h"
#import "UIAlertViewDelegate.h"

@class IDCameraController, IDFrameView, IDPhoto, NSString, UIButton, UILabel;

@interface IDCardRecognizeViewController : UIViewController <IDRecDelegate, IDPhotoDelegate, UIAlertViewDelegate>
{
    struct CGRect frameBounders;
    UILabel *supportLabel;
    _Bool _isFront;
    _Bool _bLastWrong;
    _Bool _bDoubleCheck;
    _Bool _bphotoReco;
    CDUnknownBlockType _recognizeBlock;
    CDUnknownBlockType _cancelBlock;
    IDCameraController *_cameraController;
    IDFrameView *_frameView;
    UIButton *_photoBtn;
    IDPhoto *_photo;
    UIButton *_backBtn;
    UIButton *_lightBtn;
}

@property(retain, nonatomic) UIButton *lightBtn; // @synthesize lightBtn=_lightBtn;
@property(retain, nonatomic) UIButton *backBtn; // @synthesize backBtn=_backBtn;
@property(nonatomic) _Bool bphotoReco; // @synthesize bphotoReco=_bphotoReco;
@property(retain, nonatomic) IDPhoto *photo; // @synthesize photo=_photo;
@property(retain, nonatomic) UIButton *photoBtn; // @synthesize photoBtn=_photoBtn;
@property(nonatomic) _Bool bDoubleCheck; // @synthesize bDoubleCheck=_bDoubleCheck;
@property(nonatomic) _Bool bLastWrong; // @synthesize bLastWrong=_bLastWrong;
@property(retain, nonatomic) IDFrameView *frameView; // @synthesize frameView=_frameView;
@property(retain, nonatomic) IDCameraController *cameraController; // @synthesize cameraController=_cameraController;
@property(nonatomic) _Bool isFront; // @synthesize isFront=_isFront;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
@property(copy, nonatomic) CDUnknownBlockType recognizeBlock; // @synthesize recognizeBlock=_recognizeBlock;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didFinishPhotoRec;
- (void)returnIDPhotoResult:(id)arg1 from:(id)arg2;
- (id)convertDateFromeString:(id)arg1;
- (_Bool)isIncludeChineseCharacter:(id)arg1;
- (id)switchIDCardInfoFromIdInfo:(id)arg1;
- (void)setDefaultPrompt;
- (void)IDCardRecognited:(id)arg1;
- (_Bool)checkIDResult:(id)arg1;
- (struct CGRect)getEffectImageRect:(struct CGSize)arg1;
- (void)photo:(id)arg1;
- (void)lightAction:(id)arg1;
- (void)backAction;
- (void)viewDidLoad;
- (void)dealloc;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)disableDoubleCheck;
- (void)viewWillDisappear:(_Bool)arg1;
- (_Bool)prefersStatusBarHidden;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

