//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IdInfo;

@protocol IDRecDelegate <NSObject>
- (_Bool)checkIDResult:(IdInfo *)arg1;
- (void)IDCardRecognited:(IdInfo *)arg1;
- (struct CGRect)getEffectImageRect:(struct CGSize)arg1;
@end

