//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ILivePushStream : NSObject
{
}

+ (id)shareInstance;
- (int)requestMultiVideoStreamerStop:(unsigned int)arg1 relationId:(unsigned int)arg2 channelIDs:(id)arg3 okBlock:(CDUnknownBlockType)arg4 errBlock:(CDUnknownBlockType)arg5;
- (int)requestMultiVideoStreamerStart:(unsigned int)arg1 relationId:(unsigned int)arg2 pushOption:(id)arg3 channels:(id)arg4 succ:(CDUnknownBlockType)arg5 fail:(CDUnknownBlockType)arg6;

@end

