//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ILVLiveMessage.h"

@class NSString, TIMUserProfile;

@interface ILVLiveTextMessage : ILVLiveMessage
{
    long long _type;
    long long _priority;
    NSString *_sendId;
    NSString *_recvId;
    NSString *_text;
    TIMUserProfile *_senderProfile;
}

@property(retain, nonatomic) TIMUserProfile *senderProfile; // @synthesize senderProfile=_senderProfile;
@property(retain, nonatomic) NSString *text; // @synthesize text=_text;
@property(retain, nonatomic) NSString *recvId; // @synthesize recvId=_recvId;
@property(retain, nonatomic) NSString *sendId; // @synthesize sendId=_sendId;
@property(nonatomic) long long priority; // @synthesize priority=_priority;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

