//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "AVPlayerViewController.h"

@class NSString;

@interface JKNAVPlayerViewController : AVPlayerViewController
{
    NSString *_videourl;
    NSString *_fullscreen;
    NSString *_playmode;
}

@property(copy, nonatomic) NSString *playmode; // @synthesize playmode=_playmode;
@property(copy, nonatomic) NSString *fullscreen; // @synthesize fullscreen=_fullscreen;
@property(copy, nonatomic) NSString *videourl; // @synthesize videourl=_videourl;
- (void).cxx_destruct;
- (void)back;
- (void)setBackBarButtonItemWithImageName:(id)arg1;
- (void)setBackBarButtonItem;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

