//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MBProgressHUDDelegate.h"

@class MBProgressHUD, NSString;

@interface JKNLoadingView : NSObject <MBProgressHUDDelegate>
{
    CDUnknownBlockType _callback;
    MBProgressHUD *_hud;
    CDUnknownBlockType _emptyRetryBlock;
    CDUnknownBlockType _networkErrorRetryBlock;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType networkErrorRetryBlock; // @synthesize networkErrorRetryBlock=_networkErrorRetryBlock;
@property(copy, nonatomic) CDUnknownBlockType emptyRetryBlock; // @synthesize emptyRetryBlock=_emptyRetryBlock;
@property(retain, nonatomic) MBProgressHUD *hud; // @synthesize hud=_hud;
@property(nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
- (void).cxx_destruct;
- (void)removeAllErrorViewInView:(id)arg1;
- (void)networkErrorRetryButtonAction:(id)arg1;
- (void)removeNetWorkViewInView:(id)arg1;
- (void)showNetworkErrorViewInView:(id)arg1 retryBlcok:(CDUnknownBlockType)arg2;
- (void)emptyRetryButtonAction:(id)arg1;
- (void)removeErrorViewInView:(id)arg1;
- (void)showErrorViewInView:(id)arg1 retryBlock:(CDUnknownBlockType)arg2;
- (void)showErrorViewInView:(id)arg1 error:(id)arg2 retryBlock:(CDUnknownBlockType)arg3;
- (void)removeNoDataViewInView:(id)arg1;
- (void)showNoDataViewInView:(id)arg1 noteText:(id)arg2;
- (void)showNoDataViewInView:(id)arg1;
- (void)hudWasHidden:(id)arg1;
- (void)hideHudAfterDelay:(double)arg1;
- (void)hideHud;
- (void)createHudWithContainView:(id)arg1;
- (void)showHudWithTextOnly:(id)arg1 inView:(id)arg2;
- (void)showHudWithText:(id)arg1 inView:(id)arg2;
- (void)showHudInView:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

