//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PAApi_MEPHISTOPAGE_PlateData, UILabel;

@interface JKNSpecialistHeadView : UIView
{
    PAApi_MEPHISTOPAGE_PlateData *_specialistModel;
    UIView *_leftLineView;
    UIView *_tagView;
    UIView *_bottomline;
    UILabel *_titleLabel;
    UILabel *_subTitleLabel;
}

@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *bottomline; // @synthesize bottomline=_bottomline;
@property(retain, nonatomic) UIView *tagView; // @synthesize tagView=_tagView;
@property(retain, nonatomic) UIView *leftLineView; // @synthesize leftLineView=_leftLineView;
@property(retain, nonatomic) PAApi_MEPHISTOPAGE_PlateData *specialistModel; // @synthesize specialistModel=_specialistModel;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

