//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JKNUrl : NSObject
{
}

+ (id)jkn_getTabJumpUrl:(id)arg1;
+ (void)jkn_cleanCacheRes;
+ (void)jkn_cacheRes;
+ (id)jkn_getResUrl;
+ (id)jkn_getResFolder;
+ (id)jkn_getUrlWithPagePath:(id)arg1;
+ (id)jkn_getUrlWithShortPagePath:(id)arg1;
+ (id)jkn_getUrlWithEntranceType:(long long)arg1;

@end

