//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface keplerSystemInfoModel : NSObject
{
    NSString *_cpuSubType;
    NSString *_countryIso;
    NSString *_version;
    NSString *_breakFlag;
    NSString *_idfa;
    NSString *_totalSpace;
    NSString *_networkType;
    NSString *_cpuCount;
    NSString *_os;
    NSString *_openudid;
    NSString *_ip;
    NSString *_screenRes;
    NSString *_idfv;
    NSString *_totalSpaceFree;
    NSString *_carrier;
    NSString *_cpuType;
    NSString *_bootTime;
    NSDictionary *_modelDic;
    NSString *_infoStr;
}

+ (id)sharedInstance;
@property(copy, nonatomic) NSString *infoStr; // @synthesize infoStr=_infoStr;
@property(retain, nonatomic) NSDictionary *modelDic; // @synthesize modelDic=_modelDic;
@property(copy, nonatomic) NSString *bootTime; // @synthesize bootTime=_bootTime;
@property(copy, nonatomic) NSString *cpuType; // @synthesize cpuType=_cpuType;
@property(copy, nonatomic) NSString *carrier; // @synthesize carrier=_carrier;
@property(copy, nonatomic) NSString *totalSpaceFree; // @synthesize totalSpaceFree=_totalSpaceFree;
@property(copy, nonatomic) NSString *idfv; // @synthesize idfv=_idfv;
@property(copy, nonatomic) NSString *screenRes; // @synthesize screenRes=_screenRes;
@property(copy, nonatomic) NSString *ip; // @synthesize ip=_ip;
@property(copy, nonatomic) NSString *openudid; // @synthesize openudid=_openudid;
@property(copy, nonatomic) NSString *os; // @synthesize os=_os;
@property(copy, nonatomic) NSString *cpuCount; // @synthesize cpuCount=_cpuCount;
@property(copy, nonatomic) NSString *networkType; // @synthesize networkType=_networkType;
@property(copy, nonatomic) NSString *totalSpace; // @synthesize totalSpace=_totalSpace;
@property(copy, nonatomic) NSString *idfa; // @synthesize idfa=_idfa;
@property(copy, nonatomic) NSString *breakFlag; // @synthesize breakFlag=_breakFlag;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *countryIso; // @synthesize countryIso=_countryIso;
@property(copy, nonatomic) NSString *cpuSubType; // @synthesize cpuSubType=_cpuSubType;
- (void).cxx_destruct;
- (id)getDeviceInfo;
- (void)desc;
- (void)_init;
- (id)init;

@end

