//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class KPLTDAAAppProfile, KPLTDAADeviceProfile, NSMutableArray, NSString;

@interface KPLTDAAEventPackage : NSObject
{
    NSString *_devId;
    NSString *_productId;
    KPLTDAAAppProfile *_appProfile;
    KPLTDAADeviceProfile *_deviceProfile;
    NSMutableArray *_messages;
}

@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(retain, nonatomic) KPLTDAADeviceProfile *deviceProfile; // @synthesize deviceProfile=_deviceProfile;
@property(retain, nonatomic) KPLTDAAAppProfile *appProfile; // @synthesize appProfile=_appProfile;
@property(retain, nonatomic) NSString *productId; // @synthesize productId=_productId;
@property(retain, nonatomic) NSString *devId; // @synthesize devId=_devId;
- (void).cxx_destruct;
- (void)messagePack:(struct msgpack_packer *)arg1;
- (id)init;

@end

