//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class AVCaptureDevice, AVCaptureDeviceInput, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureStillImageOutput, AVCaptureVideoPreviewLayer;

@interface LYCameraView : UIView
{
    _Bool _captureFlashModeOn;
    _Bool _isBackCamera;
    _Bool _isCapturing;
    unsigned long long _type;
    UIView *_overlayView;
    AVCaptureDevice *_device;
    AVCaptureDeviceInput *_input;
    AVCaptureMetadataOutput *_output;
    AVCaptureStillImageOutput *_ImageOutPut;
    AVCaptureSession *_session;
    AVCaptureVideoPreviewLayer *_previewLayer;
    UIView *_focusView;
}

+ (id)setting_url_string_type:(unsigned long long)arg1;
+ (void)photoLibAvailable:(CDUnknownBlockType)arg1;
+ (void)cameraAvailable:(CDUnknownBlockType)arg1;
+ (void)goToSettingPage:(unsigned long long)arg1;
+ (id)clipImage:(id)arg1 inRect:(struct CGRect)arg2;
@property(nonatomic) _Bool isCapturing; // @synthesize isCapturing=_isCapturing;
@property(nonatomic) _Bool isBackCamera; // @synthesize isBackCamera=_isBackCamera;
@property(retain, nonatomic) UIView *focusView; // @synthesize focusView=_focusView;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *previewLayer; // @synthesize previewLayer=_previewLayer;
@property(retain, nonatomic) AVCaptureSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVCaptureStillImageOutput *ImageOutPut; // @synthesize ImageOutPut=_ImageOutPut;
@property(retain, nonatomic) AVCaptureMetadataOutput *output; // @synthesize output=_output;
@property(retain, nonatomic) AVCaptureDeviceInput *input; // @synthesize input=_input;
@property(retain, nonatomic) AVCaptureDevice *device; // @synthesize device=_device;
@property(retain, nonatomic) UIView *overlayView; // @synthesize overlayView=_overlayView;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) _Bool captureFlashModeOn; // @synthesize captureFlashModeOn=_captureFlashModeOn;
- (void).cxx_destruct;
- (id)cameraWithPosition:(long long)arg1;
@property(readonly, nonatomic) _Bool canTakePicture;
@property(readonly, nonatomic) _Bool isFrontCamera;
- (id)fixImageOrientation:(id)arg1;
- (void)setSessionPreset;
- (void)focusInPoint:(struct CGPoint)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)changeCamera;
- (void)startCapture;
- (void)takePicture:(_Bool)arg1 callback:(CDUnknownBlockType)arg2;
- (id)initWithFrame:(struct CGRect)arg1 type:(unsigned long long)arg2 isback:(_Bool)arg3;
- (id)initFrontCameraWithFrame:(struct CGRect)arg1 type:(unsigned long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 type:(unsigned long long)arg2;

@end

