//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface MPLocalNotifiCenter : NSObject
{
    _Bool _checkRemoteNotificationAvailability;
    CDUnknownBlockType _localNotificationHandler;
    NSMutableDictionary *_localPushDictionary;
}

+ (id)defaultCenter;
@property(nonatomic) _Bool checkRemoteNotificationAvailability; // @synthesize checkRemoteNotificationAvailability=_checkRemoteNotificationAvailability;
@property(retain, nonatomic) NSMutableDictionary *localPushDictionary; // @synthesize localPushDictionary=_localPushDictionary;
@property(copy, nonatomic) CDUnknownBlockType localNotificationHandler; // @synthesize localNotificationHandler=_localNotificationHandler;
- (void).cxx_destruct;
- (id)postNotificationOnNow:(_Bool)arg1 fireDate:(id)arg2 forKey:(id)arg3 alertBody:(id)arg4 alertAction:(id)arg5 soundName:(id)arg6 launchImage:(id)arg7 userInfo:(id)arg8 badgeCount:(unsigned long long)arg9 repeatInterval:(unsigned long long)arg10;
- (id)postNotificationOn:(id)arg1 forKey:(id)arg2 title:(id)arg3 content:(id)arg4 extention:(id)arg5 action:(id)arg6;
- (void)cancelLocalNotificationForKey:(id)arg1;
- (void)cancelAllLocalPushNotifications;
- (void)didReceiveLocalNotificationUserInfo:(id)arg1;
- (void)loadScheduledLocalPushNotificationsFromApplication;

@end

