//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldWebViewController.h"

#import "BookedTimeDelegate.h"
#import "DatePickerDelegate.h"
#import "PARSWebViewDelegate.h"

@class BookedPickerView, DatePickerViewController, EasyJSDataFunction, NSString, UIDatePicker, UIView;

@interface MyProductHomePageViewController : PARSOldWebViewController <PARSWebViewDelegate, DatePickerDelegate, BookedTimeDelegate>
{
    NSString *_dummyForAdr;
    UIView *_statusBarBackgroundView;
    UIView *errorView;
    _Bool isNotFirstLoad;
    BookedPickerView *_picker;
    UIView *limitPickerGroup;
    UIDatePicker *limitPicker;
    EasyJSDataFunction *dateCallBack;
    EasyJSDataFunction *callDate;
    EasyJSDataFunction *dateCallBackDeviceFail;
    unsigned long long _productType;
    DatePickerViewController *_datePicker;
    UIView *_datePickerContainnerView;
}

@property(retain, nonatomic) UIView *datePickerContainnerView; // @synthesize datePickerContainnerView=_datePickerContainnerView;
@property(retain, nonatomic) DatePickerViewController *datePicker; // @synthesize datePicker=_datePicker;
@property(nonatomic) unsigned long long productType; // @synthesize productType=_productType;
- (void).cxx_destruct;
- (void)toHealthNewsPage;
- (void)dismissPicker7Days;
- (void)doneOver7DaysPicker;
- (void)nativeSetSevenDaysFuture:(id)arg1 endDate:(id)arg2;
- (void)nativeDateLimited:(id)arg1 callBack:(id)arg2 titleStr:(id)arg3 start:(id)arg4 end:(id)arg5;
- (void)openUrl:(id)arg1;
- (void)getBookedTime:(id)arg1;
- (void)showTime:(id)arg1 callBack:(id)arg2 title:(id)arg3 optionalDate:(id)arg4;
- (void)clear;
- (void)doneWith:(id)arg1;
- (void)nativeDate:(id)arg1 callBack:(id)arg2 title:(id)arg3 maxYear:(id)arg4 minYear:(id)arg5;
- (void)showPage:(id)arg1;
- (void)dissmissDatePiceker:(id)arg1;
- (void)suggestionFeedback;
- (void)reload;
- (void)showErrorView:(id)arg1;
- (void)parsWebView:(id)arg1 didFailLoadWithError:(id)arg2;
- (void)parsWebViewDidFinishLoad:(id)arg1;
- (void)parsWebViewDidStartLoad:(id)arg1;
- (void)goAround;
- (void)PAKeyBoardHidden;
- (void)PAKeyBoardShow;
- (void)removePAKeyboardObserver;
- (void)addPAKeyboardObserver;
- (void)inputString:(id)arg1;
- (void)showKeyboard:(id)arg1 succCallBack:(id)arg2 failforAdr:(id)arg3 failCallBack:(id)arg4 paramString:(id)arg5;
- (void)hideKeyboard:(id)arg1 succCallBack:(id)arg2 failforAdr:(id)arg3 failCallBack:(id)arg4 paramString:(id)arg5;
- (void)getCVAndSecurityToken:(id)arg1 succCallBack:(id)arg2 failforAdr:(id)arg3 failCallBack:(id)arg4 paramString:(id)arg5;
- (void)appDismissWebView:(id)arg1 succCallBack:(id)arg2 failforAdr:(id)arg3 failCallBack:(id)arg4 paramString:(id)arg5;
- (void)getPhoneNumber:(id)arg1 succCallBack:(id)arg2 failforAdr:(id)arg3 failCallBack:(id)arg4 paramString:(id)arg5;
- (void)didReceiveMemoryWarning;
- (void)goToWealthProductDetail:(id)arg1;
- (void)callPhone:(id)arg1;
- (void)cancel;
- (void)back;
- (void)loginAgain;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

