//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PARSActivityDetailModel, UITableView, UIView;

@interface MyPraiseListViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSString *_groupID;
    NSString *_listType;
    UITableView *_tableView;
    UIView *_refreshView;
    PARSActivityDetailModel *_activity;
    NSString *_praiseType;
    NSArray *_contents;
}

@property(retain, nonatomic) NSArray *contents; // @synthesize contents=_contents;
@property(retain, nonatomic) NSString *praiseType; // @synthesize praiseType=_praiseType;
@property(retain, nonatomic) PARSActivityDetailModel *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) UIView *refreshView; // @synthesize refreshView=_refreshView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(copy, nonatomic) NSString *listType; // @synthesize listType=_listType;
@property(copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)back;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)addLeftRegionOfNavigationBar;
- (void)setExtraCellLineHidden;
- (void)initRefreshView;
- (void)initUI;
- (void)updateData;
- (void)viewDidLoad;
- (id)initWithActivity:(id)arg1 praiseType:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

