//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDate.h"

@interface NSDate (Calendar)
- (id)getDateStringWithFormat:(id)arg1;
- (long long)startDay;
- (id)getDateOfYear;
- (id)getDateOfDay;
- (id)getDateOfMonth;
- (id)getDayOfWeekShortString;
- (id)addDays:(long long)arg1;
- (id)getWeekDay;
- (id)getWeekStartDate:(long long)arg1;
@end

