//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (Kepler)
- (unsigned long long)keplerHexFromString;
- (id)KeplerUrlEncodingString;
- (id)keplerMaskMobile;
- (_Bool)KeplervalidateIDCardNumber;
- (_Bool)KeplervalidateMobileNumber;
@end

