//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

@interface NSString (jkn_Drawing)
- (struct CGSize)jkn_sizeWithFont:(id)arg1 maxSize:(struct CGSize)arg2;
- (id)jkn_attributedStringFromStingWithFont:(id)arg1 withLineSpacing:(double)arg2;
- (struct CGSize)jkn_sizeWithMaxWidth:(double)arg1 font:(id)arg2 lineSpacing:(double)arg3 paragraphSpacing:(double)arg4;
- (struct CGSize)jkn_sizeWithMaxWidth:(double)arg1 font:(id)arg2 lineSpacing:(double)arg3;
- (struct CGSize)jkn_sizeWithMaxWidth:(double)arg1 font:(id)arg2;
- (struct CGSize)jkn_sizeWithConstrainedSize:(struct CGSize)arg1 font:(id)arg2 lineSpacing:(double)arg3 paragraphSpacing:(double)arg4;
- (struct CGSize)jkn_sizeWithConstrainedSize:(struct CGSize)arg1 font:(id)arg2 lineSpacing:(double)arg3;
@end

