//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PAApi_MEPHISTOPAGE_ForumData : NSObject
{
    long long _identify;
    NSString *_status;
    NSString *_name;
    NSString *_photoUrl;
    long long _weight;
    long long _postsQuantity;
    long long _domainId;
    long long _withheld;
    NSString *_pageUrl;
}

+ (id)deserialize:(id)arg1;
+ (id)deserializeWithJsonData:(id)arg1;
@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(nonatomic) long long withheld; // @synthesize withheld=_withheld;
@property(nonatomic) long long domainId; // @synthesize domainId=_domainId;
@property(nonatomic) long long postsQuantity; // @synthesize postsQuantity=_postsQuantity;
@property(nonatomic) long long weight; // @synthesize weight=_weight;
@property(retain, nonatomic) NSString *photoUrl; // @synthesize photoUrl=_photoUrl;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(nonatomic) long long identify; // @synthesize identify=_identify;
- (void).cxx_destruct;
- (id)serialize;

@end

