//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface PAApi_ACTCENTER_HealthCalendarList : NSObject
{
    _Bool _hasNewPlan;
    long long _currentDate;
    NSMutableArray *_list;
    long long _cacheDay;
    NSMutableArray *_recommendCategories;
}

+ (id)deserialize:(id)arg1;
+ (id)deserializeWithJsonData:(id)arg1;
@property(nonatomic) _Bool hasNewPlan; // @synthesize hasNewPlan=_hasNewPlan;
@property(retain, nonatomic) NSMutableArray *recommendCategories; // @synthesize recommendCategories=_recommendCategories;
@property(nonatomic) long long cacheDay; // @synthesize cacheDay=_cacheDay;
@property(retain, nonatomic) NSMutableArray *list; // @synthesize list=_list;
@property(nonatomic) long long currentDate; // @synthesize currentDate=_currentDate;
- (void).cxx_destruct;
- (id)serialize;
- (id)init;

@end

