//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PAIMTXBaseViewController.h"

#import "CLLocationManagerDelegate.h"
#import "MKMapViewDelegate.h"

@class CLLocationManager, MKMapView, NSString, PAIMBubbleChatController;

@interface PAIMShareCurrentLocationViewController : PAIMTXBaseViewController <MKMapViewDelegate, CLLocationManagerDelegate>
{
    MKMapView *mapView;
    NSString *strLatitude;
    NSString *strLongitude;
    CLLocationManager *locmanager;
    _Bool wasFound;
    NSString *locationString;
    PAIMBubbleChatController *bubbleController;
}

@property(retain, nonatomic) NSString *locationString; // @synthesize locationString;
@property(retain, nonatomic) NSString *strLongitude; // @synthesize strLongitude;
@property(retain, nonatomic) NSString *strLatitude; // @synthesize strLatitude;
- (void).cxx_destruct;
- (void)dealloc;
- (void)mapView:(id)arg1 didSelectAnnotationView:(id)arg2;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)refreshLocation;
- (void)showParking:(struct CLLocationCoordinate2D)arg1 currentLocation:(id)arg2;
- (void)showInfoOfMap;
- (void)updateLocation;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateToLocation:(id)arg2 fromLocation:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)sendLocation;
- (id)initWithController:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

