//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PAIMXMPPModule.h"

@interface PAIMXMPPFeature : PAIMXMPPModule
{
}

- (_Bool)handleElement:(id)arg1;
- (id)processFeaturesElement;
- (_Bool)shouldprocessFeaturesElement;
- (_Bool)handleFeatures:(id)arg1;
- (void)deactivate;
- (_Bool)activate:(id)arg1;

@end

