//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"
#import "PAIMXMPPRoomOccupant.h"

@class NSDate, NSString, PAIMXMPPJID, PAIMXMPPPresence;

@interface PAIMXMPPRoomOccupantHybridMemoryStorageObject : NSObject <PAIMXMPPRoomOccupant, NSCopying, NSCoding>
{
    PAIMXMPPPresence *presence;
    PAIMXMPPJID *jid;
    NSDate *createdAt;
    PAIMXMPPJID *streamFullJid;
}

- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
@property(readonly) unsigned long long hash;
- (long long)compareByCreatedAt:(id)arg1;
- (long long)compareByNickname:(id)arg1;
@property(readonly) PAIMXMPPJID *streamFullJid;
@property(readonly) NSDate *createdAt;
@property(readonly) PAIMXMPPJID *realJID;
@property(readonly) NSString *affiliation;
@property(readonly) NSString *role;
- (id)itemAttributeStringValueForName:(id)arg1;
@property(readonly) NSString *nickname;
@property(readonly) PAIMXMPPJID *roomJID;
@property(readonly) PAIMXMPPJID *jid;
@property(readonly) PAIMXMPPPresence *presence;
- (void)updateWithPresence:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithPresence:(id)arg1 streamFullJid:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

