//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PAIMDDASLLogCapture : NSObject
{
}

+ (void)captureAslLogs;
+ (void)aslMessageRecieved:(struct __asl_object_s *)arg1;
+ (void)configureAslQuery:(struct __asl_object_s *)arg1;
+ (void)setCaptureLogLevel:(int)arg1;
+ (int)captureLogLevel;
+ (void)stop;
+ (void)start;

@end

