//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PAIMThdRequestProtocol.h"

@class NSMutableData, NSMutableDictionary, NSString, PAIMUploadFileConfigModel;

@interface PAIMBaseThirdRequest : NSObject <PAIMThdRequestProtocol>
{
    _Bool _allowResumeForFileDownloads;
    id <PAIMAFNRequsetDelegate> _requestDelgate;
    NSString *_url;
    double _timeOutSeconds;
    NSString *_temporaryFileDownloadPath;
    NSString *_downloadDestinationPath;
    unsigned long long _partialDownloadSize;
    unsigned long long _totalDownloadSize;
    unsigned long long _downloadCacheSize;
    NSMutableData *_downloadCache;
    PAIMUploadFileConfigModel *_fileConfigModel;
    NSMutableDictionary *_httpHeadSettings;
    NSMutableDictionary *_params;
}

+ (_Bool)removeFileAtPath:(id)arg1 error:(id *)arg2;
@property(retain, nonatomic) NSMutableDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSMutableDictionary *httpHeadSettings; // @synthesize httpHeadSettings=_httpHeadSettings;
@property(retain, nonatomic) PAIMUploadFileConfigModel *fileConfigModel; // @synthesize fileConfigModel=_fileConfigModel;
@property(retain, nonatomic) NSMutableData *downloadCache; // @synthesize downloadCache=_downloadCache;
@property(nonatomic) unsigned long long downloadCacheSize; // @synthesize downloadCacheSize=_downloadCacheSize;
@property(nonatomic) unsigned long long totalDownloadSize; // @synthesize totalDownloadSize=_totalDownloadSize;
@property(nonatomic) unsigned long long partialDownloadSize; // @synthesize partialDownloadSize=_partialDownloadSize;
@property(nonatomic) _Bool allowResumeForFileDownloads; // @synthesize allowResumeForFileDownloads=_allowResumeForFileDownloads;
@property(retain, nonatomic) NSString *downloadDestinationPath; // @synthesize downloadDestinationPath=_downloadDestinationPath;
@property(retain, nonatomic) NSString *temporaryFileDownloadPath; // @synthesize temporaryFileDownloadPath=_temporaryFileDownloadPath;
@property(nonatomic) double timeOutSeconds; // @synthesize timeOutSeconds=_timeOutSeconds;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(nonatomic) __weak id <PAIMAFNRequsetDelegate> requestDelgate; // @synthesize requestDelgate=_requestDelgate;
- (void).cxx_destruct;
- (void)refreshDownLoadData;
- (_Bool)moveToDownloadDestinationError:(id)arg1;
- (_Bool)removeTemporaryDownloadFile;
- (unsigned long long)tempFileSize;
- (void)addFile:(id)arg1 withFileName:(id)arg2 andContentType:(id)arg3 forKey:(id)arg4;
- (void)addFile:(id)arg1 forKey:(id)arg2;
- (void)addPostValue:(id)arg1 forKey:(id)arg2;
- (void)addRequestHeader:(id)arg1 value:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

