//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PAIMBaseModel : NSObject
{
}

- (id)dateFromValue:(id)arg1;
- (_Bool)booleanFromValue:(id)arg1;
- (id)stringFromValue:(id)arg1;
- (double)floatFromValue:(id)arg1;
- (long long)intFromValue:(id)arg1;

@end

