//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PAIMDeviceInfo : NSObject
{
}

+ (id)getDeviceInfo:(id)arg1;
+ (id)deviceProperties;
+ (id)uniqueGlobalDeviceIdentifier;
+ (id)uniqueDeviceIdentifier;
+ (id)macaddress;
+ (id)machineName;
+ (id)stringFromMD5From:(id)arg1;

@end

