//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@protocol PAIMThdRequestProtocol <NSObject>
- (void)cancel;
- (void)uploadFileWithUrl:(NSString *)arg1 delegate:(id)arg2;
- (void)downloadMediaWithUrl:(NSString *)arg1 delegate:(id)arg2;
- (void)post:(NSString *)arg1 data:(NSData *)arg2 completionBlock:(void (^)(PAIMResponseModel *))arg3 failedBlock:(void (^)(PAIMResponseModel *))arg4;
@end

