//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PAHTTPRequestDelegate.h"
#import "QiniuUploadDelegate.h"

@class NSDictionary, NSMutableArray, NSString, PAIMGetTokenTool, PAIMMediaUploader, PAIMQiniuSimpleUploader;

@interface PAIMGroupHTTPManager : NSObject <PAHTTPRequestDelegate, QiniuUploadDelegate>
{
    CDUnknownBlockType requestFinished;
    CDUnknownBlockType requestListFinished;
    CDUnknownBlockType memberListFinished;
    CDUnknownBlockType hanldGroupRequestFinished;
    PAIMGetTokenTool *_getToken;
    PAIMQiniuSimpleUploader *_uploader;
    NSString *_headImagePath;
    NSString *_uploadURL;
    CDUnknownBlockType upLoadFinished;
    NSMutableArray *_queue;
    PAIMMediaUploader *_mediaUploader;
    CDUnknownBlockType groupLitRequest;
    long long groupMemberRequestTag;
    long long _pageNumber;
    NSString *_memberVersion;
    id <PAIMGroupHTTPManagerDelegate> _delegate;
    NSDictionary *_userInfo;
}

@property(retain, nonatomic) NSDictionary *userInfo; // @synthesize userInfo=_userInfo;
@property(nonatomic) id <PAIMGroupHTTPManagerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSString *memberVersion; // @synthesize memberVersion=_memberVersion;
@property(nonatomic) long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(nonatomic) long long groupMemberRequestTag; // @synthesize groupMemberRequestTag;
@property(copy, nonatomic) CDUnknownBlockType groupLitRequest; // @synthesize groupLitRequest;
- (void).cxx_destruct;
- (void)dealloc;
- (void)cancelUpload;
- (void)cancel;
- (void)hanldError:(long long)arg1 withError:(id)arg2;
- (void)uploadMediaDidSuccessWithKey:(id)arg1 andObject:(id)arg2;
- (void)uploadMediaDidFail:(id)arg1 object:(id)arg2;
- (void)upLoadHeadImage:(id)arg1 upLoadFinished:(CDUnknownBlockType)arg2;
- (void)requestFailed:(id)arg1 error:(id)arg2;
- (void)requestFinished:(id)arg1 withResult:(id)arg2;
- (void)getGroupVersionWithGroupID:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)getGroupVersionWithVersion:(id)arg1 groupID:(id)arg2;
- (void)getGroupSettingInfoWithVersion:(id)arg1 groupIDList:(id)arg2;
- (void)syncGroupChangeInfo:(id)arg1 page:(long long)arg2;
- (void)getGroupMemberWithGroupID:(id)arg1 version:(id)arg2 page:(long long)arg3;
- (void)saveToAddressList:(id)arg1 state:(_Bool)arg2 finished:(CDUnknownBlockType)arg3;
- (void)getGroupListWithVersion:(id)arg1 pageNO:(int)arg2 finished:(CDUnknownBlockType)arg3;
- (void)getGroupMemberWithVersion:(id)arg1;
- (void)getGroupMemberWithVersion:(id)arg1 tempModel:(id)arg2;
- (void)newMessageRemind:(id)arg1 state:(_Bool)arg2 finished:(CDUnknownBlockType)arg3;
- (void)setPortraitToGroupID:(id)arg1 withURL:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)removeGroupMemberJID:(id)arg1 fromGroup:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)joinGroup:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)changeGroupNickWithId:(id)arg1 to:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)changeGroupNameWithId:(id)arg1 to:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)getGroupInfo:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)getGroupMemberList:(id)arg1 updatetime:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)getGroupMemberList:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)getGroupChatList:(CDUnknownBlockType)arg1;
- (void)invitationGroup:(id)arg1 friends:(id)arg2 finished:(CDUnknownBlockType)arg3;
- (void)quitGroup:(id)arg1 finished:(CDUnknownBlockType)arg2;
- (void)createGroup:(id)arg1 users:(id)arg2 groupType:(long long)arg3 portraiturl:(id)arg4 finished:(CDUnknownBlockType)arg5;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

