//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSString;

@interface PAIMApiSettingModel : NSObject
{
    _Bool _stickie;
    _Bool _showBadge;
    _Bool _showNickName;
    _Bool _notifyNewMessage;
    NSString *_conversationID;
    NSString *_backGroundImg;
    long long _defaultBackdImg;
    NSDate *_stickieTime;
    unsigned long long _chatType;
    unsigned long long _keyBoardType;
}

@property(nonatomic) unsigned long long keyBoardType; // @synthesize keyBoardType=_keyBoardType;
@property(nonatomic) unsigned long long chatType; // @synthesize chatType=_chatType;
@property(retain, nonatomic) NSDate *stickieTime; // @synthesize stickieTime=_stickieTime;
@property(nonatomic) _Bool notifyNewMessage; // @synthesize notifyNewMessage=_notifyNewMessage;
@property(nonatomic) long long defaultBackdImg; // @synthesize defaultBackdImg=_defaultBackdImg;
@property(nonatomic) _Bool showNickName; // @synthesize showNickName=_showNickName;
@property(nonatomic) _Bool showBadge; // @synthesize showBadge=_showBadge;
@property(retain, nonatomic) NSString *backGroundImg; // @synthesize backGroundImg=_backGroundImg;
@property(nonatomic) _Bool stickie; // @synthesize stickie=_stickie;
@property(retain, nonatomic) NSString *conversationID; // @synthesize conversationID=_conversationID;
- (void).cxx_destruct;
- (id)initWithConversationID:(id)arg1 stickie:(_Bool)arg2 backGroundImg:(id)arg3 showBadge:(_Bool)arg4 chatType:(unsigned long long)arg5 showNickName:(_Bool)arg6 defaultBackdImg:(long long)arg7 notifyNewMessage:(_Bool)arg8 stickieTime:(id)arg9;

@end

