//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PAIMSpeexCodec : NSObject
{
    int codecOpenedTimes;
    int encodeFrameSize;
    int decodeFrameSize;
    struct SpeexBits encodeSpeexBits;
    struct SpeexBits decodeSpeexBits;
    void *encodeState;
    void *decodeState;
}

- (void)dealloc;
- (void)close;
- (int)decode:(char *)arg1 length:(int)arg2 output:(short *)arg3;
- (id)encode:(short *)arg1 length:(int)arg2;
- (void)open:(int)arg1;
- (id)init;

@end

