//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PAIMApiMessageModel, PAIMFlatRoundedButton, PAIMUIExpandingTextViewInternal, UIButton, UIImageView, UILabel;

@interface PAIMChatBaseCell : UITableViewCell
{
    id <ChatMessageViewDelegate> _delegate;
    unsigned long long _chatStyle;
    PAIMFlatRoundedButton *_headImageView;
    PAIMApiMessageModel *_chatMessageData;
    UIButton *_bubbleButton;
    UILabel *_nickname;
    double _distanceBetweenContentToLeft;
    PAIMUIExpandingTextViewInternal *_inputTextView;
    UIImageView *_timeView;
    UIImageView *_activityIndicator;
    UIButton *_failMessageView;
}

@property(retain, nonatomic) UIButton *failMessageView; // @synthesize failMessageView=_failMessageView;
@property(retain, nonatomic) UIImageView *activityIndicator; // @synthesize activityIndicator=_activityIndicator;
@property(retain, nonatomic) UIImageView *timeView; // @synthesize timeView=_timeView;
@property(nonatomic) __weak PAIMUIExpandingTextViewInternal *inputTextView; // @synthesize inputTextView=_inputTextView;
@property(readonly, nonatomic) double distanceBetweenContentToLeft; // @synthesize distanceBetweenContentToLeft=_distanceBetweenContentToLeft;
@property(retain, nonatomic) UILabel *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) UIButton *bubbleButton; // @synthesize bubbleButton=_bubbleButton;
@property(retain, nonatomic) PAIMApiMessageModel *chatMessageData; // @synthesize chatMessageData=_chatMessageData;
@property(retain, nonatomic) PAIMFlatRoundedButton *headImageView; // @synthesize headImageView=_headImageView;
@property(readonly, nonatomic) unsigned long long chatStyle; // @synthesize chatStyle=_chatStyle;
@property(nonatomic) __weak id <ChatMessageViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)canBecomeFirstResponder;
- (void)deleteMSG:(id)arg1;
- (void)resendMSG:(id)arg1;
- (void)copyMSG:(id)arg1;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (void)updateUploadProgress:(double)arg1;
- (void)resendFailedMessage;
- (void)getSelfHeaderImageUrl:(id *)arg1 placeholder:(id *)arg2;
- (id)getNicknameFrom:(id)arg1;
- (void)activityStopAnimateIfAnimating;
- (void)activityStartAnimating;
- (void)adjustActivityViewFrameWithNearestRect:(struct CGRect)arg1;
- (void)adjustFailMessageViewFrameWithNearestRect:(struct CGRect)arg1;
- (void)removeTimeVIew;
- (void)addTimeView;
- (_Bool)isCompanyRedPacket;
- (void)tryToSendFailedMessage;
@property(readonly, nonatomic) double distanceBetweenBubbleToTop;
@property(readonly, nonatomic) double distanceBetweenContentToTop;
@property(readonly, nonatomic) _Bool needShowTimeLabel;
- (int)showResendOriginType:(id)arg1;
- (id)initWithChatStyle:(unsigned long long)arg1 reuseIdentifier:(id)arg2;
- (void)dealloc;

@end

