//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PAIMWCXMPPManagerDelegate.h"

@class NSMutableArray, NSString;

@interface PAIMApiAppEvent : NSObject <PAIMWCXMPPManagerDelegate>
{
    NSMutableArray *multiDelegateArray_;
    id <PAIMApiAppEventDelegate> _logOutByOtherDeviceDelegate;
}

+ (id)shareInstance;
@property(nonatomic) id <PAIMApiAppEventDelegate> logOutByOtherDeviceDelegate; // @synthesize logOutByOtherDeviceDelegate=_logOutByOtherDeviceDelegate;
- (void).cxx_destruct;
- (void)xmpploginWillLoginFailureWithError:(id)arg1 loginType:(unsigned long long)arg2;
- (void)removeAppEventObserver:(id)arg1;
- (void)setNetWorkStateObserver:(id)arg1;
- (void)setLogoutByOtherDeviceDelegate:(id)arg1;
- (void)setDeviceToken:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

