//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UILabel.h"

@class NSAttributedString, NSMutableArray, NSMutableAttributedString, NSTextCheckingResult, UIColor;

@interface PAIMOHAttributedLabel : UILabel
{
    NSMutableAttributedString *_attributedText;
    struct __CTFrame *textFrame;
    struct CGRect drawingRect;
    NSMutableArray *customLinks;
    NSTextCheckingResult *activeLink;
    struct CGPoint touchStartPoint;
    NSMutableArray *images;
    NSMutableAttributedString *attrStrWithLinks;
    _Bool underlineLinks;
    _Bool centerVertically;
    _Bool onlyCatchTouchesOnLinks;
    _Bool extendBottomToFit;
    UIColor *linkColor;
    UIColor *highlightedLinkColor;
    unsigned long long automaticallyAddLinksForType;
    id <OHAttributedLabelDelegate> delegate;
    NSMutableArray *_imageInfoArr;
    NSMutableArray *_rects;
}

@property(retain, nonatomic) NSMutableArray *rects; // @synthesize rects=_rects;
@property(retain, nonatomic) NSMutableArray *imageInfoArr; // @synthesize imageInfoArr=_imageInfoArr;
@property(retain, nonatomic) NSTextCheckingResult *activeLink; // @synthesize activeLink;
@property(retain, nonatomic) NSMutableArray *images; // @synthesize images;
@property(nonatomic) __weak id <OHAttributedLabelDelegate> delegate; // @synthesize delegate;
@property(nonatomic) _Bool extendBottomToFit; // @synthesize extendBottomToFit;
@property(nonatomic) _Bool onlyCatchTouchesOnLinks; // @synthesize onlyCatchTouchesOnLinks;
@property(nonatomic) unsigned long long automaticallyAddLinksForType; // @synthesize automaticallyAddLinksForType;
@property(nonatomic) _Bool centerVertically; // @synthesize centerVertically;
@property(nonatomic) _Bool underlineLinks; // @synthesize underlineLinks;
@property(retain, nonatomic) UIColor *highlightedLinkColor; // @synthesize highlightedLinkColor;
@property(retain, nonatomic) UIColor *linkColor; // @synthesize linkColor;
@property(retain, nonatomic) NSMutableAttributedString *attrStrWithLinks; // @synthesize attrStrWithLinks;
- (void).cxx_destruct;
- (void)setNumberOfLines:(long long)arg1;
- (void)setAdjustsFontSizeToFitWidth:(_Bool)arg1;
- (void)warnAboutKnownIssues_CheckAdjustsFontSizeToFitWidth;
- (void)warnAboutKnownIssues_CheckLineBreakMode;
- (void)setNeedsDisplay;
- (void)setLineBreakMode:(long long)arg1;
- (void)setTextAlignment:(long long)arg1;
- (void)setTextColor:(id)arg1;
- (void)setFont:(id)arg1;
- (void)setText:(id)arg1;
@property(copy, nonatomic) NSAttributedString *attributedText;
- (void)attachImagesWithFrame:(struct __CTFrame *)arg1 withImages:(id)arg2 withContext:(struct CGContext *)arg3;
- (void)setAttString:(id)arg1 withImages:(id)arg2;
- (void)resetAttributedText;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)drawActiveLinkHighlightForRect:(struct CGRect)arg1;
- (void)drawTextInRect:(struct CGRect)arg1;
- (void)resetTextFrame;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)linkAtPoint:(struct CGPoint)arg1;
- (id)linkAtCharacterIndex:(long long)arg1;
- (id)attributedTextWithLinks;
- (void)removeAllCustomLinks;
- (void)addAddressLink:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)addUrlLink:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)addPhoneNumberLink:(id)arg1 inRange:(struct _NSRange)arg2;
- (void)addLinks:(id)arg1 string:(id)arg2 type:(unsigned long long)arg3;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)commonInit;

@end

