//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PAIMApiGroupInfoModel : NSObject
{
    _Bool _isMember;
    _Bool _msgSwitchOn;
    _Bool _isSave;
    NSString *_groupID;
    NSString *_nickName;
    NSString *_albumUrl;
    NSString *_ownerID;
    NSArray *_members;
    unsigned long long _groupType;
    long long _maxusers;
    long long _nameStatus;
}

@property(nonatomic) long long nameStatus; // @synthesize nameStatus=_nameStatus;
@property(nonatomic) long long maxusers; // @synthesize maxusers=_maxusers;
@property(nonatomic) _Bool isSave; // @synthesize isSave=_isSave;
@property(nonatomic) _Bool msgSwitchOn; // @synthesize msgSwitchOn=_msgSwitchOn;
@property(nonatomic) _Bool isMember; // @synthesize isMember=_isMember;
@property(nonatomic) unsigned long long groupType; // @synthesize groupType=_groupType;
@property(retain, nonatomic) NSArray *members; // @synthesize members=_members;
@property(retain, nonatomic) NSString *ownerID; // @synthesize ownerID=_ownerID;
@property(retain, nonatomic) NSString *albumUrl; // @synthesize albumUrl=_albumUrl;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;
- (id)initWithGroupID:(id)arg1 nickName:(id)arg2 albumUrl:(id)arg3 ownerID:(id)arg4 members:(id)arg5 groupType:(unsigned long long)arg6 isMember:(_Bool)arg7 msgSwitchOn:(_Bool)arg8 isSave:(_Bool)arg9 maxusers:(long long)arg10 nameStatus:(long long)arg11;

@end

