//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, PALHRequestMessage;

@protocol PALHServiceHandler <NSObject>
- (void)handleMessage:(PALHRequestMessage *)arg1 result:(void (^)(id, NSError *))arg2;
- (_Bool)canHandleAction:(NSString *)arg1;
- (NSArray *)actions;

@optional
- (NSArray *)authActions;
@end

