//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PALHServiceHandler.h"

#import "PARSShareActionViewDelegate.h"

@class NSString, PALHWebView, PARSPALHWebViewController;

@interface PALHWebviewServiceHandler : PALHServiceHandler <PARSShareActionViewDelegate>
{
    PALHWebView *_webView;
    PARSPALHWebViewController *_webViewController;
    CDUnknownBlockType _shareResultBlock;
    unsigned long long _shareActionType;
}

@property(nonatomic) unsigned long long shareActionType; // @synthesize shareActionType=_shareActionType;
@property(copy, nonatomic) CDUnknownBlockType shareResultBlock; // @synthesize shareResultBlock=_shareResultBlock;
@property(nonatomic) __weak PARSPALHWebViewController *webViewController; // @synthesize webViewController=_webViewController;
@property(nonatomic) __weak PALHWebView *webView; // @synthesize webView=_webView;
- (void).cxx_destruct;
- (void)style:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)renewalSuccess:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)handleSMSResult:(long long)arg1;
- (void)wbOnResp:(id)arg1;
- (void)wxOnResp:(id)arg1;
- (void)userDoNotInstallWeiBoApp;
- (void)userDoNotInstallWXApp;
- (void)shareView:(id)arg1 didSelectToShareWithType:(unsigned long long)arg2;
- (void)setNavBarAlpha:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)setBounces:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)share:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)executeUri:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)dismiss:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)openWealthWebView:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)moreButtonsConf:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)setNavRightBtn:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)setWebViewTitle:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)handleMessage:(id)arg1 result:(CDUnknownBlockType)arg2;
- (id)actions;
- (void)dealloc;
- (id)initWithWebView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

