//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, PALiveLoadMoreFooterView, PALiveSignInListViewModel, UICollectionView;

@interface PALiveSignInListView : UIView <UICollectionViewDelegate, UICollectionViewDataSource>
{
    _Bool _enablePullToLoadMore;
    UICollectionView *_collectionView;
    PALiveLoadMoreFooterView *_loadMoreView;
    PALiveSignInListViewModel *_viewModel;
}

@property(retain, nonatomic) PALiveSignInListViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak PALiveLoadMoreFooterView *loadMoreView; // @synthesize loadMoreView=_loadMoreView;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) _Bool enablePullToLoadMore; // @synthesize enablePullToLoadMore=_enablePullToLoadMore;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)pullToLoadMoreDidFinish;
- (void)triggerPullToLoadMore;
- (void)pullToLoadMoreDidTrigger;
- (void)restetLoadMoreState;
- (void)showNoMoreData;
- (id)initWithViewModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

