//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class PALiveViewerInfo, UIImageView, UILabel;

@interface PALiveSignInListViewCell : UICollectionViewCell
{
    PALiveViewerInfo *_item;
    UIImageView *_imageView;
    UILabel *_titleLable;
}

@property(retain, nonatomic) UILabel *titleLable; // @synthesize titleLable=_titleLable;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) PALiveViewerInfo *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)configWithItem:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

