//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, PALiveLoadMoreFooterView, UITableView, UIView;

@interface PALiveBaseTableViewVC : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    _Bool _enablePullToRefresh;
    _Bool _enablePullToLoadMore;
    _Bool _isObserving;
    _Bool _refreshing;
    _Bool _loadingMore;
    UITableView *_tableView;
    NSMutableArray *_dataArray;
    UIView *_refreshView;
    PALiveLoadMoreFooterView *_loadMoreView;
}

@property(nonatomic) __weak PALiveLoadMoreFooterView *loadMoreView; // @synthesize loadMoreView=_loadMoreView;
@property(retain, nonatomic) UIView *refreshView; // @synthesize refreshView=_refreshView;
@property(nonatomic) _Bool loadingMore; // @synthesize loadingMore=_loadingMore;
@property(nonatomic) _Bool refreshing; // @synthesize refreshing=_refreshing;
@property(nonatomic) _Bool isObserving; // @synthesize isObserving=_isObserving;
@property(nonatomic) _Bool enablePullToLoadMore; // @synthesize enablePullToLoadMore=_enablePullToLoadMore;
@property(nonatomic) _Bool enablePullToRefresh; // @synthesize enablePullToRefresh=_enablePullToRefresh;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)importLoadMoreView;
- (void)pullToLoadMoreDidFinish;
- (void)triggerPullToLoadMore;
- (void)pullToLoadMoreDidTrigger;
- (void)paRefreshTableHeaderDidTriggerRefresh:(id)arg1;
- (_Bool)paRefreshTableHeaderDataSourceIsLoading:(id)arg1;
- (void)addRefreshHeaderView:(_Bool)arg1;
- (void)pullToRefreshDidFinish;
- (void)autoPullToRefresh;
- (void)pullToRefreshDidTrigger;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)unregisterKeyPath;
- (void)registerKeyPath;
- (long long)headerViewStyle;
- (void)addHeaderView;
- (void)resetRefreshState;
- (void)restetLoadMoreState;
- (void)showNoMoreData;
- (void)createTableView;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

