//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PALiveButton;

@protocol PALiveBottomViewDelegate <NSObject>
- (void)onBottomViewChangeMicEnable:(PALiveButton *)arg1;
- (void)onBottomViewSwitchCamera;
- (void)onBottomViewShowMore;
- (void)onBottomViewShowShare;
- (void)onBottomViewShowGift;
- (void)onBottomViewShowPraise;
- (void)onBottomViewShowMsg:(unsigned long long)arg1;
@end

