//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PAZNBaseManager.h"

#import "TIMUserStatusListener.h"

@class NSString;

@interface PALiveIMLoginManager : PAZNBaseManager <TIMUserStatusListener>
{
    _Bool _isLoginSucc;
    _Bool _isIMLogining;
    long long _reLoginCount;
    NSString *_userSign;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSString *userSign; // @synthesize userSign=_userSign;
@property(nonatomic) long long reLoginCount; // @synthesize reLoginCount=_reLoginCount;
@property(nonatomic) _Bool isIMLogining; // @synthesize isIMLogining=_isIMLogining;
@property(nonatomic) _Bool isLoginSucc; // @synthesize isLoginSucc=_isLoginSucc;
- (void).cxx_destruct;
- (void)getUserIdSig:(id)arg1 succ:(CDUnknownBlockType)arg2 fail:(CDUnknownBlockType)arg3;
- (void)liveLogout:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)login:(id)arg1 sig:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)liveLogin:(id)arg1 sig:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)liveLogin:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (id)init;
- (void)destroyManager;
- (void)onForceOffline;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

