//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PALiveArcView, UIImageView, UILabel, UIScrollView;

@interface PALiveRefreshTableHeaderView : UIView
{
    int _state;
    id <PALiveRefreshTableHeaderViewDelegate> _delegate;
    UILabel *_statusLabel;
    UIImageView *_arrowImage;
    UIImageView *_circleImageView;
    UIScrollView *_scrollView;
    PALiveArcView *_arcView;
}

@property(nonatomic) __weak PALiveArcView *arcView; // @synthesize arcView=_arcView;
@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIImageView *circleImageView; // @synthesize circleImageView=_circleImageView;
@property(retain, nonatomic) UIImageView *arrowImage; // @synthesize arrowImage=_arrowImage;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(nonatomic) __weak id <PALiveRefreshTableHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) int state; // @synthesize state=_state;
- (void).cxx_destruct;
- (void)setScrollView:(id)arg1 contentInsetForTop:(double)arg2;
- (void)showLoading:(id)arg1;
- (void)paRefreshScrollViewDataSourceDidFinishedLoading:(id)arg1;
- (_Bool)paRefreshScrollViewDidEndDragging:(id)arg1;
- (void)paRefreshScrollViewDidScroll:(id)arg1;
- (void)updateArcViewWithScroll:(id)arg1;
- (void)updateArcViewWithPoint:(struct CGPoint)arg1;
- (void)stopAnimating;
- (void)startRotationAnimating;
- (id)initWithFrame:(struct CGRect)arg1;

@end

