//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "ILVLiveAVListener.h"
#import "ILVLiveIMListener.h"
#import "PALiveAttachViewControllerDelegate.h"
#import "PAliveViewerListVCDelegate.h"

@class NSString, PALiveAttachViewController, PALivePersonInfo, PALiveRoomInfo, PAZNMBProgressHUD, UIButton, UIScrollView;

@interface PALiveViewController : UIViewController <ILVLiveIMListener, PALiveAttachViewControllerDelegate, PAliveViewerListVCDelegate, ILVLiveAVListener>
{
    _Bool _isDismiss;
    _Bool _isOriNavigationBarHidden;
    _Bool _isHost;
    _Bool _isLandSpace;
    _Bool _isSelfCloseRoom;
    _Bool _isJoinRoomSucc;
    PAZNMBProgressHUD *_progressHUD;
    PALiveRoomInfo *_roomInfo;
    PALivePersonInfo *_curUserInfo;
    PALivePersonInfo *_hostInfo;
    NSString *_roomId;
    long long _lastOrientation;
    UIScrollView *_scrollContentView;
    UIButton *_closeButton;
    UIButton *_revertButton;
    UIButton *_fullScreenButton;
    PALiveAttachViewController *_uiVC;
}

@property(retain, nonatomic) PALiveAttachViewController *uiVC; // @synthesize uiVC=_uiVC;
@property(retain, nonatomic) UIButton *fullScreenButton; // @synthesize fullScreenButton=_fullScreenButton;
@property(retain, nonatomic) UIButton *revertButton; // @synthesize revertButton=_revertButton;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIScrollView *scrollContentView; // @synthesize scrollContentView=_scrollContentView;
@property(nonatomic) long long lastOrientation; // @synthesize lastOrientation=_lastOrientation;
@property(nonatomic) _Bool isJoinRoomSucc; // @synthesize isJoinRoomSucc=_isJoinRoomSucc;
@property(nonatomic) _Bool isSelfCloseRoom; // @synthesize isSelfCloseRoom=_isSelfCloseRoom;
@property(nonatomic) _Bool isLandSpace; // @synthesize isLandSpace=_isLandSpace;
@property(nonatomic) _Bool isHost; // @synthesize isHost=_isHost;
@property(nonatomic) _Bool isOriNavigationBarHidden; // @synthesize isOriNavigationBarHidden=_isOriNavigationBarHidden;
@property(copy, nonatomic) NSString *roomId; // @synthesize roomId=_roomId;
@property(retain, nonatomic) PALivePersonInfo *hostInfo; // @synthesize hostInfo=_hostInfo;
@property(retain, nonatomic) PALivePersonInfo *curUserInfo; // @synthesize curUserInfo=_curUserInfo;
@property(retain, nonatomic) PALiveRoomInfo *roomInfo; // @synthesize roomInfo=_roomInfo;
@property(nonatomic) _Bool isDismiss; // @synthesize isDismiss=_isDismiss;
@property(retain, nonatomic) PAZNMBProgressHUD *progressHUD; // @synthesize progressHUD=_progressHUD;
- (void).cxx_destruct;
- (void)onRefreshMainAVView:(id)arg1;
- (void)loginManagerZNForceOffline:(id)arg1;
- (void)loginManagerForceOffline:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)interfaceOrientation:(long long)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (_Bool)shouldAutorotate;
- (unsigned long long)supportedInterfaceOrientations;
- (void)deviceOrientationChanged;
- (void)listeningRotating;
- (void)onAppEnterBackground;
- (void)onTapFullScreenBtn:(id)arg1;
- (void)clickCloseBtn:(id)arg1;
- (void)sendCustomC2CMsg:(id)arg1 toUserId:(id)arg2 customCmd:(long long)arg3 succ:(CDUnknownBlockType)arg4 failed:(CDUnknownBlockType)arg5;
- (void)sendCustomGroupMsg:(id)arg1 msgPriority:(long long)arg2 customCmd:(long long)arg3 succ:(CDUnknownBlockType)arg4 failed:(CDUnknownBlockType)arg5;
- (_Bool)isLiveRoomHostOnVideo;
- (void)disMissVC;
- (void)exitLiveVC:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)leaveRoom:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)startHostRoom;
- (void)joinRoom:(int)arg1;
- (void)enterLiveRoom;
- (void)setScrollViewScrollEnabled:(_Bool)arg1;
- (void)resetScrollViewOffset;
- (void)hiddenBottomView:(_Bool)arg1;
- (void)hiddenMessageView:(_Bool)arg1;
- (void)refreshView;
- (void)refreshFullScreenButton;
- (void)createFullScreenButton;
- (void)addAVView;
- (void)layoutViews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithRoomId:(id)arg1 withRoomInfo:(id)arg2;
- (void)omRecvHostLeaveRoom;
- (void)omRecvHostEnterRoom:(id)arg1;
- (void)onRecvUpdateRoom:(id)arg1;
- (void)onRecvCloseRoom;
- (void)onRecvExitRoom:(id)arg1;
- (void)onRecvEnterRoom:(id)arg1;
- (void)onRecvPACustomMsg:(id)arg1;
- (void)onRecvRedEnvelope:(id)arg1;
- (void)onRecvGiftMsg:(id)arg1;
- (void)onRecvPraiseMsg:(id)arg1;
- (void)rejectToVideo:(id)arg1;
- (void)downToVideo:(id)arg1;
- (void)upToVideo:(id)arg1;
- (_Bool)isSendToSelf:(id)arg1;
- (void)onCustomMessage:(id)arg1;
- (void)onOtherMessage:(id)arg1;
- (void)homePage:(id)arg1;
- (void)share:(id)arg1;
- (void)reportAnchor;
- (void)reportAnchorText:(id)arg1;
- (void)reportAnchorVC:(id)arg1;
- (void)signIn:(id)arg1;
- (void)showMemberListVC:(id)arg1;
- (void)closeCurRoom:(id)arg1;
- (void)livePreviewStartLive:(id)arg1;
- (void)attachVC:(id)arg1 changeAudioMode:(_Bool)arg2;
- (void)attachVC:(id)arg1 selectMsg:(id)arg2;
- (void)attachVC:(id)arg1 globalMute:(_Bool)arg2;
- (void)sendPACustomMsg:(id)arg1 customType:(long long)arg2;
- (void)sendPAQuestionMsg:(id)arg1;
- (void)attachVC:(id)arg1 sendGift:(id)arg2;
- (void)attachVC:(id)arg1 sendPraise:(unsigned long long)arg2;
- (void)attachVC:(id)arg1 sendToHostMsg:(id)arg2;
- (void)attachVC:(id)arg1 sendMsg:(id)arg2 isQuestion:(_Bool)arg3;
- (void)addPlaceholderView:(id)arg1;
- (void)onTapInteractive:(id)arg1;
- (void)offVideoType:(long long)arg1 users:(id)arg2;
- (void)onVideoType:(long long)arg1 users:(id)arg2;
- (void)onFirstFrameRecved:(int)arg1 height:(int)arg2 identifier:(id)arg3 srcType:(long long)arg4;
- (void)onUserUpdateInfo:(long long)arg1 users:(id)arg2;
- (void)onRoomDisconnect:(int)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

