//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIActivityIndicatorView, UIColor, UILabel, UIPanGestureRecognizer, UIScrollView;

@interface PALiveLoadMoreFooterView : UIView
{
    _Bool _hideWhenNoData;
    _Bool _autoLoadMore;
    _Bool _hideLastTime;
    unsigned long long _loadStatus;
    UIScrollView *_scrollView;
    CDUnknownBlockType _loadingBlock;
    UIColor *_textColor;
    double _ignoreBottom;
    UIActivityIndicatorView *_activityView;
    UILabel *_loadStatusLabel;
    UILabel *_lastTimeLabel;
    UIPanGestureRecognizer *_panGesture;
    id _target;
    SEL _action;
    struct UIEdgeInsets _lastInsets;
}

+ (id)loadMoreViewWithTarget:(id)arg1 action:(SEL)arg2;
+ (id)loadMoreViewWithBlock:(CDUnknownBlockType)arg1;
@property(nonatomic) SEL action; // @synthesize action=_action;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) struct UIEdgeInsets lastInsets; // @synthesize lastInsets=_lastInsets;
@property(retain, nonatomic) UIPanGestureRecognizer *panGesture; // @synthesize panGesture=_panGesture;
@property(retain, nonatomic) UILabel *lastTimeLabel; // @synthesize lastTimeLabel=_lastTimeLabel;
@property(retain, nonatomic) UILabel *loadStatusLabel; // @synthesize loadStatusLabel=_loadStatusLabel;
@property(retain, nonatomic) UIActivityIndicatorView *activityView; // @synthesize activityView=_activityView;
@property(nonatomic) double ignoreBottom; // @synthesize ignoreBottom=_ignoreBottom;
@property(nonatomic) _Bool hideLastTime; // @synthesize hideLastTime=_hideLastTime;
@property(nonatomic) _Bool autoLoadMore; // @synthesize autoLoadMore=_autoLoadMore;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
@property(nonatomic) _Bool hideWhenNoData; // @synthesize hideWhenNoData=_hideWhenNoData;
@property(copy, nonatomic) CDUnknownBlockType loadingBlock; // @synthesize loadingBlock=_loadingBlock;
@property(readonly, nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) unsigned long long loadStatus; // @synthesize loadStatus=_loadStatus;
- (void).cxx_destruct;
- (void)removeObservers;
- (void)addObservers;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (double)getScrollViewPullOffsetY;
- (void)scrollViewPanStateDidChange:(id)arg1;
- (void)scrollViewContentSizeDidChange:(id)arg1;
- (void)scrollViewContentOffsetDidChange:(id)arg1;
- (void)resetLoadMoreData;
- (void)noMoreData;
- (void)endLoadMoreData;
- (void)beginLoadData;
- (void)loadMoreLastDate;
- (void)setUp;
- (void)willMoveToSuperview:(id)arg1;
- (id)init;
- (void)dealloc;

@end

