//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PAPayAccountEntity;

@interface PAPayInfoModel : NSObject
{
    PAPayAccountEntity *_paPapayAcount;
    CDUnknownBlockType _updatePapayAccountBlock;
    id <PAPayInfoModelDelegate> _hudDelegate;
}

+ (void)purgeSharedInstance;
+ (id)sharedInstance;
@property(nonatomic) __weak id <PAPayInfoModelDelegate> hudDelegate; // @synthesize hudDelegate=_hudDelegate;
@property(copy, nonatomic) CDUnknownBlockType updatePapayAccountBlock; // @synthesize updatePapayAccountBlock=_updatePapayAccountBlock;
@property(retain, nonatomic) PAPayAccountEntity *paPapayAcount; // @synthesize paPapayAcount=_paPapayAcount;
- (void).cxx_destruct;
- (void)addBankCard:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)bindCard:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)sendGetPaPayAndHqbBalanceRequst;
- (void)sendGetPaPayUserInfoTokenRequest;
- (void)sendSavePayTokenRequestParams:(id)arg1 WithCallBack:(CDUnknownBlockType)arg2;
- (void)updatePapayInfoToken:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (void)sendGetAccessToken:(id)arg1 withCallBack:(CDUnknownBlockType)arg2;
- (void)updateToken:(id)arg1 withBlock:(CDUnknownBlockType)arg2;
- (_Bool)isBindPapayAccount;
- (id)currentPapayAccountInfo;

@end

