//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "TCBlobDownloaderDelegate.h"

@class NSArray, NSObject<OS_dispatch_queue>, NSString, PAResources, TCBlobDownloadManager;

@interface PAResourcesDownloader : NSObject <TCBlobDownloaderDelegate>
{
    NSString *_resUrl;
    NSArray *_resourcesUrlArray;
    TCBlobDownloadManager *_sharedDownloadManager;
    PAResources *_cacheRes;
    NSObject<OS_dispatch_queue> *_revQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *revQueue; // @synthesize revQueue=_revQueue;
@property(retain, nonatomic) PAResources *cacheRes; // @synthesize cacheRes=_cacheRes;
@property(retain, nonatomic) TCBlobDownloadManager *sharedDownloadManager; // @synthesize sharedDownloadManager=_sharedDownloadManager;
@property(retain, nonatomic) NSArray *resourcesUrlArray; // @synthesize resourcesUrlArray=_resourcesUrlArray;
@property(retain, nonatomic) NSString *resUrl; // @synthesize resUrl=_resUrl;
- (void).cxx_destruct;
- (void)download:(id)arg1 didFinishWithSuccess:(_Bool)arg2 atPath:(id)arg3;
- (void)download:(id)arg1 didCancelRemovingFile:(_Bool)arg2;
- (void)download:(id)arg1 didStopWithError:(id)arg2;
- (void)download:(id)arg1 didReceiveData:(unsigned long long)arg2 onTotal:(unsigned long long)arg3;
- (void)download:(id)arg1 didReceiveFirstResponse:(id)arg2;
- (id)downloadFileNameForUrlString:(id)arg1;
- (id)downloadPath;
- (void)downloadFileWithRes:(id)arg1;
- (id)paraseResWithJsonString:(id)arg1;
- (id)paraseResWithFilePath:(id)arg1;
- (void)downloadWithResUrlArray:(id)arg1;
- (void)cacheResJSONFile;
- (void)cleanLogCache;
- (void)cleanCacheRes;
- (void)cacheResourcesAsync;
- (void)cacheRevJson;
- (id)md5FileWithFilePath:(id)arg1;
- (_Bool)checkRemoteResourceCacheStatusWithURL:(id)arg1;
- (_Bool)isReachableWithFilePath:(id)arg1 requestUrl:(id)arg2;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

