//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSString;

@interface PARSConversationQuitGroupChatRequest : PARSProtalBaseUserHTTPRequest
{
    NSString *_memberId;
    NSString *_groupId;
    NSString *_memberType;
}

@property(copy, nonatomic) NSString *memberType; // @synthesize memberType=_memberType;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *memberId; // @synthesize memberId=_memberId;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

