//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseHandler.h"

#import "PARSPocketEViewDataSource.h"
#import "PARSPocketEViewDelegate.h"

@class NSArray, NSString, PARSPocketEView;

@interface PARSPocketEHandler : PARSBaseHandler <PARSPocketEViewDataSource, PARSPocketEViewDelegate>
{
    NSString *_currentAgentName;
    NSString *_sourceChannel;
    NSArray *_pocketEViews;
    PARSPocketEView *_currentPocketEView;
}

@property(retain, nonatomic) PARSPocketEView *currentPocketEView; // @synthesize currentPocketEView=_currentPocketEView;
@property(retain, nonatomic) NSArray *pocketEViews; // @synthesize pocketEViews=_pocketEViews;
@property(copy, nonatomic) NSString *sourceChannel; // @synthesize sourceChannel=_sourceChannel;
@property(copy, nonatomic) NSString *currentAgentName; // @synthesize currentAgentName=_currentAgentName;
- (void).cxx_destruct;
- (_Bool)hideWhenTouchBackgroundView;
- (void)delaySchedule:(double)arg1;
- (void)schedule;
- (id)dequeue;
- (void)enqueue:(id)arg1;
- (void)showPocketEViewWithMessage:(id)arg1;
- (_Bool)validateCommand:(id)arg1;
- (void)dispatchWithCommand:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

