//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PARSMainAccountOpenWCAccountViewControllerDelegate.h"
#import "PARSMainAccountTipsAlert.h"
#import "PARSMainAccountWebViewDelegate.h"
#import "PARSWCPayOpenAccountViewControllerDelegate.h"

@class NSString, PARSMainAccountInfo, PARSMainAccountStatusResult, PARSMainAccountTipsAlert, PARSMainAccountUserInfo;

@interface PARSMainAccountStatusManager : NSObject <PARSWCPayOpenAccountViewControllerDelegate, PARSMainAccountOpenWCAccountViewControllerDelegate, PARSMainAccountWebViewDelegate, PARSMainAccountTipsAlert>
{
    _Bool _showTips;
    _Bool _isFromHomePage;
    PARSMainAccountInfo *_mainAccountInfo;
    PARSMainAccountTipsAlert *_tipsAlert;
    PARSMainAccountUserInfo *_mainAccountUserInfo;
    PARSMainAccountStatusResult *_openOldWCAccountStatusResult;
    CDUnknownBlockType _statusResultBlock;
}

+ (id)sharedManager;
@property(nonatomic) _Bool isFromHomePage; // @synthesize isFromHomePage=_isFromHomePage;
@property(nonatomic) _Bool showTips; // @synthesize showTips=_showTips;
@property(copy, nonatomic) CDUnknownBlockType statusResultBlock; // @synthesize statusResultBlock=_statusResultBlock;
@property(retain, nonatomic) PARSMainAccountStatusResult *openOldWCAccountStatusResult; // @synthesize openOldWCAccountStatusResult=_openOldWCAccountStatusResult;
@property(retain, nonatomic) PARSMainAccountUserInfo *mainAccountUserInfo; // @synthesize mainAccountUserInfo=_mainAccountUserInfo;
@property(retain, nonatomic) PARSMainAccountTipsAlert *tipsAlert; // @synthesize tipsAlert=_tipsAlert;
@property(retain, nonatomic) PARSMainAccountInfo *mainAccountInfo; // @synthesize mainAccountInfo=_mainAccountInfo;
- (void).cxx_destruct;
- (void)didCanceledUpgrade:(id)arg1;
- (void)didConfirmedToUpgrade:(id)arg1;
- (void)didOpenedChengziBankAndDismissedMAWebViewController:(id)arg1;
- (void)didDismissedMAWebViewController:(id)arg1;
- (void)didDoneOpenedMainAccountSucecss:(id)arg1;
- (void)didOpenedMainAccountAndDismissed:(id)arg1;
- (void)didDismissedMAOpenAccountViewController:(id)arg1;
- (void)openAccountDidSucecss:(id)arg1;
- (void)openAccountDidFinishWithoutAddCard:(id)arg1;
- (void)openAccountDidFinishWithoutSetPwd:(id)arg1;
- (void)didDismissedOpenAccountViewController:(id)arg1;
- (void)doOpenChengziBank;
- (void)showOpenChengziBankTips;
- (void)doUpgradeMainAccount;
- (void)showUpgradeMainAccountTips;
- (void)doOpenWCAccount;
- (void)cancelOpenOldWangCai;
- (void)showOpenWCAccountTips;
- (void)didLoginTimeout:(id)arg1;
- (void)cancelOpenMainAccount;
- (void)goOpenMainAccount;
- (void)showOpenMainAccountTips;
- (void)wangCaiOpenedAndNoNeedToUpgradeMainAccount;
- (void)checkUpStatusWithMainAccountInfo:(id)arg1;
- (void)checkUpStatusAndShowTips:(_Bool)arg1 withMainAccountUserInfo:(id)arg2 mainAccountInfo:(id)arg3 result:(CDUnknownBlockType)arg4;
- (void)checkUpStatusAndShowTips:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)checkUpStatusWithMainAccountInfo:(id)arg1 isFromHomePage:(_Bool)arg2 result:(CDUnknownBlockType)arg3;
- (void)checkUpStatusWithResult:(CDUnknownBlockType)arg1;
- (_Bool)checkMainAccountRiskStatus:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

