//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PARSWangCaiTradeResultPage, PARSWangCaiTradeResultPageViewModel;

@interface PARSWangCaiTradeResultController : UIViewController
{
    PARSWangCaiTradeResultPage *_resultView;
    PARSWangCaiTradeResultPageViewModel *_viewModel;
}

@property(retain, nonatomic) PARSWangCaiTradeResultPageViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) PARSWangCaiTradeResultPage *resultView; // @synthesize resultView=_resultView;
- (void).cxx_destruct;
- (void)viewDidLoad;
- (id)initWithType:(unsigned long long)arg1 parameter:(id)arg2;
- (void)dealloc;

@end

