//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSYYBaseUserCacheProvider.h"

@class NSString;

@interface PARSMainAccountDataProvider : PARSYYBaseUserCacheProvider
{
    NSString *_userId;
}

@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)queryMainAccountWCIncomeInfo;
- (void)updateMainAccountWCIncomeInfo:(id)arg1;
- (id)queryMainAccountInfo;
- (void)updateMainAccountInfo:(id)arg1;
- (id)initWithUserID:(id)arg1;

@end

