//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSMainAccountTipsAlert;

@protocol PARSMainAccountTipsAlert <NSObject>
- (void)didConfirmedToUpgrade:(PARSMainAccountTipsAlert *)arg1;

@optional
- (void)didCanceledUpgrade:(PARSMainAccountTipsAlert *)arg1;
@end

