//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

#import "PARSHCConversationBeanProtocol.h"

@class NSString, PARSCircleMemberInfo;

@interface PARSCircleInfo : PARSBaseInfo <PARSHCConversationBeanProtocol>
{
    _Bool _sound;
    _Bool _groupNicknameModified;
    NSString *_memberId;
    NSString *_smemberId;
    NSString *_circleId;
    NSString *_status;
    NSString *_scircleId;
    NSString *_scToken;
    NSString *_circleName;
    NSString *_type;
    NSString *_role;
    NSString *_imageURL;
    long long _memberCount;
    NSString *_agentNo;
    NSString *_agentName;
    long long _canModify;
    PARSCircleMemberInfo *_holder;
    PARSCircleMemberInfo *_customer;
    long long _msgCount;
    NSString *_message;
    NSString *_activeTime;
    NSString *_nickName;
    NSString *_activityId;
    NSString *_holderId;
}

@property(copy, nonatomic) NSString *holderId; // @synthesize holderId=_holderId;
@property(copy, nonatomic) NSString *activityId; // @synthesize activityId=_activityId;
@property(nonatomic) _Bool groupNicknameModified; // @synthesize groupNicknameModified=_groupNicknameModified;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(nonatomic) _Bool sound; // @synthesize sound=_sound;
@property(copy, nonatomic) NSString *activeTime; // @synthesize activeTime=_activeTime;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(nonatomic) long long msgCount; // @synthesize msgCount=_msgCount;
@property(retain, nonatomic) PARSCircleMemberInfo *customer; // @synthesize customer=_customer;
@property(retain, nonatomic) PARSCircleMemberInfo *holder; // @synthesize holder=_holder;
@property(nonatomic) long long canModify; // @synthesize canModify=_canModify;
@property(copy, nonatomic) NSString *agentName; // @synthesize agentName=_agentName;
@property(copy, nonatomic) NSString *agentNo; // @synthesize agentNo=_agentNo;
@property(nonatomic) long long memberCount; // @synthesize memberCount=_memberCount;
@property(copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
@property(copy, nonatomic) NSString *role; // @synthesize role=_role;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *circleName; // @synthesize circleName=_circleName;
@property(copy, nonatomic) NSString *scToken; // @synthesize scToken=_scToken;
@property(copy, nonatomic) NSString *scircleId; // @synthesize scircleId=_scircleId;
@property(copy, nonatomic) NSString *status; // @synthesize status=_status;
@property(copy, nonatomic) NSString *circleId; // @synthesize circleId=_circleId;
@property(copy, nonatomic) NSString *smemberId; // @synthesize smemberId=_smemberId;
@property(copy, nonatomic) NSString *memberId; // @synthesize memberId=_memberId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, nonatomic) _Bool newMsgAlert;
@property(readonly, nonatomic, getter=isGroupChat) _Bool groupChat;
@property(readonly, copy, nonatomic) NSString *title;
@property(readonly, nonatomic) unsigned long long circleRole;
- (unsigned long long)getRoleType;
@property(readonly, nonatomic) unsigned long long circleType;
- (unsigned long long)getCircleType;
@property(readonly, copy, nonatomic) NSString *receiverId;
- (id)initWithJson:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

