//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSWealthSearchHistoryTableHeaderView;

@protocol PARSWealthSearchHistoryTableHeaderViewDelegate <NSObject>
- (void)searchHistoryTableHeaderViewBeginSearch:(PARSWealthSearchHistoryTableHeaderView *)arg1;
@end

