//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSWangCaiCancelApplyParam : PARSBaseInfo
{
    NSString *_cancelReason;
    NSString *_frontOfIdCardImgUrl;
    NSString *_faceOfIdCardImgUrl;
    NSString *_holdingIdCardImgUrl;
}

@property(copy, nonatomic) NSString *holdingIdCardImgUrl; // @synthesize holdingIdCardImgUrl=_holdingIdCardImgUrl;
@property(copy, nonatomic) NSString *faceOfIdCardImgUrl; // @synthesize faceOfIdCardImgUrl=_faceOfIdCardImgUrl;
@property(copy, nonatomic) NSString *frontOfIdCardImgUrl; // @synthesize frontOfIdCardImgUrl=_frontOfIdCardImgUrl;
@property(copy, nonatomic) NSString *cancelReason; // @synthesize cancelReason=_cancelReason;
- (void).cxx_destruct;

@end

