//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, PARSCircleInfo, PARSCircleMemberListInfo, PARSConversationAnnouncementHandler, PARSConversationDeleteMemberHandler, PARSConversationGroupChatDetailHandler, PARSConversationGroupChatNameHandler, PARSConversationGroupInfo, PARSConversationQuitGroupChatHandler, PARSConversationUpdateNikNameHandler, PARSHealthCircleInfoHandler;

@interface PARSHCConversationInfoManager : NSObject
{
    NSString *_nickName;
    NSString *_groupName;
    NSString *_groupAnnouncement;
    PARSConversationGroupInfo *_groupInfo;
    PARSCircleInfo *_circleInfo;
    PARSCircleMemberListInfo *_oldMemberListInfo;
    NSArray *_oldMemberList;
    PARSConversationUpdateNikNameHandler *_updateNikNameHander;
    PARSConversationAnnouncementHandler *_announcementHandler;
    PARSConversationGroupChatNameHandler *_groupChatNameHandler;
    PARSConversationGroupChatDetailHandler *_groupChatDetailHandler;
    PARSConversationQuitGroupChatHandler *_quitGroupChatHandler;
    PARSConversationDeleteMemberHandler *_deleteMemberHandler;
    PARSHealthCircleInfoHandler *_healthCircleInfoHandler;
}

+ (id)sharedManager;
@property(retain, nonatomic) PARSHealthCircleInfoHandler *healthCircleInfoHandler; // @synthesize healthCircleInfoHandler=_healthCircleInfoHandler;
@property(retain, nonatomic) PARSConversationDeleteMemberHandler *deleteMemberHandler; // @synthesize deleteMemberHandler=_deleteMemberHandler;
@property(retain, nonatomic) PARSConversationQuitGroupChatHandler *quitGroupChatHandler; // @synthesize quitGroupChatHandler=_quitGroupChatHandler;
@property(retain, nonatomic) PARSConversationGroupChatDetailHandler *groupChatDetailHandler; // @synthesize groupChatDetailHandler=_groupChatDetailHandler;
@property(retain, nonatomic) PARSConversationGroupChatNameHandler *groupChatNameHandler; // @synthesize groupChatNameHandler=_groupChatNameHandler;
@property(retain, nonatomic) PARSConversationAnnouncementHandler *announcementHandler; // @synthesize announcementHandler=_announcementHandler;
@property(retain, nonatomic) PARSConversationUpdateNikNameHandler *updateNikNameHander; // @synthesize updateNikNameHander=_updateNikNameHander;
@property(retain, nonatomic) NSArray *oldMemberList; // @synthesize oldMemberList=_oldMemberList;
@property(retain, nonatomic) PARSCircleMemberListInfo *oldMemberListInfo; // @synthesize oldMemberListInfo=_oldMemberListInfo;
@property(retain, nonatomic) PARSCircleInfo *circleInfo; // @synthesize circleInfo=_circleInfo;
@property(retain, nonatomic) PARSConversationGroupInfo *groupInfo; // @synthesize groupInfo=_groupInfo;
@property(copy, nonatomic) NSString *groupAnnouncement; // @synthesize groupAnnouncement=_groupAnnouncement;
@property(copy, nonatomic) NSString *groupName; // @synthesize groupName=_groupName;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
- (void).cxx_destruct;
- (void)deleteMemberWithGroupId:(id)arg1 liveId:(id)arg2 memberIds:(id)arg3 result:(CDUnknownBlockType)arg4;
- (void)fetchQuitGroupChatWithNeedRefresh:(_Bool)arg1 GroupId:(id)arg2 memberId:(id)arg3 memberType:(id)arg4 ResultBlock:(CDUnknownBlockType)arg5;
- (void)fetchGroupChatDetailWithNeedRefresh:(_Bool)arg1 GroupId:(id)arg2 mobilePhone:(id)arg3 ResultBlock:(CDUnknownBlockType)arg4;
- (void)fetchGroupChatNameWithNeedRefresh:(_Bool)arg1 groupId:(id)arg2 mobilePhone:(id)arg3 groupChatName:(id)arg4 ResultBlock:(CDUnknownBlockType)arg5;
- (void)fetchAnnouncementWithNeedRefresh:(_Bool)arg1 groupId:(id)arg2 mobilePhone:(id)arg3 announcement:(id)arg4 ResultBlock:(CDUnknownBlockType)arg5;
- (void)fetchUpdateNikNameWithNeedRefresh:(_Bool)arg1 memberId:(id)arg2 groupId:(id)arg3 nikName:(id)arg4 type:(id)arg5 ResultBlock:(CDUnknownBlockType)arg6;
- (unsigned long long)heightForHCAnnoucementCell;
- (unsigned long long)heightForHCMemeberListForRole:(unsigned long long)arg1;
- (void)requestHealthCircleInfoMemberListWithCircleId:(id)arg1 pageNo:(long long)arg2 pageSize:(long long)arg3 result:(CDUnknownBlockType)arg4;
- (void)requestHealthCircleInfoWithCircleId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)clearData;

@end

