//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "PARSLiveSearchHistoryCellDelegate.h"
#import "PARSLiveSearchHistoryTableHeaderViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, PARSLiveSearchHistorySectionHeaderView, PARSLiveSearchHistoryTableHeaderView, UITableView;

@interface PARSLiveSearchHistoryController : PARSBaseViewController <UITableViewDelegate, UITableViewDataSource, PARSLiveSearchHistoryCellDelegate, PARSLiveSearchHistoryTableHeaderViewDelegate>
{
    id <PARSLiveSearchHistoryControllerDelegate> _delegate;
    UITableView *_tableView;
    PARSLiveSearchHistoryTableHeaderView *_tableHeaderView;
    PARSLiveSearchHistorySectionHeaderView *_searchHistorySectionHeaderView;
    NSString *_inputKeyword;
    NSMutableArray *_keywords;
}

@property(retain, nonatomic) NSMutableArray *keywords; // @synthesize keywords=_keywords;
@property(retain, nonatomic) NSString *inputKeyword; // @synthesize inputKeyword=_inputKeyword;
@property(retain, nonatomic) PARSLiveSearchHistorySectionHeaderView *searchHistorySectionHeaderView; // @synthesize searchHistorySectionHeaderView=_searchHistorySectionHeaderView;
@property(retain, nonatomic) PARSLiveSearchHistoryTableHeaderView *tableHeaderView; // @synthesize tableHeaderView=_tableHeaderView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <PARSLiveSearchHistoryControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)searchHistoryTableHeaderViewBeginSearch:(id)arg1;
- (void)liveSearchHistoryCell:(id)arg1 didTapDeleteButton:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didTapRootView:(id)arg1;
- (void)didTapClearButton:(id)arg1;
- (void)updateSearchHeaderView;
- (void)refreshUI;
- (void)loadData;
- (void)addSearchKeyword:(id)arg1;
- (void)updateSearchKeyword:(id)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

