//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSWangCaiTradePage.h"

@class UIButton, UILabel, UITapGestureRecognizer, UIView;

@interface PARSWangCaiTradeOutPage : PARSWangCaiTradePage
{
    UILabel *_lbLimitTip;
    UIView *_uvTradeOption;
    UIButton *_uvQuick;
    UIButton *_uvNormal;
    UIView *_uvLine;
    UILabel *_lbLimitBalance;
    UILabel *_lbQuickTrade;
    UILabel *_lbQuickTradeTip;
    UILabel *_lbQuickTradeTime;
    UILabel *_lbNormalTrade;
    UILabel *_lbNormalTradeTime;
    UIButton *_btnQuickCheck;
    UIButton *_btnNormalCheck;
    UITapGestureRecognizer *_quickTapped;
    UITapGestureRecognizer *_normalTapped;
    UITapGestureRecognizer *_dismissTapped;
}

@property(retain, nonatomic) UITapGestureRecognizer *dismissTapped; // @synthesize dismissTapped=_dismissTapped;
@property(retain, nonatomic) UITapGestureRecognizer *normalTapped; // @synthesize normalTapped=_normalTapped;
@property(retain, nonatomic) UITapGestureRecognizer *quickTapped; // @synthesize quickTapped=_quickTapped;
- (void).cxx_destruct;
@property(readonly, nonatomic) UILabel *lbLimitBalance; // @synthesize lbLimitBalance=_lbLimitBalance;
@property(readonly, nonatomic) UILabel *lbLimitTip; // @synthesize lbLimitTip=_lbLimitTip;
@property(readonly, nonatomic) UIView *uvTradeOption; // @synthesize uvTradeOption=_uvTradeOption;
@property(readonly, nonatomic) UIButton *uvNormal; // @synthesize uvNormal=_uvNormal;
@property(readonly, nonatomic) UIButton *btnNormalCheck; // @synthesize btnNormalCheck=_btnNormalCheck;
@property(readonly, nonatomic) UILabel *lbNormalTradeTime; // @synthesize lbNormalTradeTime=_lbNormalTradeTime;
@property(readonly, nonatomic) UILabel *lbNormalTrade; // @synthesize lbNormalTrade=_lbNormalTrade;
@property(readonly, nonatomic) UIView *uvLine; // @synthesize uvLine=_uvLine;
@property(readonly, nonatomic) UIButton *uvQuick; // @synthesize uvQuick=_uvQuick;
@property(readonly, nonatomic) UIButton *btnQuickCheck; // @synthesize btnQuickCheck=_btnQuickCheck;
@property(readonly, nonatomic) UILabel *lbQuickTradeTime; // @synthesize lbQuickTradeTime=_lbQuickTradeTime;
@property(readonly, nonatomic) UILabel *lbQuickTradeTip; // @synthesize lbQuickTradeTip=_lbQuickTradeTip;
@property(readonly, nonatomic) UILabel *lbQuickTrade; // @synthesize lbQuickTrade=_lbQuickTrade;
- (void)tradeOptionTapped:(id)arg1;
- (void)dismiss;
- (void)attach:(id)arg1;
- (void)dettach;
- (void)binderToViewModel:(id)arg1;

@end

