//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSWCOpenAccountUserInfo : PARSBaseInfo
{
    NSString *_realName;
    NSString *_identityNumber;
    NSString *_code;
    NSString *_message;
    NSString *_deviceNum;
}

@property(copy, nonatomic) NSString *deviceNum; // @synthesize deviceNum=_deviceNum;
@property(copy, nonatomic) NSString *message; // @synthesize message=_message;
@property(copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(copy, nonatomic) NSString *identityNumber; // @synthesize identityNumber=_identityNumber;
@property(copy, nonatomic) NSString *realName; // @synthesize realName=_realName;
- (void).cxx_destruct;

@end

