//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSString, PARSMyOrdeInfo, PARSResultView, PARSViewLogicNotifyObserver, UITableView;

@interface PARSMineOrderViewController : PARSBaseRefreshViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _hasMoreData;
    UITableView *_orderTableView;
    NSMutableArray *_listInfos;
    PARSMyOrdeInfo *_orderInfo;
    PARSResultView *_resultView;
    long long _pageNo;
    PARSResultView *_retryView;
    PARSViewLogicNotifyObserver *_errorsObserver;
    NSArray *_tempArr;
}

@property(retain, nonatomic) NSArray *tempArr; // @synthesize tempArr=_tempArr;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *errorsObserver; // @synthesize errorsObserver=_errorsObserver;
@property(retain, nonatomic) PARSResultView *retryView; // @synthesize retryView=_retryView;
@property(nonatomic) _Bool hasMoreData; // @synthesize hasMoreData=_hasMoreData;
@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
@property(retain, nonatomic) PARSResultView *resultView; // @synthesize resultView=_resultView;
@property(retain, nonatomic) PARSMyOrdeInfo *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(retain, nonatomic) NSMutableArray *listInfos; // @synthesize listInfos=_listInfos;
@property(retain, nonatomic) UITableView *orderTableView; // @synthesize orderTableView=_orderTableView;
- (void).cxx_destruct;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)didSelectResultView;
- (void)onLoadMore;
- (void)setupSubView;
- (void)onRefresh;
- (void)loadCache;
- (void)loadData;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

