//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewLogic.h"

@class NSArray, PARSViewLogicNotifyObserver;

@interface PARSMyInsuranceViewLogic : PARSBaseViewLogic
{
    _Bool _isLoading;
    _Bool _hasNext;
    PARSViewLogicNotifyObserver *_errorsObserver;
    PARSViewLogicNotifyObserver *_delegateObserver;
    NSArray *_datasources;
    long long _currentPage;
    long long _pageSize;
}

@property(nonatomic) long long pageSize; // @synthesize pageSize=_pageSize;
@property(nonatomic) _Bool hasNext; // @synthesize hasNext=_hasNext;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(retain, nonatomic) NSArray *datasources; // @synthesize datasources=_datasources;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *delegateObserver; // @synthesize delegateObserver=_delegateObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *errorsObserver; // @synthesize errorsObserver=_errorsObserver;
- (void).cxx_destruct;
- (void)requestInsuranceInfoList;
- (void)fetchInsuranceList;
- (id)init;

@end

