//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSMainAccountCardHandler, PARSMainAccountHandler, PARSMainAccountInfo, PARSMainAccountPayPasswordHandler, PARSMainAccountWCFundHandler, PARSMainAccountWCTransferHandler, PARSPaySignatureHandler;

@interface PARSMainAccountManager : NSObject
{
    PARSMainAccountInfo *_mainAccountInfo;
    PARSMainAccountHandler *_mainAccountHandler;
    PARSMainAccountCardHandler *_mainAccountCardHandler;
    PARSMainAccountWCTransferHandler *_wcTransferHandler;
    PARSMainAccountWCFundHandler *_wcFundHandler;
    PARSMainAccountPayPasswordHandler *_payPwdHandler;
    PARSPaySignatureHandler *_signatureHandler;
}

+ (id)sharedManager;
@property(retain, nonatomic) PARSPaySignatureHandler *signatureHandler; // @synthesize signatureHandler=_signatureHandler;
@property(retain, nonatomic) PARSMainAccountPayPasswordHandler *payPwdHandler; // @synthesize payPwdHandler=_payPwdHandler;
@property(retain, nonatomic) PARSMainAccountWCFundHandler *wcFundHandler; // @synthesize wcFundHandler=_wcFundHandler;
@property(retain, nonatomic) PARSMainAccountWCTransferHandler *wcTransferHandler; // @synthesize wcTransferHandler=_wcTransferHandler;
@property(retain, nonatomic) PARSMainAccountCardHandler *mainAccountCardHandler; // @synthesize mainAccountCardHandler=_mainAccountCardHandler;
@property(retain, nonatomic) PARSMainAccountHandler *mainAccountHandler; // @synthesize mainAccountHandler=_mainAccountHandler;
@property(retain, nonatomic) PARSMainAccountInfo *mainAccountInfo; // @synthesize mainAccountInfo=_mainAccountInfo;
- (void).cxx_destruct;
- (void)requestValidateMessageCode:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getPublicKeySignalWithPwd:(id)arg1;
- (void)subscriberWithSuccess:(_Bool)arg1 error:(id)arg2 subscriber:(id)arg3;
- (id)requestValidateFindPassword:(id)arg1;
- (id)requestValidateOldPassword:(id)arg1;
- (id)requestModifyPassword:(id)arg1;
- (id)requestResetPassword:(id)arg1;
- (void)requestWCYieldWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestWCIncomeWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestWangCaiPayWithOTPParam:(id)arg1 doneOpenMainAccount:(_Bool)arg2 needPolling:(_Bool)arg3 result:(CDUnknownBlockType)arg4;
- (void)requestWangCaiPayWithRequestParam:(id)arg1 needPolling:(_Bool)arg2 result:(CDUnknownBlockType)arg3;
- (void)requestWangCaiTransOutInfoWithResult:(CDUnknownBlockType)arg1;
- (void)requestWangCaiTransInInfoWithResult:(CDUnknownBlockType)arg1;
- (void)requestWangCaiTransferWithRequestParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestOTPMessageWithBankCardNo:(id)arg1 paymentAmount:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)requestPublicKeyInfo:(CDUnknownBlockType)arg1;
- (void)requestCoBrandCreditCardInfoWithResult:(CDUnknownBlockType)arg1;
- (void)requestChangeCardWithParam:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestApplyUnbindCardWithParam:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestUnbindCardWithCardNo:(id)arg1 payCmaPassWord:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestAddCardWithParam:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)requestQueryCardAndCheckupWithCardNo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestCardList:(CDUnknownBlockType)arg1;
- (void)requestMerchantAuthServiceInfoWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountVerifyPasswordWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountWCIncomeListWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountWCIncomeInfoWithRefresh:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountChengziUrl:(CDUnknownBlockType)arg1;
- (void)fetchMainAccountInfo:(CDUnknownBlockType)arg1;
- (void)requestMainAccountInfoWithNeedRefresh:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountInfo:(CDUnknownBlockType)arg1;
- (void)requestOpenMainAccountWithUserInfo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestOpenMainAccount:(CDUnknownBlockType)arg1;
- (void)requestMainAccountIsOpened:(CDUnknownBlockType)arg1;
- (void)requestMainAccountStatus:(CDUnknownBlockType)arg1;
- (void)updateMainAccountInfo;
- (_Bool)hasDoneOpenedMainAccount;
- (void)setUp;
- (void)dealloc;
- (id)init;

@end

