//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PARSFileUtil : NSObject
{
}

+ (id)sourceFilePath;
+ (_Bool)moveSourcePath:(id)arg1 toTargetPath:(id)arg2 andError:(id *)arg3;
+ (id)fetchFileWithDictionaryPath:(id)arg1;
+ (id)dictionaryPathForUpload;
+ (id)dictionaryPathForWriteData;
+ (id)dictionaryPathWithFile:(id)arg1;
+ (_Bool)removeFileWithFilePath:(id)arg1 andError:(id *)arg2;
+ (_Bool)fileIsExistAtPath:(id)arg1;

@end

