//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSString, PARSPopoverView, UITableView;

@interface PARSPopoverSegmentView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _filterSelected;
    id <PARSPopoverSegmentDataSource><PARSPopoverSegmentDelegate> _delegate;
    UITableView *_tableView;
    PARSPopoverView *_popoverView;
}

@property(retain, nonatomic) PARSPopoverView *popoverView; // @synthesize popoverView=_popoverView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <PARSPopoverSegmentDataSource><PARSPopoverSegmentDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool filterSelected; // @synthesize filterSelected=_filterSelected;
- (void).cxx_destruct;
- (_Bool)alwaysShowBelowPoint;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)handleSegmentSelectAction:(id)arg1;
- (id)buildSegmentItem;
- (void)buildSubviews;
- (void)willMoveToSuperview:(id)arg1;
- (void)dealloc;
- (id)currentSegmentItemAtIndex:(unsigned long long)arg1;
- (id)currentItemAtSegment:(unsigned long long)arg1;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

