//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "LoginMemberDelegate.h"
#import "PARSPolicyVerifyPhoneViewControllerDelegate.h"
#import "PARSPopoverSegmentDataSource.h"
#import "PARSPopoverSegmentDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"

@class NSString, PARSPolicyListBottomView, PARSPolicyListViewLogic, PARSPopoverSegmentView, UIButton, UICollectionView;

@interface PARSPolicyListViewController : PARSBaseRefreshViewController <UICollectionViewDelegate, UICollectionViewDataSource, LoginMemberDelegate, PARSPopoverSegmentDataSource, PARSPopoverSegmentDelegate, PARSPolicyVerifyPhoneViewControllerDelegate>
{
    PARSPolicyListViewLogic *_viewLogic;
    UICollectionView *_collectionView;
    PARSPolicyListBottomView *_bottomView;
    PARSPopoverSegmentView *_segmentView;
    UIButton *_switchButton;
    double _startYOffset;
}

@property(nonatomic) double startYOffset; // @synthesize startYOffset=_startYOffset;
@property(retain, nonatomic) UIButton *switchButton; // @synthesize switchButton=_switchButton;
@property(retain, nonatomic) PARSPopoverSegmentView *segmentView; // @synthesize segmentView=_segmentView;
@property(retain, nonatomic) PARSPolicyListBottomView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) PARSPolicyListViewLogic *viewLogic; // @synthesize viewLogic=_viewLogic;
- (void).cxx_destruct;
- (void)cancelVerifyPhoneFromType:(unsigned long long)arg1;
- (void)verifyPhoneSuccessWithCode:(id)arg1 type:(unsigned long long)arg2;
- (_Bool)isAppear;
- (void)popoverSegmentView:(id)arg1 didSelectAtIndexPath:(id)arg2;
- (id)popoverItemsAtSegmentIndex:(unsigned long long)arg1;
- (id)defaultTitleOfSegment:(unsigned long long)arg1;
- (unsigned long long)numberOfRowsInSegment:(long long)arg1;
- (unsigned long long)numberOfSegments;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundColorForViewAtSection:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)onRefresh;
- (void)logInYZTSucessfully;
- (void)didClickBottomEntrance;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)showEyeTipsMask;
- (void)showFakeFloatingHeader;
- (void)removeAllStatusSubviews;
- (id)getCurrentSortOptions;
- (void)presentYZTLoginViewController;
- (void)gotoAppLogin;
- (void)showEmptyView;
- (void)showErrorView;
- (void)showLoading;
- (void)showBottomView:(_Bool)arg1;
- (void)showMorePolicy;
- (void)showPolicyDetailWithInfo:(id)arg1;
- (void)loginTimeout;
- (void)delegateWithTuple:(id)arg1;
- (void)refreshSensitiveSwitchButton:(_Bool)arg1;
- (void)updateSensitiveSwitchStatus:(id)arg1;
- (void)buildSensitiveInfoSwitchIfNeed;
- (void)buildSubviews;
- (void)updateSubviewsWithType:(id)arg1;
- (void)reloadList;
- (void)gotoVerifyPhoneWithOtpType:(unsigned long long)arg1;
- (void)installBinder;
- (void)unBindLogic;
- (void)bindLogic;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

