//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@interface PARSMySettingAlertInfo : PARSBaseInfo
{
    _Bool _hasShow;
    id _alertView;
    long long _alertViewType;
}

@property(nonatomic) _Bool hasShow; // @synthesize hasShow=_hasShow;
@property(nonatomic) long long alertViewType; // @synthesize alertViewType=_alertViewType;
@property(retain, nonatomic) id alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;

@end

