//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "PARSLoadMoreAnimationViewProtocol.h"

@class CADisplayLink, CAShapeLayer, NSString, UILabel;

@interface PARSLoadMoreAnimationView : UIView <PARSLoadMoreAnimationViewProtocol>
{
    UILabel *_tipsLabel;
    CAShapeLayer *_leftLayer;
    CAShapeLayer *_middleLayer;
    CAShapeLayer *_rightLayer;
    double _leftLayerRadius;
    double _middleLayerRadius;
    double _rightLayerRadius;
    CADisplayLink *_leftLayerDisplayLink;
    CADisplayLink *_middleLayerDisplayLink;
    CADisplayLink *_rightLayerDisplayLink;
    double _leftLayerRadiusChange;
    double _middleLayerRadiusChange;
    double _rightLayerRadiusChange;
}

@property(nonatomic) double rightLayerRadiusChange; // @synthesize rightLayerRadiusChange=_rightLayerRadiusChange;
@property(nonatomic) double middleLayerRadiusChange; // @synthesize middleLayerRadiusChange=_middleLayerRadiusChange;
@property(nonatomic) double leftLayerRadiusChange; // @synthesize leftLayerRadiusChange=_leftLayerRadiusChange;
@property(retain, nonatomic) CADisplayLink *rightLayerDisplayLink; // @synthesize rightLayerDisplayLink=_rightLayerDisplayLink;
@property(retain, nonatomic) CADisplayLink *middleLayerDisplayLink; // @synthesize middleLayerDisplayLink=_middleLayerDisplayLink;
@property(retain, nonatomic) CADisplayLink *leftLayerDisplayLink; // @synthesize leftLayerDisplayLink=_leftLayerDisplayLink;
@property(nonatomic) double rightLayerRadius; // @synthesize rightLayerRadius=_rightLayerRadius;
@property(nonatomic) double middleLayerRadius; // @synthesize middleLayerRadius=_middleLayerRadius;
@property(nonatomic) double leftLayerRadius; // @synthesize leftLayerRadius=_leftLayerRadius;
@property(retain, nonatomic) CAShapeLayer *rightLayer; // @synthesize rightLayer=_rightLayer;
@property(retain, nonatomic) CAShapeLayer *middleLayer; // @synthesize middleLayer=_middleLayer;
@property(retain, nonatomic) CAShapeLayer *leftLayer; // @synthesize leftLayer=_leftLayer;
@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
- (void).cxx_destruct;
- (void)reset;
- (void)configNoMore;
- (void)stopAnimation;
- (void)animateRightLayer:(id)arg1;
- (void)startRightLayerAnimation;
- (void)animateMiddleLayer:(id)arg1;
- (void)startMiddleLayerAnimation;
- (void)animateLeftLayer:(id)arg1;
- (void)startLeftLayerAnimation;
- (void)startAnimation;
- (void)updateRightLayerShape;
- (void)updateMiddleLayerShape;
- (void)updateLeftLayerShape;
- (void)updateSubLayerShape;
- (void)loadMoreControl:(id)arg1 didChangeToState:(unsigned long long)arg2;
- (void)setFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

