//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "PARSWealthSearchInputViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PARSResultView, PARSWealthSearchInputView, UIButton, UITableView;

@interface PARSLifeAidSearchResultViewController : PARSBaseRefreshViewController <UITableViewDelegate, UITableViewDataSource, PARSWealthSearchInputViewDelegate>
{
    UITableView *_mainTableView;
    NSArray *_productList;
    NSString *_keyword;
    long long _currentPage;
    PARSResultView *_errorView;
    PARSResultView *_emptyView;
    UIButton *_topBtn;
    PARSWealthSearchInputView *_searchInputView;
}

@property(retain, nonatomic) PARSWealthSearchInputView *searchInputView; // @synthesize searchInputView=_searchInputView;
@property(retain, nonatomic) UIButton *topBtn; // @synthesize topBtn=_topBtn;
@property(retain, nonatomic) PARSResultView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) PARSResultView *errorView; // @synthesize errorView=_errorView;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(copy, nonatomic) NSString *keyword; // @synthesize keyword=_keyword;
@property(retain, nonatomic) NSArray *productList; // @synthesize productList=_productList;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
- (void).cxx_destruct;
- (void)searchInputView:(id)arg1 didTapCancelButton:(id)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)onLoadMore;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)reloadWithKeyword:(id)arg1;
- (CDUnknownBlockType)refresh;
- (void)handleTap;
- (void)pressTopBtn;
- (void)pressSearchBtn;
- (void)search;
- (void)goSearch;
- (void)layoutSubview;
- (void)popBack;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithKeyword:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

