//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

#import "PARSUploadRequest.h"

@class NSString, PARSUploadData;

@interface PARSUploadFileToProtalRequest : PARSProtalBaseUserHTTPRequest <PARSUploadRequest>
{
    PARSUploadData *_uploadData;
    NSString *_fileUrl;
    NSString *_oldFileUrl;
}

@property(retain, nonatomic) NSString *oldFileUrl; // @synthesize oldFileUrl=_oldFileUrl;
@property(retain, nonatomic) NSString *fileUrl; // @synthesize fileUrl=_fileUrl;
@property(copy, nonatomic) PARSUploadData *uploadData; // @synthesize uploadData=_uploadData;
- (void).cxx_destruct;
- (id)uploadMultiData;
- (void)handleResponseResult:(id)arg1;
- (_Bool)sessionTaskEnable;
- (id)httpMethod;
- (id)url;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

