//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldHTTPRequest.h"

@class NSString, PARSSendMessageInfo;

@interface PARSSendMessageReqeust : PARSOldHTTPRequest
{
    PARSSendMessageInfo *_messageInfo;
    NSString *_mobilePhone;
}

@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
@property(retain, nonatomic) PARSSendMessageInfo *messageInfo; // @synthesize messageInfo=_messageInfo;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

