//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldBaseUserHTTPRequest.h"

@class NSString;

@interface PARSReceivePrizeRequest : PARSOldBaseUserHTTPRequest
{
    NSString *_prizeId;
    NSString *_prizeType;
}

@property(copy, nonatomic) NSString *prizeType; // @synthesize prizeType=_prizeType;
@property(copy, nonatomic) NSString *prizeId; // @synthesize prizeId=_prizeId;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (_Bool)shouldEncryptPhoneWithTimstamp;
- (id)httpBody;
- (id)url;
- (id)initWithUserId:(id)arg1 prizeId:(id)arg2 prizeType:(id)arg3 completion:(CDUnknownBlockType)arg4;

@end

