//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol PARSHCConversationListViewPresenterDelegate <NSObject>
- (void)didSelectRowAtIndex:(long long)arg1 data:(id <PARSHCConversationBeanProtocol>)arg2;
- (_Bool)canEditRowAtIndex:(long long)arg1;
- (void)deleteConversationAtIndex:(long long)arg1;
@end

