//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "LoginMemberDelegate.h"
#import "PARSPolicyVerifyPhoneViewControllerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PARSPolicyCommonFooterView, UITableView, UIView;

@interface PARSPolicyAcceptableListViewController : PARSBaseRefreshViewController <UITableViewDelegate, UITableViewDataSource, LoginMemberDelegate, PARSPolicyVerifyPhoneViewControllerDelegate>
{
    _Bool _isSelectedRow;
    NSString *_businessType;
    NSArray *_policyList;
    UITableView *_tableView;
    UIView *_headerView;
    PARSPolicyCommonFooterView *_footerView;
    NSString *_otpMessage;
}

@property(copy, nonatomic) NSString *otpMessage; // @synthesize otpMessage=_otpMessage;
@property(retain, nonatomic) PARSPolicyCommonFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool isSelectedRow; // @synthesize isSelectedRow=_isSelectedRow;
@property(retain, nonatomic) NSArray *policyList; // @synthesize policyList=_policyList;
@property(retain, nonatomic) NSString *businessType; // @synthesize businessType=_businessType;
- (void).cxx_destruct;
- (void)gotoDispatch:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)cancelVerifyPhoneFromType:(unsigned long long)arg1;
- (void)verifyPhoneSuccessWithCode:(id)arg1 type:(unsigned long long)arg2;
- (void)gotoVerifyPhoneWithOtpType:(unsigned long long)arg1;
- (void)logInYZTSucessfully;
- (void)gotoAppLogin;
- (void)presentYZTLoginViewController;
- (void)loginTimeout;
- (void)removeAllStatusSubviews;
- (void)showUnexpectViewWithType:(unsigned long long)arg1;
- (void)updateWithPolicyList:(id)arg1;
- (void)refreshData;
- (void)loadData;
- (void)onRefresh;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithTitle:(id)arg1 businessType:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

