//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSMyInsuranceHandler;

@interface PARSMyInsuranceManager : NSObject
{
    PARSMyInsuranceHandler *_insuranceHandler;
}

+ (id)sharedManager;
@property(retain, nonatomic) PARSMyInsuranceHandler *insuranceHandler; // @synthesize insuranceHandler=_insuranceHandler;
- (void).cxx_destruct;
- (void)requestInsuranceWithPageNo:(long long)arg1 pageSize:(long long)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)fetchInsuranceListWithResultBlock:(CDUnknownBlockType)arg1;

@end

