//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class CLLocation, NSString;

@interface PARSPlacemark : PARSBaseInfo
{
    NSString *_country;
    NSString *_province;
    NSString *_city;
    NSString *_cityCode;
    NSString *_district;
    NSString *_street;
    NSString *_address;
    CLLocation *_location;
}

@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
@property(readonly, copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(readonly, copy, nonatomic) NSString *street; // @synthesize street=_street;
@property(readonly, copy, nonatomic) NSString *district; // @synthesize district=_district;
@property(readonly, copy, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(readonly, copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(readonly, copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(readonly, copy, nonatomic) NSString *country; // @synthesize country=_country;
- (void).cxx_destruct;
- (id)initWithCLPlacemark:(id)arg1;
- (id)initWithJson:(id)arg1;

@end

