//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSHealthCircleBaseRequest.h"

@class NSArray;

@interface PARSHealthCircleInformationRequest : PARSHealthCircleBaseRequest
{
    NSArray *_infoList;
}

@property(readonly, copy, nonatomic) NSArray *infoList; // @synthesize infoList=_infoList;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;
- (id)initWithUserId:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

