//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSMyPaidPolicyInfo : PARSBaseInfo
{
    NSString *_policyNo;
    NSString *_productName;
    NSString *_dispatchUrl;
}

@property(copy, nonatomic) NSString *dispatchUrl; // @synthesize dispatchUrl=_dispatchUrl;
@property(copy, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(copy, nonatomic) NSString *policyNo; // @synthesize policyNo=_policyNo;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

