//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "PARSHWKitsInfoTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSDictionary, NSString, PARSActivityDetailModel, UITableView, UIView;

@interface PARSHWKitsInfoViewController : PARSBaseRefreshViewController <UITableViewDelegate, UITableViewDataSource, PARSHWKitsInfoTableViewCellDelegate>
{
    PARSActivityDetailModel *_activity;
    NSDictionary *_kitsInfo;
    UITableView *_kitTab;
    NSArray *_kitDataSource;
    UIView *_footView;
}

@property(retain, nonatomic) UIView *footView; // @synthesize footView=_footView;
@property(retain, nonatomic) NSArray *kitDataSource; // @synthesize kitDataSource=_kitDataSource;
@property(retain, nonatomic) UITableView *kitTab; // @synthesize kitTab=_kitTab;
@property(retain, nonatomic) NSDictionary *kitsInfo; // @synthesize kitsInfo=_kitsInfo;
@property(retain, nonatomic) PARSActivityDetailModel *activity; // @synthesize activity=_activity;
- (void).cxx_destruct;
- (void)kitInfoClick:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)fetchKitsWithDict:(id)arg1;
- (void)setupSubviews;
- (void)buildFootSubviews;
- (void)dealloc;
- (id)initWithKitsInfo:(id)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

