//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSLoginRecordsInfo : PARSBaseInfo
{
    NSString *_loginTime;
    NSString *_loginDevice;
}

@property(copy, nonatomic) NSString *loginDevice; // @synthesize loginDevice=_loginDevice;
@property(copy, nonatomic) NSString *loginTime; // @synthesize loginTime=_loginTime;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

