//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSActivityCommentInfo : PARSBaseInfo
{
    NSString *_activityId;
    NSString *_city;
    NSString *_phoneNo;
    NSString *_parentCommentId;
    NSString *_parentNickName;
    NSString *_nickName;
    NSString *_comment;
    NSString *_imageUrl;
    NSString *_thumbnailUrl;
    NSString *_dogId;
    NSString *_from;
}

@property(copy, nonatomic) NSString *from; // @synthesize from=_from;
@property(copy, nonatomic) NSString *dogId; // @synthesize dogId=_dogId;
@property(copy, nonatomic) NSString *thumbnailUrl; // @synthesize thumbnailUrl=_thumbnailUrl;
@property(copy, nonatomic) NSString *imageUrl; // @synthesize imageUrl=_imageUrl;
@property(copy, nonatomic) NSString *comment; // @synthesize comment=_comment;
@property(copy, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(copy, nonatomic) NSString *parentNickName; // @synthesize parentNickName=_parentNickName;
@property(copy, nonatomic) NSString *parentCommentId; // @synthesize parentCommentId=_parentCommentId;
@property(copy, nonatomic) NSString *phoneNo; // @synthesize phoneNo=_phoneNo;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *activityId; // @synthesize activityId=_activityId;
- (void).cxx_destruct;

@end

