//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSHealthCircleBaseRequest.h"

@class NSArray, NSString;

@interface PARSHealthCircleWalkHistoryRequest : PARSHealthCircleBaseRequest
{
    _Bool _nextPage;
    NSString *_checkAll;
    NSArray *_records;
}

@property(nonatomic) _Bool nextPage; // @synthesize nextPage=_nextPage;
@property(copy, nonatomic) NSArray *records; // @synthesize records=_records;
@property(copy, nonatomic) NSString *checkAll; // @synthesize checkAll=_checkAll;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

