//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PARSMyRedPacketInfo, UIImageView, UILabel;

@interface PARSMyRedPacketHeadView : UIView
{
    PARSMyRedPacketInfo *_myRedPacketInfo;
    UIImageView *_headImageView;
    UILabel *_nameLabel;
    UILabel *_moneyLabel;
    UILabel *_countLabel;
    long long _type;
}

@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(retain, nonatomic) UILabel *moneyLabel; // @synthesize moneyLabel=_moneyLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) PARSMyRedPacketInfo *myRedPacketInfo; // @synthesize myRedPacketInfo=_myRedPacketInfo;
- (void).cxx_destruct;
- (_Bool)isNumOfString:(id)arg1;
- (id)editString:(id)arg1 font:(id)arg2 color:(id)arg3;
- (void)setConstraints;
- (void)initUI;
- (id)initWithFrame:(struct CGRect)arg1 myRedPacketInfo:(id)arg2 type:(long long)arg3;

@end

