//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@class PARSWealthHomeProductDataProvider;

@interface PARSWealthHomeProductHandler : PARSBaseUserHandler
{
    PARSWealthHomeProductDataProvider *_productDataProvider;
}

@property(retain, nonatomic) PARSWealthHomeProductDataProvider *productDataProvider; // @synthesize productDataProvider=_productDataProvider;
- (void).cxx_destruct;
- (void)requestWCTips:(CDUnknownBlockType)arg1;
- (void)fetchCachedProductWithType:(long long)arg1 pageNo:(long long)arg2 result:(CDUnknownBlockType)arg3;
- (void)requestProductWithType:(long long)arg1 pageNo:(long long)arg2 result:(CDUnknownBlockType)arg3;
- (void)fetchCachedRecommendProducts:(CDUnknownBlockType)arg1;
- (void)requestRecommendProducts:(CDUnknownBlockType)arg1;

@end

