//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@class PARSMessageListProvider, PARSMessageTypeListProvider;

@interface PARSMessageCenterHandler : PARSBaseUserHandler
{
    _Bool _newMessageNotiIsOpen;
    PARSMessageListProvider *_newsListProvider;
    PARSMessageTypeListProvider *_typeListProvider;
}

@property(retain, nonatomic) PARSMessageTypeListProvider *typeListProvider; // @synthesize typeListProvider=_typeListProvider;
@property(retain, nonatomic) PARSMessageListProvider *newsListProvider; // @synthesize newsListProvider=_newsListProvider;
@property(nonatomic) _Bool newMessageNotiIsOpen; // @synthesize newMessageNotiIsOpen=_newMessageNotiIsOpen;
- (void).cxx_destruct;
- (void)loadSetting;
- (void)deleteMsgList:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)updateMsgIsRead:(id)arg1;
- (_Bool)queryMsgIsRead:(id)arg1;
- (void)loadMoreMsgListWithMsgInfo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)refreshMsgListWithMsgTypeId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)fetchCachedMsgListWithMsgTypeId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (_Bool)updateMsgContentEmptyWithMessageStyle:(long long)arg1;
- (_Bool)updateMsgHasReadWithMessageStyle:(long long)arg1;
- (_Bool)queryNewMsgNotiState;
- (void)updateNewMsgNotiState:(id)arg1;
- (void)updateMessageTypeSwitchState:(id)arg1 messageStyle:(long long)arg2;
- (void)scheduleLoadNewMessage:(CDUnknownBlockType)arg1;
- (void)requestMessageListWithLocationCacheFlag:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)fetchCachedMessageListWithResult:(CDUnknownBlockType)arg1;
- (id)initWithUserId:(id)arg1 queue:(id)arg2;

@end

