//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSMineWangCaiView, UIButton, UILabel, UIView;

@interface PARSMineWangCaiCell : UITableViewCell
{
    _Bool _isRegistered;
    _Bool _isRisk;
    id <PARSWealthWangCaiCellDelegate> _delegate;
    UIView *_tipView;
    UILabel *_wangCaiLabel;
    UIView *_lineView;
    PARSMineWangCaiView *_wangCaiView;
    UIButton *_detailBtn;
    UIButton *_fansBtn;
    UIView *_containerView;
    UIButton *_riskButton;
}

@property(retain, nonatomic) UIButton *riskButton; // @synthesize riskButton=_riskButton;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *fansBtn; // @synthesize fansBtn=_fansBtn;
@property(retain, nonatomic) UIButton *detailBtn; // @synthesize detailBtn=_detailBtn;
@property(retain, nonatomic) PARSMineWangCaiView *wangCaiView; // @synthesize wangCaiView=_wangCaiView;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *wangCaiLabel; // @synthesize wangCaiLabel=_wangCaiLabel;
@property(retain, nonatomic) UIView *tipView; // @synthesize tipView=_tipView;
@property(nonatomic) _Bool isRisk; // @synthesize isRisk=_isRisk;
@property(nonatomic) _Bool isRegistered; // @synthesize isRegistered=_isRegistered;
@property(nonatomic) __weak id <PARSWealthWangCaiCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)startShake;
- (void)updateWithWangCaiBrefInfo:(id)arg1;
- (id)buttonWithImageName:(id)arg1 title:(id)arg2 action:(SEL)arg3;
- (void)didTapWangCaiView:(id)arg1;
- (void)tapFansBtn:(id)arg1;
- (void)tapDetailBtn:(id)arg1;
- (void)tapShakeBtn:(id)arg1;
- (void)tapWangCaiImage:(id)arg1;
- (void)clickRiskButton:(id)arg1;
- (void)dealloc;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

