//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSString;

@interface PARSConversationAnnouncementRequest : PARSProtalBaseUserHTTPRequest
{
    NSString *_mobilePhone;
    NSString *_groupId;
    NSString *_announcement;
}

@property(copy, nonatomic) NSString *announcement; // @synthesize announcement=_announcement;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

