//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PARSActivityDetailModel;

@interface PARSActivityDetailDispatchItem : NSObject
{
    unsigned long long _navigationType;
    PARSActivityDetailModel *_activityInfo;
    NSString *_QRCodeURLStr;
    NSString *_locationStr;
}

+ (id)dispatchItemWithNavigationType:(unsigned long long)arg1 activityInfo:(id)arg2;
+ (id)dispatchItemWithNavigationType:(unsigned long long)arg1;
@property(retain, nonatomic) NSString *locationStr; // @synthesize locationStr=_locationStr;
@property(retain, nonatomic) NSString *QRCodeURLStr; // @synthesize QRCodeURLStr=_QRCodeURLStr;
@property(retain, nonatomic) PARSActivityDetailModel *activityInfo; // @synthesize activityInfo=_activityInfo;
@property(nonatomic) unsigned long long navigationType; // @synthesize navigationType=_navigationType;
- (void).cxx_destruct;

@end

