//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PARSCloudUploadManager : NSObject
{
    NSString *_baseUrl;
    NSString *_token;
    NSString *_bucket;
    NSArray *_keys;
}

+ (id)sharedManager;
@property(retain, nonatomic) NSArray *keys; // @synthesize keys=_keys;
@property(copy, nonatomic) NSString *bucket; // @synthesize bucket=_bucket;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
@property(copy, nonatomic) NSString *baseUrl; // @synthesize baseUrl=_baseUrl;
- (void).cxx_destruct;
- (void)uploadToCloudWithUploadData:(id)arg1 uploadType:(long long)arg2 progressBlock:(CDUnknownBlockType)arg3 resultBlock:(CDUnknownBlockType)arg4;
- (void)requestTokenWithPSSUrl:(id)arg1 policyNo:(id)arg2 CompleteBlock:(CDUnknownBlockType)arg3;
- (void)uploadWithData:(id)arg1 pssUrl:(id)arg2 policyNo:(id)arg3 uploadType:(long long)arg4 progressBlock:(CDUnknownBlockType)arg5 resultBlock:(CDUnknownBlockType)arg6;

@end

