//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSDictionary, NSNumber, NSString, PARSMainAccountCardInfo;

@interface PARSMainAccountWCTransOutInfo : PARSBaseInfo
{
    _Bool _isDayLimit;
    NSNumber *_balance;
    NSString *_balanceStr;
    NSNumber *_dayLimitAmount;
    NSNumber *_alreadyTransOutAmount;
    NSString *_nomalArrivalTime;
    PARSMainAccountCardInfo *_cardInfo;
    NSDictionary *_ruleItems;
    NSString *_transationLimitUrl;
    NSString *_transOutRuleUrl;
}

@property(retain, nonatomic) NSString *transOutRuleUrl; // @synthesize transOutRuleUrl=_transOutRuleUrl;
@property(retain, nonatomic) NSString *transationLimitUrl; // @synthesize transationLimitUrl=_transationLimitUrl;
@property(retain, nonatomic) NSDictionary *ruleItems; // @synthesize ruleItems=_ruleItems;
@property(retain, nonatomic) PARSMainAccountCardInfo *cardInfo; // @synthesize cardInfo=_cardInfo;
@property(retain, nonatomic) NSString *nomalArrivalTime; // @synthesize nomalArrivalTime=_nomalArrivalTime;
@property(retain, nonatomic) NSNumber *alreadyTransOutAmount; // @synthesize alreadyTransOutAmount=_alreadyTransOutAmount;
@property(retain, nonatomic) NSNumber *dayLimitAmount; // @synthesize dayLimitAmount=_dayLimitAmount;
@property(retain, nonatomic) NSString *balanceStr; // @synthesize balanceStr=_balanceStr;
@property(retain, nonatomic) NSNumber *balance; // @synthesize balance=_balance;
@property(nonatomic) _Bool isDayLimit; // @synthesize isDayLimit=_isDayLimit;
- (void).cxx_destruct;
- (id)availableTransOutAmount;
- (id)initWithJson:(id)arg1;

@end

