//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSArray, NSString;

@interface PARSLiveAddressListRequest : PARSProtalBaseUserHTTPRequest
{
    NSString *_liveId;
    NSString *_groupId;
    NSArray *_members;
}

@property(copy, nonatomic) NSArray *members; // @synthesize members=_members;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
@property(copy, nonatomic) NSString *liveId; // @synthesize liveId=_liveId;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

