//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSYYBaseUserCacheProvider.h"

@interface PARSLiveBannerProvider : PARSYYBaseUserCacheProvider
{
}

- (void)deleteAllliveBannerInfos;
- (id)fetchliveBannerInfos;
- (void)cacheLiveBannerInfos:(id)arg1;
- (id)initWithUser:(id)arg1;

@end

