//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSSJYConfigInfo : PARSBaseInfo
{
    NSString *_scircleId;
    unsigned long long _msgMode;
}

@property(nonatomic) unsigned long long msgMode; // @synthesize msgMode=_msgMode;
@property(copy, nonatomic) NSString *scircleId; // @synthesize scircleId=_scircleId;
- (void).cxx_destruct;

@end

