//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface PARSDealSearchCell : UITableViewCell
{
    UILabel *_dateAndBusinessCodeLabel;
    UILabel *_fundNameAndCodeLabel;
    UILabel *_confirmAmountLabel;
    UILabel *_confirmPortionLabel;
}

@property(retain, nonatomic) UILabel *confirmPortionLabel; // @synthesize confirmPortionLabel=_confirmPortionLabel;
@property(retain, nonatomic) UILabel *confirmAmountLabel; // @synthesize confirmAmountLabel=_confirmAmountLabel;
@property(retain, nonatomic) UILabel *fundNameAndCodeLabel; // @synthesize fundNameAndCodeLabel=_fundNameAndCodeLabel;
@property(retain, nonatomic) UILabel *dateAndBusinessCodeLabel; // @synthesize dateAndBusinessCodeLabel=_dateAndBusinessCodeLabel;
- (void).cxx_destruct;
- (void)updateCellWithDealSearchInfo:(id)arg1;
- (struct UIEdgeInsets)layoutMargins;
- (struct UIEdgeInsets)separatorInset;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

