//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class PARSMainAccountInfo;

@interface PARSMainAccountQueryAccountInfoRequest : PARSProtalBaseUserHTTPRequest
{
    PARSMainAccountInfo *_accountInfo;
}

@property(retain, nonatomic) PARSMainAccountInfo *accountInfo; // @synthesize accountInfo=_accountInfo;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (_Bool)needMobilePhone;
- (_Bool)shouldEncryptPhoneWithTimstamp;
- (id)url;

@end

