//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSYZTUserInfo : PARSBaseInfo
{
    _Bool _isMale;
    NSString *_realName;
    NSString *_birthday;
}

@property(nonatomic) _Bool isMale; // @synthesize isMale=_isMale;
@property(copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(copy, nonatomic) NSString *realName; // @synthesize realName=_realName;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

