//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSYYBaseCacheProvider.h"

@interface PARSYYBaseCommonCacheProvider : PARSYYBaseCacheProvider
{
}

- (void)cacheAndRemoveTMCacheDataWithSourcePath:(id)arg1 sourceName:(id)arg2 value:(id)arg3 key:(id)arg4;
- (id)queryAndRemoveTMCacheDataWithSourcePath:(id)arg1 sourceName:(id)arg2 key:(id)arg3;
- (id)initWithName:(id)arg1;

@end

