//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserDatabaseProvider.h"

@interface PARSFakePedometerDataProvider : PARSBaseUserDatabaseProvider
{
}

- (_Bool)deletePedometersBeforeDate:(id)arg1;
- (_Bool)isPedometerUploaded:(id)arg1;
- (void)addUploadedFakePedometerList:(id)arg1;
- (_Bool)addUploadedFakePedometer:(id)arg1;
- (_Bool)onCreateTable:(id)arg1;
- (long long)version;
- (id)name;

@end

