//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, RACCommand, RACSignal, RACSubject;

@interface PARSWangCaiFindMyPayPasswordViewModel : NSObject
{
    _Bool _isBusy;
    _Bool _isFailed;
    _Bool _needChangeCard;
    RACCommand *_nextCommand;
    RACSubject *_errors;
    RACSignal *_canSendValidateSignal;
    RACSignal *_canExecuteNextCommandSignal;
    NSString *_userName;
    NSString *_idCardNo;
    NSString *_isChangeCard;
    NSString *_bankCardNo;
    NSString *_phoneNo;
    NSString *_validateCode;
    unsigned long long _failCount;
    unsigned long long _cacleFaiCount;
    NSString *_lastCardNo;
}

@property(retain, nonatomic) NSString *lastCardNo; // @synthesize lastCardNo=_lastCardNo;
@property(nonatomic) _Bool needChangeCard; // @synthesize needChangeCard=_needChangeCard;
@property(nonatomic) _Bool isFailed; // @synthesize isFailed=_isFailed;
@property(nonatomic) unsigned long long cacleFaiCount; // @synthesize cacleFaiCount=_cacleFaiCount;
@property(nonatomic) unsigned long long failCount; // @synthesize failCount=_failCount;
@property(nonatomic) _Bool isBusy; // @synthesize isBusy=_isBusy;
@property(copy, nonatomic) NSString *validateCode; // @synthesize validateCode=_validateCode;
@property(copy, nonatomic) NSString *phoneNo; // @synthesize phoneNo=_phoneNo;
@property(copy, nonatomic) NSString *bankCardNo; // @synthesize bankCardNo=_bankCardNo;
@property(copy, nonatomic) NSString *isChangeCard; // @synthesize isChangeCard=_isChangeCard;
@property(copy, nonatomic) NSString *idCardNo; // @synthesize idCardNo=_idCardNo;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(readonly, nonatomic) RACSignal *canExecuteNextCommandSignal; // @synthesize canExecuteNextCommandSignal=_canExecuteNextCommandSignal;
@property(readonly, nonatomic) RACSignal *canSendValidateSignal; // @synthesize canSendValidateSignal=_canSendValidateSignal;
- (void).cxx_destruct;
- (void)resetPhoneAndBankCardNo;
@property(readonly, nonatomic) RACSubject *errors; // @synthesize errors=_errors;
@property(readonly, nonatomic) RACCommand *nextCommand; // @synthesize nextCommand=_nextCommand;
- (id)init;

@end

