//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSClickPraiseParmInfo : PARSBaseInfo
{
    NSString *_commentId;
    NSString *_dogeId;
    NSString *_phoneNo;
}

@property(retain, nonatomic) NSString *phoneNo; // @synthesize phoneNo=_phoneNo;
@property(retain, nonatomic) NSString *dogeId; // @synthesize dogeId=_dogeId;
@property(retain, nonatomic) NSString *commentId; // @synthesize commentId=_commentId;
- (void).cxx_destruct;

@end

