//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldHTTPRequest.h"

@class NSString, PARSSignAccountStatusInfo;

@interface PARSCheckSignAccountRequest : PARSOldHTTPRequest
{
    NSString *_mobilePhone;
    PARSSignAccountStatusInfo *_statusInfo;
}

@property(retain, nonatomic) PARSSignAccountStatusInfo *statusInfo; // @synthesize statusInfo=_statusInfo;
@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;
- (id)initWithMobilePhone:(id)arg1 completion:(CDUnknownBlockType)arg2;

@end

