//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

@class NSArray, PARSPSManagerViewLogic, UITableView;

@interface PARSPSManagerViewController : PARSBaseViewController
{
    UITableView *_tableView;
    PARSPSManagerViewLogic *_viewLogic;
    NSArray *_models;
}

@property(retain, nonatomic) NSArray *models; // @synthesize models=_models;
@property(retain, nonatomic) PARSPSManagerViewLogic *viewLogic; // @synthesize viewLogic=_viewLogic;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (_Bool)shouldHideNavigationBar;
- (void)dealloc;
- (void)unBindLogic;
- (void)bindLogic;
- (void)selectActionWithTuple:(id)arg1;
- (void)updateDelegateWithTuple:(id)arg1;
- (void)handleTapOnLogoutWangCaiAccount;
- (void)handleTapGestureOnGetBackPassView;
- (void)handleTapGestureOnModifyPassView;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)viewDidLoad;

@end

