//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSQiniuInfo : PARSBaseInfo
{
    NSString *_token;
    NSString *_expiredDate;
    long long _timeout;
    long long _serviceTime;
    NSString *_qnDomain;
    NSString *_cdnDomain;
}

@property(copy, nonatomic) NSString *cdnDomain; // @synthesize cdnDomain=_cdnDomain;
@property(copy, nonatomic) NSString *qnDomain; // @synthesize qnDomain=_qnDomain;
@property(nonatomic) long long serviceTime; // @synthesize serviceTime=_serviceTime;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(copy, nonatomic) NSString *expiredDate; // @synthesize expiredDate=_expiredDate;
@property(copy, nonatomic) NSString *token; // @synthesize token=_token;
- (void).cxx_destruct;

@end

