//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSResult.h"

@class NSArray;

@interface PARSListResult : PARSResult
{
    _Bool _nextFlag;
    NSArray *_list;
    long long _page;
    long long _totalPage;
    long long _pageNo;
}

@property(nonatomic) long long pageNo; // @synthesize pageNo=_pageNo;
@property(nonatomic) _Bool nextFlag; // @synthesize nextFlag=_nextFlag;
@property(nonatomic) long long totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) long long page; // @synthesize page=_page;
@property(copy, nonatomic) NSArray *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (id)description;

@end

