//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSMainAccountPayResult : PARSBaseInfo
{
    _Bool _needQuery;
    long long _status;
    NSString *_prepayId;
    NSString *_msg;
    NSString *_transationNo;
}

@property(nonatomic) _Bool needQuery; // @synthesize needQuery=_needQuery;
@property(retain, nonatomic) NSString *transationNo; // @synthesize transationNo=_transationNo;
@property(retain, nonatomic) NSString *msg; // @synthesize msg=_msg;
@property(retain, nonatomic) NSString *prepayId; // @synthesize prepayId=_prepayId;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

