//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSDictionary, NSString;

@interface PARSFundListResult : PARSBaseInfo
{
    NSDictionary *_typeFunds;
    NSString *_lowRiskText;
    NSString *_lowRiskDetailText;
    NSString *_highRiskText;
    NSString *_highRiskDetailText;
    NSString *_userRiskLevel;
}

@property(retain, nonatomic) NSString *userRiskLevel; // @synthesize userRiskLevel=_userRiskLevel;
@property(retain, nonatomic) NSString *highRiskDetailText; // @synthesize highRiskDetailText=_highRiskDetailText;
@property(retain, nonatomic) NSString *highRiskText; // @synthesize highRiskText=_highRiskText;
@property(retain, nonatomic) NSString *lowRiskDetailText; // @synthesize lowRiskDetailText=_lowRiskDetailText;
@property(retain, nonatomic) NSString *lowRiskText; // @synthesize lowRiskText=_lowRiskText;
@property(retain, nonatomic) NSDictionary *typeFunds; // @synthesize typeFunds=_typeFunds;
- (void).cxx_destruct;

@end

