//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PARSHealthBodyInfo, PARSHealthWalkPickerView, UILabel, UITableView;

@interface PARSHealthWalkConfigView : UIView <UITableViewDelegate, UITableViewDataSource>
{
    CDUnknownBlockType _handler;
    UIView *_bgView;
    UILabel *_titleLabel;
    UITableView *_tableView;
    PARSHealthWalkPickerView *_pickerView;
    PARSHealthBodyInfo *_bodyInfo;
    NSString *_title;
    NSArray *_sexArr;
    NSArray *_heightArr;
    NSArray *_weightArr;
    unsigned long long _type;
}

+ (id)showConfigWithTitle:(id)arg1 bodyInfo:(id)arg2 handler:(CDUnknownBlockType)arg3;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSArray *weightArr; // @synthesize weightArr=_weightArr;
@property(copy, nonatomic) NSArray *heightArr; // @synthesize heightArr=_heightArr;
@property(copy, nonatomic) NSArray *sexArr; // @synthesize sexArr=_sexArr;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) PARSHealthBodyInfo *bodyInfo; // @synthesize bodyInfo=_bodyInfo;
@property(retain, nonatomic) PARSHealthWalkPickerView *pickerView; // @synthesize pickerView=_pickerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (void)tapAction:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)preSelecteRow:(id)arg1 type:(unsigned long long)arg2;
- (void)showBodyInfoConfig:(id)arg1 type:(unsigned long long)arg2;
- (void)smallScreenAnimation:(double)arg1;
- (void)fetchConfigData;
- (void)show;
- (void)setupSubviews;
- (id)init;
- (id)initWithTitle:(id)arg1 bodyInfo:(id)arg2 handler:(CDUnknownBlockType)arg3;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

