//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

@class PARSModifyNicknameViewLogic, UIButton, UITextField, UIView;

@interface PARSModifyNicknameViewController : PARSBaseViewController
{
    PARSModifyNicknameViewLogic *_viewLogic;
    UIView *_mainView;
    UIButton *_rightButton;
    UITextField *_nicknameTextField;
}

@property(retain, nonatomic) UITextField *nicknameTextField; // @synthesize nicknameTextField=_nicknameTextField;
@property(retain, nonatomic) UIButton *rightButton; // @synthesize rightButton=_rightButton;
@property(retain, nonatomic) UIView *mainView; // @synthesize mainView=_mainView;
@property(retain, nonatomic) PARSModifyNicknameViewLogic *viewLogic; // @synthesize viewLogic=_viewLogic;
- (void).cxx_destruct;
- (void)dealloc;
- (void)unBindLogic;
- (void)bindLogic;
- (void)loadObserverAction:(id)arg1;
- (void)errorObserverAction:(id)arg1;
- (void)delegateWithTuple:(id)arg1;
- (void)back;
- (void)uploadNickname;
- (void)rightBtnAction;
- (void)backgroundViewTap;
- (void)updateNickname;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)setupConfirmButton;
- (void)setupConstraints;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

