//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSPolicyRuleCheck4DetailRequestResult : PARSBaseInfo
{
    _Bool _passed;
    NSString *_tipsMsg;
    NSString *_resultMsg;
}

+ (_Bool)checkPassedByAction:(id)arg1;
@property(retain, nonatomic) NSString *resultMsg; // @synthesize resultMsg=_resultMsg;
@property(nonatomic) _Bool passed; // @synthesize passed=_passed;
@property(readonly, nonatomic) NSString *tipsMsg; // @synthesize tipsMsg=_tipsMsg;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

