//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserDatabaseProvider.h"

@interface PARSBRoadcastLiveProvider : PARSBaseUserDatabaseProvider
{
}

- (id)querryBroadcastLiveInfoWithIsBanner:(_Bool)arg1;
- (_Bool)removeBroadcastLiveInfo;
- (_Bool)saveBroadcastLiveInfoWith:(id)arg1;
- (id)buildLiveModelWithResult:(id)arg1;
- (_Bool)onCreateTable:(id)arg1;
- (_Bool)onUpgradeTable:(id)arg1 fromVersion:(long long)arg2 toVersion:(long long)arg3;
- (long long)version;
- (id)name;

@end

