//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURLProtocol.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"
#import "NSURLSessionDataDelegate.h"
#import "NSURLSessionDelegate.h"
#import "PARSPrURLProtocolProtocol.h"

@class NSMutableData, NSString, NSURLSessionDataTask, PARSPrNetworkInfo;

@interface PARSPrURLProtocol : NSURLProtocol <NSURLConnectionDelegate, NSURLConnectionDataDelegate, NSURLSessionDelegate, NSURLSessionDataDelegate, PARSPrURLProtocolProtocol>
{
    NSURLSessionDataTask *_sessionTask;
    double _startTime;
    double _dataStartTime;
    PARSPrNetworkInfo *_networkInfo;
    NSMutableData *_responseData;
}

+ (_Bool)requestIsCacheEquivalent:(id)arg1 toRequest:(id)arg2;
+ (id)canonicalRequestForRequest:(id)arg1;
+ (_Bool)canInitWithRequest:(id)arg1;
@property(retain, nonatomic) NSMutableData *responseData; // @synthesize responseData=_responseData;
@property(retain, nonatomic) PARSPrNetworkInfo *networkInfo; // @synthesize networkInfo=_networkInfo;
@property(nonatomic) double dataStartTime; // @synthesize dataStartTime=_dataStartTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSURLSessionDataTask *sessionTask; // @synthesize sessionTask=_sessionTask;
- (void).cxx_destruct;
- (id)taidFromRequest;
- (id)businesssCodeFromResponse;
- (void)requestDidSuccess;
- (void)requestDidFailWithError:(id)arg1;
- (void)URLSession:(id)arg1 task:(id)arg2 didCompleteWithError:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveData:(id)arg3;
- (void)URLSession:(id)arg1 dataTask:(id)arg2 didReceiveResponse:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)stopLoading;
- (void)startLoading;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

