//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSHealthCircleBaseRequest.h"

@class NSArray, PARSHealthBehaviorIndexOtherInfo;

@interface PARSHealthBehaviorIndexRequest : PARSHealthCircleBaseRequest
{
    NSArray *_healthBehaviorIndexList;
    PARSHealthBehaviorIndexOtherInfo *_otherInfo;
}

@property(retain, nonatomic) PARSHealthBehaviorIndexOtherInfo *otherInfo; // @synthesize otherInfo=_otherInfo;
@property(copy, nonatomic) NSArray *healthBehaviorIndexList; // @synthesize healthBehaviorIndexList=_healthBehaviorIndexList;
- (void).cxx_destruct;
- (id)parseListWithData:(id)arg1;
- (void)handleResponseResult:(id)arg1;
- (id)url;

@end

