//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSDictionary, PARSCouponViewLogic, PARSResultView, UIButton, UITableView;

@interface PARSCouponConfirmView : UIView
{
    PARSCouponViewLogic *_viewLogic;
    CDUnknownBlockType _confirmBlock;
    NSArray *_originalCouponList;
    UIView *_parentView;
    UITableView *_mainTableView;
    NSDictionary *_paramDict;
    PARSResultView *_errorView;
    UIView *_footerView;
    UIButton *_confirmBtn;
    UIButton *_explainBtn;
    NSArray *_couponList;
    NSArray *_selectedCouponList;
    NSArray *_selectedIndexPaths;
}

@property(retain, nonatomic) NSArray *selectedIndexPaths; // @synthesize selectedIndexPaths=_selectedIndexPaths;
@property(retain, nonatomic) NSArray *selectedCouponList; // @synthesize selectedCouponList=_selectedCouponList;
@property(retain, nonatomic) NSArray *couponList; // @synthesize couponList=_couponList;
@property(retain, nonatomic) UIButton *explainBtn; // @synthesize explainBtn=_explainBtn;
@property(retain, nonatomic) UIButton *confirmBtn; // @synthesize confirmBtn=_confirmBtn;
@property(retain, nonatomic) UIView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) PARSResultView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) NSDictionary *paramDict; // @synthesize paramDict=_paramDict;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView=_parentView;
@property(copy, nonatomic) NSArray *originalCouponList; // @synthesize originalCouponList=_originalCouponList;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
@property(retain, nonatomic) PARSCouponViewLogic *viewLogic; // @synthesize viewLogic=_viewLogic;
- (void).cxx_destruct;
- (id)viewController;
- (void)layoutRightNavigationBtn;
- (void)layoutSubview;
- (void)showInView:(id)arg1;
- (id)initWithDict:(id)arg1;
- (void)dealloc;
- (void)showExplain:(id)arg1;
- (void)pressConfirmBtn:(id)arg1;
- (void)handleTap;
- (void)cell:(id)arg1 indexPath:(id)arg2 didPressIndicator:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)fetchCoupons;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)addObservers;
- (void)unBindLogic;
- (void)bindLogic;

@end

