//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSMainAccountAddCardRequestParam : PARSBaseInfo
{
    NSString *_cardNo;
    NSString *_mobile;
    NSString *_otpPhoneCode;
}

@property(retain, nonatomic) NSString *otpPhoneCode; // @synthesize otpPhoneCode=_otpPhoneCode;
@property(retain, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(retain, nonatomic) NSString *cardNo; // @synthesize cardNo=_cardNo;
- (void).cxx_destruct;

@end

