//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class PARSWangCaiTradePage, PARSWangCaiTradePageViewModel;

@interface PARSWangCaiTradeController : UIViewController
{
    PARSWangCaiTradePage *_pageView;
    PARSWangCaiTradePageViewModel *_viewModel;
}

@property(retain, nonatomic) PARSWangCaiTradePageViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) PARSWangCaiTradePage *pageView; // @synthesize pageView=_pageView;
- (void).cxx_destruct;
- (void)didTapRightButtonItem:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithTradeOutInfo:(id)arg1;
- (id)initWithTradeInInfo:(id)arg1;
- (id)initWithTradeType:(unsigned long long)arg1;
- (void)dealloc;

@end

