//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol PARSHealthCircleTrackPanel <NSObject>
- (void)panelPerformAction:(unsigned long long)arg1;
- (_Bool)panelShouldPerformAction:(unsigned long long)arg1;
- (void)panelEndScale;
- (void)panelScaling:(double)arg1;
@end

