//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString, PARSMyHealthPageInfo, PARSResultView, PARSZoneConfigInfo, UITableView;

@interface PARSMyHealthViewController : PARSBaseRefreshViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _needUpdateHealthInfoWhenAppear;
    UITableView *_tableView;
    PARSResultView *_errorResultView;
    PARSZoneConfigInfo *_myHealthZoneInfo;
    PARSMyHealthPageInfo *_myHealthInfo;
    long long _todayStepCount;
    NSMutableArray *_zoneItemList;
}

@property(nonatomic) _Bool needUpdateHealthInfoWhenAppear; // @synthesize needUpdateHealthInfoWhenAppear=_needUpdateHealthInfoWhenAppear;
@property(retain, nonatomic) NSMutableArray *zoneItemList; // @synthesize zoneItemList=_zoneItemList;
@property(nonatomic) long long todayStepCount; // @synthesize todayStepCount=_todayStepCount;
@property(retain, nonatomic) PARSMyHealthPageInfo *myHealthInfo; // @synthesize myHealthInfo=_myHealthInfo;
@property(retain, nonatomic) PARSZoneConfigInfo *myHealthZoneInfo; // @synthesize myHealthZoneInfo=_myHealthZoneInfo;
@property(retain, nonatomic) PARSResultView *errorResultView; // @synthesize errorResultView=_errorResultView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)refreshUI;
- (void)updateZoneItemList;
- (void)hideErrorView;
- (void)showErrorView;
- (void)loadStepCount;
- (void)loadDataWithRefresh:(_Bool)arg1 showLoading:(_Bool)arg2;
- (void)onRefresh;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

