//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewLogic.h"

#import "UIAlertViewDelegate.h"

@class NSArray, NSString, PARSFeedbackContentInfo, PARSFeedbackProblemInfo, PARSViewLogicNotifyObserver, UIAlertView;

@interface PARSFeedbackDetailViewLogic : PARSBaseViewLogic <UIAlertViewDelegate>
{
    _Bool _showTips;
    _Bool _needUploadLog;
    NSString *_feedbackContent;
    NSString *_locateInfo;
    NSString *_locateProvince;
    NSString *_locateCity;
    NSArray *_pictures;
    PARSFeedbackProblemInfo *_proplemInfo;
    NSArray *_detailItems;
    PARSViewLogicNotifyObserver *_errorsObserver;
    PARSViewLogicNotifyObserver *_uploadCompleteObserver;
    PARSViewLogicNotifyObserver *_cancelUploadObserver;
    PARSFeedbackContentInfo *_contentInfo;
    long long _pictureIndex;
    long long _retryCount;
    NSString *_reportId;
    UIAlertView *_alertView;
}

+ (id)sharedDetailViewLogic;
@property(retain, nonatomic) UIAlertView *alertView; // @synthesize alertView=_alertView;
@property(retain, nonatomic) NSString *reportId; // @synthesize reportId=_reportId;
@property(nonatomic) long long retryCount; // @synthesize retryCount=_retryCount;
@property(nonatomic) long long pictureIndex; // @synthesize pictureIndex=_pictureIndex;
@property(retain, nonatomic) PARSFeedbackContentInfo *contentInfo; // @synthesize contentInfo=_contentInfo;
@property(nonatomic) _Bool needUploadLog; // @synthesize needUploadLog=_needUploadLog;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *cancelUploadObserver; // @synthesize cancelUploadObserver=_cancelUploadObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *uploadCompleteObserver; // @synthesize uploadCompleteObserver=_uploadCompleteObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *errorsObserver; // @synthesize errorsObserver=_errorsObserver;
@property(nonatomic) _Bool showTips; // @synthesize showTips=_showTips;
@property(retain, nonatomic) NSArray *detailItems; // @synthesize detailItems=_detailItems;
@property(retain, nonatomic) PARSFeedbackProblemInfo *proplemInfo; // @synthesize proplemInfo=_proplemInfo;
@property(retain, nonatomic) NSArray *pictures; // @synthesize pictures=_pictures;
@property(retain, nonatomic) NSString *locateCity; // @synthesize locateCity=_locateCity;
@property(retain, nonatomic) NSString *locateProvince; // @synthesize locateProvince=_locateProvince;
@property(retain, nonatomic) NSString *locateInfo; // @synthesize locateInfo=_locateInfo;
@property(retain, nonatomic) NSString *feedbackContent; // @synthesize feedbackContent=_feedbackContent;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)commitActionWithNeedUploadLogFile:(_Bool)arg1;
- (void)sendPicture;
- (void)postErrorNotify;
- (void)postNotify;
- (void)uploadFeedback;
- (void)uploadLog;
- (void)deleteOldFile;
- (void)createZipWithFileName:(id)arg1;
- (_Bool)createDirectoryAtPath:(id)arg1;
- (id)defaultUploadPath;
- (id)defaultDirectory;
- (id)compressImage:(id)arg1 toMaxFileSize:(long long)arg2 index:(long long)arg3;
- (id)checkFeedbackIsValid;
- (id)nowDateStr;
- (void)updateProblemInfoWithValue:(id)arg1 atIndex:(long long)arg2;
- (void)initDataWithProblemInfo:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

