//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSWealthProductInfo : PARSBaseInfo
{
    NSString *_productCode;
    NSString *_name;
    NSString *_imgUrl;
    NSString *_imgPath;
}

@property(copy, nonatomic) NSString *imgPath; // @synthesize imgPath=_imgPath;
@property(readonly, copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *productCode; // @synthesize productCode=_productCode;
- (void).cxx_destruct;
- (id)initWithActivityJson:(id)arg1;
- (id)initWithJson:(id)arg1;

@end

