//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSPublicProductInfo, UILabel, UIView;

@interface PARSMyProductLiCaiPublicCell : UITableViewCell
{
    UIView *_liCaiPublicTitleView;
    UIView *_liCaiPublicContentView;
    UILabel *_liCaiPublicTitleLabel;
    PARSPublicProductInfo *_productInfo;
}

@property(retain, nonatomic) PARSPublicProductInfo *productInfo; // @synthesize productInfo=_productInfo;
@property(retain, nonatomic) UILabel *liCaiPublicTitleLabel; // @synthesize liCaiPublicTitleLabel=_liCaiPublicTitleLabel;
@property(retain, nonatomic) UIView *liCaiPublicContentView; // @synthesize liCaiPublicContentView=_liCaiPublicContentView;
@property(retain, nonatomic) UIView *liCaiPublicTitleView; // @synthesize liCaiPublicTitleView=_liCaiPublicTitleView;
- (void).cxx_destruct;
- (void)updateCellWithProductInfo:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

