//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSAddressInfo : PARSBaseInfo
{
    _Bool _isChoose;
    _Bool _isDefault;
    NSString *_addressId;
    NSString *_userName;
    NSString *_phoneNo;
    NSString *_postcode;
    NSString *_province;
    NSString *_provinceCode;
    NSString *_city;
    NSString *_cityCode;
    NSString *_area;
    NSString *_areaCode;
    NSString *_address;
}

@property(nonatomic) _Bool isDefault; // @synthesize isDefault=_isDefault;
@property(nonatomic) _Bool isChoose; // @synthesize isChoose=_isChoose;
@property(copy, nonatomic) NSString *address; // @synthesize address=_address;
@property(copy, nonatomic) NSString *areaCode; // @synthesize areaCode=_areaCode;
@property(copy, nonatomic) NSString *area; // @synthesize area=_area;
@property(copy, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(copy, nonatomic) NSString *city; // @synthesize city=_city;
@property(copy, nonatomic) NSString *provinceCode; // @synthesize provinceCode=_provinceCode;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *postcode; // @synthesize postcode=_postcode;
@property(copy, nonatomic) NSString *phoneNo; // @synthesize phoneNo=_phoneNo;
@property(copy, nonatomic) NSString *userName; // @synthesize userName=_userName;
@property(copy, nonatomic) NSString *addressId; // @synthesize addressId=_addressId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)formatAddressInfo;
- (id)toDictionary;
- (id)initWithJson:(id)arg1;

@end

