//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSMayFairHandler;

@interface PARSMayFairManager : NSObject
{
    PARSMayFairHandler *_mayFairHandler;
}

+ (id)shareManager;
@property(retain, nonatomic) PARSMayFairHandler *mayFairHandler; // @synthesize mayFairHandler=_mayFairHandler;
- (void).cxx_destruct;
- (void)requestPushAgentWithResult:(CDUnknownBlockType)arg1;

@end

