//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSDictionary;

@interface PARSGetRealInfoRequest : PARSProtalBaseUserHTTPRequest
{
    NSDictionary *_result;
}

@property(copy, nonatomic) NSDictionary *result; // @synthesize result=_result;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;
- (_Bool)shouldEncryptPhoneWithTimstamp;

@end

