//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PARSExpressInputView, UIButton;

@protocol PARSExpressInputViewDelegate <NSObject>

@optional
- (void)expressInputView:(PARSExpressInputView *)arg1 didClickRightBtn:(UIButton *)arg2;
- (void)expressInputView:(PARSExpressInputView *)arg1 didSelect:(NSString *)arg2;
@end

