//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PARSLaunchProtocol.h"

@class NSObject<OS_dispatch_queue>, NSString, PARSARUserHandler, PARSBaseSignHandler, PARSGestureLockInfo, PARSLogInHandler, PARSLogoutHandler, PARSPasswordHandler, PARSRegisterVerifyCodeInfo, PARSSignUpHandler, PARSUserInfo, PARSUserInfoHandler, PARSYZTLogInHandler;

@interface PARSUserManager : NSObject <PARSLaunchProtocol>
{
    NSString *_registerToken;
    NSString *_inputVerifyCode;
    NSString *_verifyCodeKey;
    NSString *_codeForIdentifyVerifyCode;
    NSString *_isVerifyMoMsgCode;
    PARSRegisterVerifyCodeInfo *_imageVerifyCodeInfo;
    PARSLogInHandler *_logInHandler;
    PARSYZTLogInHandler *_yztLogInHandler;
    PARSSignUpHandler *_signUpHandler;
    PARSBaseSignHandler *_commonSignHandler;
    PARSUserInfoHandler *_userInfoHandler;
    PARSPasswordHandler *_passwordHandler;
    PARSARUserHandler *_arUserHandler;
    PARSLogoutHandler *_logoutHandler;
    NSObject<OS_dispatch_queue> *_userQueue;
    NSString *_magicStr;
    NSString *_mobilePhone;
}

+ (id)sharedManager;
@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
@property(copy, nonatomic) NSString *magicStr; // @synthesize magicStr=_magicStr;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *userQueue; // @synthesize userQueue=_userQueue;
@property(retain, nonatomic) PARSLogoutHandler *logoutHandler; // @synthesize logoutHandler=_logoutHandler;
@property(retain, nonatomic) PARSARUserHandler *arUserHandler; // @synthesize arUserHandler=_arUserHandler;
@property(retain, nonatomic) PARSPasswordHandler *passwordHandler; // @synthesize passwordHandler=_passwordHandler;
@property(retain, nonatomic) PARSUserInfoHandler *userInfoHandler; // @synthesize userInfoHandler=_userInfoHandler;
@property(retain, nonatomic) PARSBaseSignHandler *commonSignHandler; // @synthesize commonSignHandler=_commonSignHandler;
@property(retain, nonatomic) PARSSignUpHandler *signUpHandler; // @synthesize signUpHandler=_signUpHandler;
@property(retain, nonatomic) PARSYZTLogInHandler *yztLogInHandler; // @synthesize yztLogInHandler=_yztLogInHandler;
@property(retain, nonatomic) PARSLogInHandler *logInHandler; // @synthesize logInHandler=_logInHandler;
@property(retain, nonatomic) PARSRegisterVerifyCodeInfo *imageVerifyCodeInfo; // @synthesize imageVerifyCodeInfo=_imageVerifyCodeInfo;
@property(copy, nonatomic) NSString *isVerifyMoMsgCode; // @synthesize isVerifyMoMsgCode=_isVerifyMoMsgCode;
@property(copy, nonatomic) NSString *codeForIdentifyVerifyCode; // @synthesize codeForIdentifyVerifyCode=_codeForIdentifyVerifyCode;
@property(copy, nonatomic) NSString *verifyCodeKey; // @synthesize verifyCodeKey=_verifyCodeKey;
@property(copy, nonatomic) NSString *inputVerifyCode; // @synthesize inputVerifyCode=_inputVerifyCode;
@property(copy, nonatomic) NSString *registerToken; // @synthesize registerToken=_registerToken;
- (void).cxx_destruct;
- (void)doExit;
- (void)logoutAppRequestWithResultBlock:(CDUnknownBlockType)arg1;
- (void)logoutYZTRequestWithResultBlock:(CDUnknownBlockType)arg1;
- (void)checkLoginRequestWithResultBlock:(CDUnknownBlockType)arg1;
- (void)fetchUserPolicyInfoWithResult:(CDUnknownBlockType)arg1;
- (void)findPasswordWithPhoneNo:(id)arg1 andPassword:(id)arg2 andOtpCode:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)verifyWithPhoneNo:(id)arg1 andUsername:(id)arg2 andIdNo:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)checkIsAlreadyRegisterWithPhoneNo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestRealInfoWithCompletion:(CDUnknownBlockType)arg1;
- (void)changeUserAvatarWithHash:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)changeUserAvatarWithImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)changeUserAvatarWithPresetAvatarName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)changeUserNickName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)verifyAgentInfoWithNumber:(id)arg1 activityId:(id)arg2 oldSystem:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
- (void)verifyOTPCustomerAgentWithNumber:(id)arg1 verifyCode:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addAgentInfoWithNumber:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)updateUserAgentInfo:(id)arg1 recommendAgentInfo:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)requestUpdateRecommendAgentWithAgentCode:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateGestureLockInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)addPromptedResignAgentNumbers:(id)arg1;
- (void)fetchUserAgentInfoOnRefresh:(_Bool)arg1 agentId:(id)arg2 agentTypeFlag:(id)arg3 recommendAgentCode:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)fetchGetRecommendCustomerAgentInfoWithResult:(CDUnknownBlockType)arg1;
- (void)fetchConfirmRedClickResultWithClickRedDot:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)updateBedgeInfo:(id)arg1;
- (void)fetchBedgeInfoWithNeedRefresh:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)fetchQutuoAgentInfoWithResult:(CDUnknownBlockType)arg1;
- (void)fetchRecommendAgentInfoWithResult:(CDUnknownBlockType)arg1;
- (void)checkVerificationCode:(id)arg1 ofMobilePhone:(id)arg2 type:(long long)arg3 result:(CDUnknownBlockType)arg4;
- (void)fetchMobilPhoneVerificationCode:(id)arg1 type:(long long)arg2 result:(CDUnknownBlockType)arg3;
- (void)fetchYZTUserInfoWithResult:(CDUnknownBlockType)arg1;
- (void)fetchUserInfoOnRefresh:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)updateUserInfo:(id)arg1;
- (unsigned long long)verifyGestureFailureTimesCount;
- (void)verifyGesturePassword:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)switchGestureLockOnOff:(_Bool)arg1 withPassord:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)isGestureLockOn;
- (id)signInfoOfUserId:(id)arg1;
- (void)logoutForTimeout:(CDUnknownBlockType)arg1;
- (void)didLogOutSuccess;
- (void)clearData;
- (void)logOutWithResult:(CDUnknownBlockType)arg1;
- (void)didSignUpSuccess;
- (void)didSignUpFinishedWithUserInfo:(id)arg1 signInfo:(id)arg2 error:(id)arg3 messageCode:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)finishSignUpExtaProgress;
- (void)signUpAndBindWithAccount:(id)arg1 password:(id)arg2 verificationCode:(id)arg3 msgCodeType:(id)arg4 verificationCodeCompletion:(CDUnknownBlockType)arg5 result:(CDUnknownBlockType)arg6;
- (void)signUpWithAcccount:(id)arg1 password:(id)arg2 verificationCode:(id)arg3 msgCodeType:(id)arg4 verificationCodeCompletion:(CDUnknownBlockType)arg5 result:(CDUnknownBlockType)arg6;
- (void)checkRegisterImageVerifyCodeWithResult:(CDUnknownBlockType)arg1;
- (void)fetchRegisterImageVerifyCodeWithResult:(CDUnknownBlockType)arg1;
- (void)fetchSignUpVerificationCode:(id)arg1 type:(long long)arg2 result:(CDUnknownBlockType)arg3;
- (void)checkAccountStatus:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)updateRegisterTokenWithMagicStr:(id)arg1 mobilePhone:(id)arg2;
- (void)fetchSendMessageInfo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)bindYZTAccount:(id)arg1 withPhone:(id)arg2 isRegistered:(_Bool)arg3 phoneVerCode:(id)arg4 result:(CDUnknownBlockType)arg5;
- (void)logInWithYZTAcccount:(id)arg1 password:(id)arg2 verificationCode:(id)arg3 yztLogInSource:(long long)arg4 result:(CDUnknownBlockType)arg5 otherCompletion:(CDUnknownBlockType)arg6;
- (void)logInWithYZTAcccount:(id)arg1 password:(id)arg2 verificationCode:(id)arg3 result:(CDUnknownBlockType)arg4;
- (void)fetchYZTSignAndTimestampWithResult:(CDUnknownBlockType)arg1 bussinessType:(unsigned long long)arg2;
- (void)refreshYZTVerificationCode:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)prepareForYZTLogin:(id)arg1 verifyResult:(CDUnknownBlockType)arg2;
- (void)didLogInSuccess;
- (void)updateAnyDoorSignInfo:(id)arg1 ofUserId:(id)arg2;
- (void)updateUserInfo:(id)arg1 signInfo:(id)arg2;
- (void)didLogInFinishedWithUserInfo:(id)arg1 signInfo:(id)arg2 error:(id)arg3 result:(CDUnknownBlockType)arg4 source:(long long)arg5;
- (void)didLogInFinishedWithUserInfo:(id)arg1 signInfo:(id)arg2 error:(id)arg3 result:(CDUnknownBlockType)arg4;
- (void)changeLogInPassword:(id)arg1 toPassword:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)refreshLogInStatusWithResult:(CDUnknownBlockType)arg1;
- (void)logInWithAcccount:(id)arg1 password:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)logInWithAcccount:(id)arg1 password:(id)arg2 result:(CDUnknownBlockType)arg3 source:(long long)arg4;
- (void)logInWithAcccount:(id)arg1 password:(id)arg2 result:(CDUnknownBlockType)arg3 source:(long long)arg4 withObject:(id)arg5;
- (void)loginWithVerifyCodeParam:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)setUp;
- (void)loadLatestUserInfoHandler;
- (id)loadUserInfoHandlerOfUserId:(id)arg1;
- (void)tryToSwitchGestureLockOnOrOff:(_Bool)arg1 loginUuid:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)tryToSwitchGestureLockOnOrOff:(_Bool)arg1 Completion:(CDUnknownBlockType)arg2;
- (void)fetchGestureLockInfo:(CDUnknownBlockType)arg1 withParameter:(id)arg2;
- (void)fetchGestureLockInfo:(CDUnknownBlockType)arg1;
@property(readonly, nonatomic) PARSGestureLockInfo *gestureLockInfo;
@property(readonly, nonatomic) PARSUserInfo *currUserInfo;
@property(readonly, nonatomic) NSString *latestLogedInYZTUserName;
@property(readonly, nonatomic) NSString *latestLogedInYZTAccount;
@property(readonly, nonatomic) NSString *latestLogedInAccount;
@property(readonly, nonatomic) long long loginType;
@property(readonly, nonatomic) _Bool isLogedIn;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

