//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@interface PARSRealNameToWangCaiRequest : PARSProtalBaseUserHTTPRequest
{
    _Bool _isFromRealNameAuth;
}

@property(nonatomic) _Bool isFromRealNameAuth; // @synthesize isFromRealNameAuth=_isFromRealNameAuth;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)httpMethod;
- (id)url;

@end

