//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@class PARSMainAccountDataProvider;

@interface PARSMainAccountHandler : PARSBaseUserHandler
{
    PARSMainAccountDataProvider *_dataProvider;
}

@property(retain, nonatomic) PARSMainAccountDataProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (void)requestMerchantAuthServiceInfoWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountVerifyPasswordWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountWCIncomeListWithParam:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)fetchMainAccountWCIncomeInfo:(CDUnknownBlockType)arg1;
- (void)requestMainAccountWCIncomeInfo:(CDUnknownBlockType)arg1;
- (void)requestMainAccountChengziUrl:(CDUnknownBlockType)arg1;
- (void)fetchMainAccountInfo:(CDUnknownBlockType)arg1;
- (void)requestMainAccountInfo:(CDUnknownBlockType)arg1;
- (void)requestOpenMainAccountWithUserInfo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestMainAccountIsOpened:(CDUnknownBlockType)arg1;
- (void)requestMainAccountStatus:(CDUnknownBlockType)arg1;

@end

