//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSLifeAidHomePageProductInfo.h"

@class NSString;

@interface PARSLifeAidSearchResultInfo : PARSLifeAidHomePageProductInfo
{
    NSString *_name;
    NSString *_des;
    NSString *_hotLabel;
    NSString *_imgUrl;
    NSString *_discountLabel;
    NSString *_jumpUrl;
}

@property(copy, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(copy, nonatomic) NSString *discountLabel; // @synthesize discountLabel=_discountLabel;
@property(copy, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(copy, nonatomic) NSString *hotLabel; // @synthesize hotLabel=_hotLabel;
@property(copy, nonatomic) NSString *des; // @synthesize des=_des;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (id)initWithDict:(id)arg1;

@end

