//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSHealthCircleBaseRequest.h"

@class NSString;

@interface PARSHealthCircleTickLikeRequest : PARSHealthCircleBaseRequest
{
    NSString *_groupId;
    NSString *_praiseType;
    NSString *_targetPhone;
    NSString *_agentNo;
}

@property(copy, nonatomic) NSString *agentNo; // @synthesize agentNo=_agentNo;
@property(copy, nonatomic) NSString *targetPhone; // @synthesize targetPhone=_targetPhone;
@property(copy, nonatomic) NSString *praiseType; // @synthesize praiseType=_praiseType;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;
- (id)initWithUserId:(id)arg1 targetPhone:(id)arg2 groupId:(id)arg3 agentNo:(id)arg4 praiseType:(id)arg5 result:(CDUnknownBlockType)arg6;

@end

