//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "PARSWCPayPasscodeViewDelegate.h"
#import "PARSWangCaiHomeHeaderViewDelegate.h"
#import "PARSWangCaiShareViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "WealthWebViewDelegate.h"

@class NSString, PARSBankCardProtectionStatusInfo, PARSWCPayPasscodeViewController, PARSWangCaiFooterView, PARSWangCaiHomeHeaderView, PARSWangCaiInfo, UITableView;

@interface PARSOldWangCaiHomeViewController : PARSBaseRefreshViewController <PARSWCPayPasscodeViewDelegate, PARSWangCaiShareViewDelegate, PARSWangCaiHomeHeaderViewDelegate, WealthWebViewDelegate, UITableViewDelegate, UITableViewDataSource>
{
    _Bool _hasShowSetPassWord;
    _Bool _isLoading;
    UITableView *_tableView;
    PARSWangCaiHomeHeaderView *_headerView;
    PARSWangCaiFooterView *_wangCaiFooterView;
    PARSWCPayPasscodeViewController *_passcodeVC;
    PARSWangCaiInfo *_wangCaiInfo;
    NSString *_bankCardProtectionMessage;
    unsigned long long _remindFlag;
    PARSBankCardProtectionStatusInfo *_bankCardProtectionStatusInfo;
}

@property(retain, nonatomic) PARSBankCardProtectionStatusInfo *bankCardProtectionStatusInfo; // @synthesize bankCardProtectionStatusInfo=_bankCardProtectionStatusInfo;
@property(nonatomic) unsigned long long remindFlag; // @synthesize remindFlag=_remindFlag;
@property(retain, nonatomic) NSString *bankCardProtectionMessage; // @synthesize bankCardProtectionMessage=_bankCardProtectionMessage;
@property(retain, nonatomic) PARSWangCaiInfo *wangCaiInfo; // @synthesize wangCaiInfo=_wangCaiInfo;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) _Bool hasShowSetPassWord; // @synthesize hasShowSetPassWord=_hasShowSetPassWord;
@property(retain, nonatomic) PARSWCPayPasscodeViewController *passcodeVC; // @synthesize passcodeVC=_passcodeVC;
@property(retain, nonatomic) PARSWangCaiFooterView *wangCaiFooterView; // @synthesize wangCaiFooterView=_wangCaiFooterView;
@property(retain, nonatomic) PARSWangCaiHomeHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)closeShareView;
- (void)webViewDidClose;
- (void)refreshWangCaiUI;
- (void)loadBankCardProtectionStatusWithRefresh:(_Bool)arg1;
- (void)checkToShowSetPassword;
- (void)requestOldWangcaiDetailInfoNeedRefresh:(_Bool)arg1;
- (void)adjustFooterView;
- (void)handleError:(id)arg1;
- (void)gotoWebAnchor:(id)arg1;
- (void)didSelectBankCardCell;
- (void)updateWangCaiUI;
- (void)reloadData;
- (void)shareWangCai;
- (_Bool)isDataLoadSuccess;
- (void)fetchWangCaiInfoNeedRefresh:(_Bool)arg1;
- (id)accumulatedIncome;
- (void)didTapTransferOutButton;
- (void)didTapTransferInButton;
- (void)didTapWeeklyIncomeRateView;
- (void)didTapTenThousandIncomeView;
- (void)didTapAccumIncomeView;
- (void)didTapTotalAmountView;
- (void)payPasscodeViewControllerDidCancel:(id)arg1;
- (void)payPasscodeViewController:(id)arg1 didFinishTypedPasswd:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didTapRightBarButtonItem:(id)arg1;
- (void)onRefresh;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

