//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSMainAccountVerifyPasswordInfo : PARSBaseInfo
{
    NSString *_appId;
    NSString *_openId;
    NSString *_cmaPassword;
    NSString *_pamaPassword;
}

@property(retain, nonatomic) NSString *pamaPassword; // @synthesize pamaPassword=_pamaPassword;
@property(retain, nonatomic) NSString *cmaPassword; // @synthesize cmaPassword=_cmaPassword;
@property(retain, nonatomic) NSString *openId; // @synthesize openId=_openId;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void).cxx_destruct;

@end

