//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PARSZoneSectionController.h"

@class NSString, PARSZoneConfigInfo, UICollectionView;

@interface PARSZoneSectionController : NSObject <PARSZoneSectionController>
{
    id <PARSZoneSectionControllerDelegate> _delegate;
    UICollectionView *_collectionView;
    PARSZoneConfigInfo *_zoneConfigInfo;
}

@property(retain, nonatomic) PARSZoneConfigInfo *zoneConfigInfo; // @synthesize zoneConfigInfo=_zoneConfigInfo;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <PARSZoneSectionControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundColorForViewAtSection:(long long)arg3;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundImageForViewAtSection:(long long)arg3;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundImageUrlForViewAtSection:(long long)arg3;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundLayerForViewAtSection:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)loadData:(id)arg1 withCompetion:(CDUnknownBlockType)arg2;
- (void)refreshData:(CDUnknownBlockType)arg1;
- (id)initWithDelegate:(id)arg1 collectionView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

