//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSSocialCloudBaseHandler.h"

#import "PAIMApiMessageDelegate.h"

@class NSString;

@interface PARSSocialCloudGroupListHandler : PARSSocialCloudBaseHandler <PAIMApiMessageDelegate>
{
    NSString *_userId;
}

@property(readonly, copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)terminateConversations;
- (void)fetchBadgeNumberWithResult:(CDUnknownBlockType)arg1;
- (void)asynUpdateStateToReadWithAudioMessages:(id)arg1;
- (void)asynUpdateStateToReadWithMessages:(id)arg1;
- (id)initWithId:(id)arg1 queue:(id)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

