//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserDatabaseProvider.h"

@interface PARSModuleInfoProvider : PARSBaseUserDatabaseProvider
{
}

- (void)queryModuleZoneInfoWithModuleIdList:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)queryModuleZoneInfoWithModuleId:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)deleteModuleZoneInfoWithZoneIdList:(id)arg1;
- (void)deleteModuleZoneInfoWithZoneId:(id)arg1;
- (void)deleteModuleZoneInfoWithModuleId:(id)arg1;
- (void)saveModuleZoneInfoList:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)saveModuleZoneInfo:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)buildModuleInfoWithResult:(id)arg1;
- (_Bool)onCreateTable:(id)arg1;
- (long long)version;
- (id)name;
- (id)initWithUserID:(id)arg1;

@end

