//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSFundOrderInfo.h"

@class NSString;

@interface PARSFundCancelOrderInfo : PARSFundOrderInfo
{
    NSString *_latticePointCode;
    NSString *_customNumber;
    NSString *_payCenter;
}

@property(copy, nonatomic) NSString *payCenter; // @synthesize payCenter=_payCenter;
@property(copy, nonatomic) NSString *customNumber; // @synthesize customNumber=_customNumber;
@property(copy, nonatomic) NSString *latticePointCode; // @synthesize latticePointCode=_latticePointCode;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

