//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewLogic.h"

#import "PARSRefreshViewLogic.h"

@class NSArray, PARSViewLogicNotifyObserver;

@interface PARSAllActivityListViewLogic : PARSBaseViewLogic <PARSRefreshViewLogic>
{
    _Bool _showTip;
    _Bool _isLoading;
    _Bool _isRequestingBannerActivity;
    _Bool _isRequestingAllActivity;
    _Bool _hasMore;
    _Bool _isLoadingMore;
    NSArray *_allActivityDataItems;
    NSArray *_bannerDataItems;
    NSArray *_recommendActivityDataItems;
    long long _totalPage;
    long long _currentPage;
    long long _emptyType;
    PARSViewLogicNotifyObserver *_errorsObserver;
    PARSViewLogicNotifyObserver *_delegatesObserver;
}

@property(retain, nonatomic) PARSViewLogicNotifyObserver *delegatesObserver; // @synthesize delegatesObserver=_delegatesObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *errorsObserver; // @synthesize errorsObserver=_errorsObserver;
@property(nonatomic) _Bool isLoadingMore; // @synthesize isLoadingMore=_isLoadingMore;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(nonatomic) _Bool isRequestingAllActivity; // @synthesize isRequestingAllActivity=_isRequestingAllActivity;
@property(nonatomic) _Bool isRequestingBannerActivity; // @synthesize isRequestingBannerActivity=_isRequestingBannerActivity;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(nonatomic) long long emptyType; // @synthesize emptyType=_emptyType;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(nonatomic) long long totalPage; // @synthesize totalPage=_totalPage;
@property(copy, nonatomic) NSArray *recommendActivityDataItems; // @synthesize recommendActivityDataItems=_recommendActivityDataItems;
@property(copy, nonatomic) NSArray *bannerDataItems; // @synthesize bannerDataItems=_bannerDataItems;
@property(copy, nonatomic) NSArray *allActivityDataItems; // @synthesize allActivityDataItems=_allActivityDataItems;
@property(nonatomic) _Bool showTip; // @synthesize showTip=_showTip;
- (void).cxx_destruct;
- (void)selectedPlaceChangged:(id)arg1;
- (void)updateBanner;
- (void)loadAllActivityList:(long long)arg1 reload:(_Bool)arg2 needRefresh:(_Bool)arg3;
- (void)loadBannerActivityList:(_Bool)arg1;
- (void)itemClickAction:(unsigned long long)arg1;
- (void)bannerScrollClickAction:(unsigned long long)arg1;
- (void)loadMoreDataAction;
- (void)loadDataAction:(_Bool)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(nonatomic) _Bool isActive;

@end

