//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSCollectionViewCell.h"

@class NSIndexPath, PARSImageView, UIButton, UICollectionView, UIImageView, UILabel, UIView;

@interface PARSPolicyServiceListCell : PARSCollectionViewCell
{
    _Bool _canMove;
    UICollectionView *_collectionView;
    long long _status;
    id <PARSPolicyServiceListCellDelegate> _delegate;
    UIView *_containerView;
    PARSImageView *_imageView;
    UILabel *_titleLabel;
    UIButton *_optionBtn;
    NSIndexPath *_fromIndexPath;
    NSIndexPath *_currentIndexPath;
    NSIndexPath *_toIndexPath;
    UIImageView *_snapedImageView;
    struct CGSize _deltaSize;
}

@property(nonatomic) struct CGSize deltaSize; // @synthesize deltaSize=_deltaSize;
@property(retain, nonatomic) UIImageView *snapedImageView; // @synthesize snapedImageView=_snapedImageView;
@property(retain, nonatomic) NSIndexPath *toIndexPath; // @synthesize toIndexPath=_toIndexPath;
@property(retain, nonatomic) NSIndexPath *currentIndexPath; // @synthesize currentIndexPath=_currentIndexPath;
@property(retain, nonatomic) NSIndexPath *fromIndexPath; // @synthesize fromIndexPath=_fromIndexPath;
@property(retain, nonatomic) UIButton *optionBtn; // @synthesize optionBtn=_optionBtn;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) PARSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <PARSPolicyServiceListCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) long long status; // @synthesize status=_status;
@property(nonatomic) _Bool canMove; // @synthesize canMove=_canMove;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)indexPath:(id)arg1 moveToRect:(struct CGRect)arg2 completion:(CDUnknownBlockType)arg3;
- (id)getTheCellSnap:(id)arg1;
- (void)longPress:(id)arg1;
- (void)updateWithInfo:(id)arg1;
- (void)pressOptionBtn:(id)arg1;
- (unsigned long long)selectedStyle;
- (id)initWithFrame:(struct CGRect)arg1;

@end

