//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSSignInfo.h"

#import "NSCopying.h"

@class NSString;

@interface PARSYZTSignInfo : PARSSignInfo <NSCopying>
{
    NSString *_partyNo;
}

@property(copy, nonatomic) NSString *partyNo; // @synthesize partyNo=_partyNo;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJson:(id)arg1 account:(id)arg2;
- (id)init;

@end

