//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class PARSHWPedometerBottomSubView, UILabel;

@interface PARSHWPedometerWalkingBottomView : UIView
{
    id <PARSHWPedometerWalkingBottomViewDelegate> _delegate;
    PARSHWPedometerBottomSubView *_redPacketView;
    PARSHWPedometerBottomSubView *_kitView;
    PARSHWPedometerBottomSubView *_medalView;
    PARSHWPedometerBottomSubView *_donateBookView;
    UILabel *_redPacketContentLabel;
    UILabel *_kitContentLabel;
    UILabel *_medalContentLabel;
    UILabel *_donateContentLabel;
    UILabel *_kitBadgeValue;
    UILabel *_donateBadgeValue;
}

@property(retain, nonatomic) UILabel *donateBadgeValue; // @synthesize donateBadgeValue=_donateBadgeValue;
@property(retain, nonatomic) UILabel *kitBadgeValue; // @synthesize kitBadgeValue=_kitBadgeValue;
@property(retain, nonatomic) UILabel *donateContentLabel; // @synthesize donateContentLabel=_donateContentLabel;
@property(retain, nonatomic) UILabel *medalContentLabel; // @synthesize medalContentLabel=_medalContentLabel;
@property(retain, nonatomic) UILabel *kitContentLabel; // @synthesize kitContentLabel=_kitContentLabel;
@property(retain, nonatomic) UILabel *redPacketContentLabel; // @synthesize redPacketContentLabel=_redPacketContentLabel;
@property(retain, nonatomic) PARSHWPedometerBottomSubView *donateBookView; // @synthesize donateBookView=_donateBookView;
@property(retain, nonatomic) PARSHWPedometerBottomSubView *medalView; // @synthesize medalView=_medalView;
@property(retain, nonatomic) PARSHWPedometerBottomSubView *kitView; // @synthesize kitView=_kitView;
@property(retain, nonatomic) PARSHWPedometerBottomSubView *redPacketView; // @synthesize redPacketView=_redPacketView;
@property(nonatomic) __weak id <PARSHWPedometerWalkingBottomViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)buildSubClassView:(id)arg1 title:(id)arg2 content:(id)arg3 isShowBottomLine:(_Bool)arg4 isShowLeftLine:(_Bool)arg5 type:(long long)arg6;
- (void)setupSubviews;
- (void)donateBookViewTap;
- (void)medalViewTap;
- (void)kitViewTap;
- (void)redPacketViewTap;
- (void)updatePrivateViewContent:(id)arg1 badgeValue:(id)arg2 type:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

