//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIButton;

@interface PARSWealthSearchResultTableHeaderView : UIView
{
    UIButton *_button;
}

+ (id)newHeaderView;
@property(retain, nonatomic) UIButton *button; // @synthesize button=_button;
- (void).cxx_destruct;
- (void)updateWithResultCount:(long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

