//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@class PARSMyHealthPageInfoProvider;

@interface PARSMyHealthHandler : PARSBaseUserHandler
{
    PARSMyHealthPageInfoProvider *_myHealthPageInfoProvider;
}

@property(retain, nonatomic) PARSMyHealthPageInfoProvider *myHealthPageInfoProvider; // @synthesize myHealthPageInfoProvider=_myHealthPageInfoProvider;
- (void).cxx_destruct;
- (void)fetchMyHealthPageInfo:(CDUnknownBlockType)arg1;
- (void)requestMyHealthPageInfo:(CDUnknownBlockType)arg1;

@end

