//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PAIMApiMessageModel;

@protocol PARSConversationChatCellDelegate <NSObject>
- (void)deleteMessage:(PAIMApiMessageModel *)arg1;
- (void)resendMessage:(PAIMApiMessageModel *)arg1;
@end

