//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSStandardAddressInfo, UILabel;

@interface PARSCityListTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    PARSStandardAddressInfo *_addressInfo;
}

@property(retain, nonatomic) PARSStandardAddressInfo *addressInfo; // @synthesize addressInfo=_addressInfo;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)loadCity:(id)arg1;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

