//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class PARSSignInHandler;

@interface PARSSignInManager : NSObject
{
    PARSSignInHandler *_handler;
}

+ (id)sharedManager;
@property(retain, nonatomic) PARSSignInHandler *handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (_Bool)fetchBalanceShowStatus;
- (void)updateBalanceShowStatus:(_Bool)arg1;
- (void)fetchMissionListCacheBlcok:(CDUnknownBlockType)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)fetchIntegralWithResultBlock:(CDUnknownBlockType)arg1;
- (void)signInWithResultBLock:(CDUnknownBlockType)arg1;
- (void)querySignInRecordWithPageNo:(long long)arg1 pageSize:(long long)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)querySignInPrizeWithPrizeIndex:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)querySignInStateWithResultBlock:(CDUnknownBlockType)arg1;

@end

