//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PARSCollectionSectionBackgroundFlowLayoutDelegate.h"
#import "PARSHPBannerViewCellDelegate.h"
#import "PARSHPNoticeViewCellDelegate.h"
#import "PARSHPShortcutViewProtocal.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSArray, NSString, PARSZoneConfigInfo, UICollectionView;

@interface PARSHomePageViewPresenter : NSObject <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, PARSHPNoticeViewCellDelegate, PARSHPBannerViewCellDelegate, PARSCollectionSectionBackgroundFlowLayoutDelegate, PARSHPShortcutViewProtocal>
{
    _Bool _reserveBottomPlaceForAnydoor;
    id <PARSHomePageViewDelegate> _viewDelegate;
    NSArray *_bannerInfos;
    NSArray *_favoriteInfos;
    PARSZoneConfigInfo *_noticeZone;
    PARSZoneConfigInfo *_shortcutZone;
    PARSZoneConfigInfo *_customZone;
    NSArray *_informationList;
    NSString *_moreTitle;
    NSString *_title;
    UICollectionView *_collectionView;
    NSArray *_bannerViewInfos;
    struct CGPoint _lastStopOffset;
}

@property(retain, nonatomic) NSArray *bannerViewInfos; // @synthesize bannerViewInfos=_bannerViewInfos;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *moreTitle; // @synthesize moreTitle=_moreTitle;
@property(readonly, nonatomic) struct CGPoint lastStopOffset; // @synthesize lastStopOffset=_lastStopOffset;
@property(nonatomic) _Bool reserveBottomPlaceForAnydoor; // @synthesize reserveBottomPlaceForAnydoor=_reserveBottomPlaceForAnydoor;
@property(retain, nonatomic) NSArray *informationList; // @synthesize informationList=_informationList;
@property(retain, nonatomic) PARSZoneConfigInfo *customZone; // @synthesize customZone=_customZone;
@property(retain, nonatomic) PARSZoneConfigInfo *shortcutZone; // @synthesize shortcutZone=_shortcutZone;
@property(retain, nonatomic) PARSZoneConfigInfo *noticeZone; // @synthesize noticeZone=_noticeZone;
@property(retain, nonatomic) NSArray *favoriteInfos; // @synthesize favoriteInfos=_favoriteInfos;
@property(retain, nonatomic) NSArray *bannerInfos; // @synthesize bannerInfos=_bannerInfos;
@property(nonatomic) __weak id <PARSHomePageViewDelegate> viewDelegate; // @synthesize viewDelegate=_viewDelegate;
- (void).cxx_destruct;
- (void)shortcutImageDidLoaded;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)homePageBannerView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (void)homePageNoticeView:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundImageUrlForViewAtSection:(long long)arg3;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundLayerForViewAtSection:(long long)arg3;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForFooterInSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundColorForViewAtSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)presentView;
- (void)prepare;
- (id)initWithView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

