//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

@class UILabel, UITextView;

@interface PARSVoiceSearchWaitingViewController : PARSBaseViewController
{
    UILabel *_titleLabel;
    UITextView *_descTextView;
    long long _searchType;
}

@property(nonatomic) long long searchType; // @synthesize searchType=_searchType;
@property(retain, nonatomic) UITextView *descTextView; // @synthesize descTextView=_descTextView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)initUI;
- (void)viewDidLoad;
- (id)initWithSearchType:(long long)arg1;

@end

