//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@class PARSHealthCircleListProvider;

@interface PARSHealthCircleListHandler : PARSBaseUserHandler
{
    PARSHealthCircleListProvider *_dataProvider;
}

@property(retain, nonatomic) PARSHealthCircleListProvider *dataProvider; // @synthesize dataProvider=_dataProvider;
- (void).cxx_destruct;
- (void)asynDeleteGroupSummaryInfo:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)asynSaveGroupSummaryInfos:(id)arg1;
- (void)requestQueryUserMobilePhoneWithSocialCloudId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)requestSavingUserMobilePhone:(id)arg1 socialCloudId:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)saveUserSummaryInfo:(id)arg1;
- (void)queryUserSummaryInfoWithResult:(CDUnknownBlockType)arg1;
- (void)queryEcoCircleIdWithSocialCloudId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)queryAllHealthCircleGroupsWithResult:(CDUnknownBlockType)arg1;
- (void)requestAllHealthCircleGroupsWithResult:(CDUnknownBlockType)arg1;
- (void)updateStickiedState:(_Bool)arg1 forConversation:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)saveConversationList:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)queryConversationListWithStickiedState:(_Bool)arg1 result:(CDUnknownBlockType)arg2;
- (void)queryConversationListWithResult:(CDUnknownBlockType)arg1;
- (void)requestJoinCircle:(id)arg1 agentNo:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)fetchCacheCircleList:(CDUnknownBlockType)arg1;
- (void)requestCircleListWithResult:(CDUnknownBlockType)arg1;

@end

