//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "LoginMemberDelegate.h"
#import "PARSCollectionSectionBackgroundFlowLayoutDelegate.h"
#import "PARSPolicyVerifyPhoneViewControllerDelegate.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class NSString, PARSPolicyHomeViewLogic, UICollectionView;

@interface PARSPolicyHomeViewController : PARSBaseRefreshViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, PARSCollectionSectionBackgroundFlowLayoutDelegate, PARSPolicyVerifyPhoneViewControllerDelegate, LoginMemberDelegate>
{
    UICollectionView *_collectionView;
    PARSPolicyHomeViewLogic *_viewLogic;
}

@property(retain, nonatomic) PARSPolicyHomeViewLogic *viewLogic; // @synthesize viewLogic=_viewLogic;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
- (void).cxx_destruct;
- (void)verifyPhoneSuccessWithCode:(id)arg1 type:(unsigned long long)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 layout:(id)arg2 backgroundImageUrlForViewAtSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)onRefresh;
- (void)logInYZTSucessfully;
- (void)refreshPolicyUsualServiceList;
- (void)reloadHeader;
- (void)refreshView;
- (void)reloadData;
- (void)cleanYZTUserInfo;
- (void)didLogin;
- (void)gotoOnlineCustomerServicesCenter;
- (unsigned long long)getSeparatorOptionsWithIndexPath:(id)arg1;
- (void)clickActionWithInfo:(id)arg1;
- (void)delegateWithTuple:(id)arg1;
- (void)addRightBarButtonItem;
- (void)buildSubviews;
- (void)gotoVerifyPhone;
- (void)installBinder;
- (void)unBindLogic;
- (void)bindLogic;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

