//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UITableView, UIView;

@interface PARSFeedbackViewController : PARSBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    _Bool _showLogUpload;
    _Bool _isFirstIn;
    _Bool _isPresented;
    _Bool _cellHasClick;
    NSArray *_problems;
    NSString *_problemTitle;
    UITableView *_tableView;
    UIView *_headerView;
}

@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool cellHasClick; // @synthesize cellHasClick=_cellHasClick;
@property(nonatomic) _Bool isPresented; // @synthesize isPresented=_isPresented;
@property(nonatomic) _Bool isFirstIn; // @synthesize isFirstIn=_isFirstIn;
@property(retain, nonatomic) NSString *problemTitle; // @synthesize problemTitle=_problemTitle;
@property(nonatomic) _Bool showLogUpload; // @synthesize showLogUpload=_showLogUpload;
@property(retain, nonatomic) NSArray *problems; // @synthesize problems=_problems;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)goBackWithView:(id)arg1 viewController:(id)arg2;
- (id)findLowestVC:(id)arg1;
- (void)navBack;
- (void)loadData:(_Bool)arg1;
- (void)initUI;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

