//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PARSHealthKit : NSObject
{
    _Bool _raiseFlag;
    NSString *_receiveNumber;
    NSString *_broughtNumber;
    NSString *_remainingNumber;
    NSString *_unclaimedNumber;
    NSString *_cumulativeTime;
    NSString *_name;
    NSString *_agentNo;
    long long _pedometerStep;
    long long _sysdate;
}

@property(nonatomic) _Bool raiseFlag; // @synthesize raiseFlag=_raiseFlag;
@property(readonly, nonatomic) long long sysdate; // @synthesize sysdate=_sysdate;
@property(nonatomic) long long pedometerStep; // @synthesize pedometerStep=_pedometerStep;
@property(readonly, copy, nonatomic) NSString *agentNo; // @synthesize agentNo=_agentNo;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *cumulativeTime; // @synthesize cumulativeTime=_cumulativeTime;
@property(readonly, copy, nonatomic) NSString *unclaimedNumber; // @synthesize unclaimedNumber=_unclaimedNumber;
@property(readonly, copy, nonatomic) NSString *remainingNumber; // @synthesize remainingNumber=_remainingNumber;
@property(readonly, copy, nonatomic) NSString *broughtNumber; // @synthesize broughtNumber=_broughtNumber;
@property(readonly, copy, nonatomic) NSString *receiveNumber; // @synthesize receiveNumber=_receiveNumber;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

