//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSZoneSectionControllerDelegate.h"

@class NSString, PARSFinanceHomeRecommandTitleSectionController;

@protocol PARSFinanceHomeRecommandTitleSectionControllerDelegate <PARSZoneSectionControllerDelegate>
- (void)sectionController:(PARSFinanceHomeRecommandTitleSectionController *)arg1 didTapHeaderRightWithUri:(NSString *)arg2;
@end

