//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSSignInfoRecordListInfo : PARSBaseInfo
{
    NSString *_time;
    NSString *_signFlag;
    NSString *_dateStr;
}

@property(retain, nonatomic) NSString *dateStr; // @synthesize dateStr=_dateStr;
@property(copy, nonatomic) NSString *signFlag; // @synthesize signFlag=_signFlag;
@property(copy, nonatomic) NSString *time; // @synthesize time=_time;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

