//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PARSMediaManager : NSObject
{
}

+ (id)sharedManager;
- (void)showPhotoBrowserInVC:(id)arg1 maxPicCount:(long long)arg2 mediaType:(long long)arg3 singleSelection:(_Bool)arg4 needCut:(_Bool)arg5;

@end

