//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@interface PARSRegisterDelegateInfo : PARSBaseInfo
{
    long long _type;
    id _info;
}

@property(nonatomic) id info; // @synthesize info=_info;
@property(nonatomic) long long type; // @synthesize type=_type;

@end

