//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSSplashAdvertInfo : PARSBaseInfo
{
    _Bool _isFullScreen;
    NSString *_pic;
    long long _visibleTime;
    long long _invisibleTime;
    long long _ldScreenVersion;
    long long _countDownTimer;
    NSString *_title;
    NSString *_subTitle;
    long long _actionType;
    NSString *_action;
}

@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long countDownTimer; // @synthesize countDownTimer=_countDownTimer;
@property(nonatomic) long long ldScreenVersion; // @synthesize ldScreenVersion=_ldScreenVersion;
@property(nonatomic) long long invisibleTime; // @synthesize invisibleTime=_invisibleTime;
@property(nonatomic) long long visibleTime; // @synthesize visibleTime=_visibleTime;
@property(nonatomic) _Bool isFullScreen; // @synthesize isFullScreen=_isFullScreen;
@property(retain, nonatomic) NSString *pic; // @synthesize pic=_pic;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

