//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseUserHandler.h"

@interface PARSOldPrizeHandler : PARSBaseUserHandler
{
}

- (void)requestForFavorAddressWithResultBlock:(CDUnknownBlockType)arg1;
- (void)requestForMergeActivityPrizeWithModel:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;

@end

