//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldHTTPRequest.h"

@class NSString;

@interface PARSPhoneVerificationCodeRequest : PARSOldHTTPRequest
{
    _Bool _isSuccessed;
    NSString *_mobilePhone;
    NSString *_verificationCode;
    long long _type;
}

@property(nonatomic) _Bool isSuccessed; // @synthesize isSuccessed=_isSuccessed;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *verificationCode; // @synthesize verificationCode=_verificationCode;
@property(copy, nonatomic) NSString *mobilePhone; // @synthesize mobilePhone=_mobilePhone;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (long long)responseBodyType;
- (id)httpBody;
- (id)url;
- (id)initWithMobilePhone:(id)arg1 verificationCode:(id)arg2 type:(long long)arg3 completion:(CDUnknownBlockType)arg4;

@end

