//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "PARSHealthCircleMemberInfoDelegate.h"
#import "UIActionSheetDelegate.h"
#import "UITableViewDelegate.h"

@class NSString, PARSCircleInfo, PARSHealthCircleInfoDatasource, UITableView;

@interface PARSHealthCircleInfoViewController : PARSBaseViewController <UITableViewDelegate, UIActionSheetDelegate, PARSHealthCircleMemberInfoDelegate>
{
    _Bool _socialCloudFlag;
    PARSCircleInfo *_circleInfo;
    NSString *_activityId;
    CDUnknownBlockType _deleteBlock;
    CDUnknownBlockType _modifyHandler;
    unsigned long long _type;
    long long _module;
    UITableView *_mainTableView;
    PARSHealthCircleInfoDatasource *_datasource;
    NSString *_scircleId;
}

@property(nonatomic) _Bool socialCloudFlag; // @synthesize socialCloudFlag=_socialCloudFlag;
@property(copy, nonatomic) NSString *scircleId; // @synthesize scircleId=_scircleId;
@property(retain, nonatomic) PARSHealthCircleInfoDatasource *datasource; // @synthesize datasource=_datasource;
@property(retain, nonatomic) UITableView *mainTableView; // @synthesize mainTableView=_mainTableView;
@property(nonatomic) long long module; // @synthesize module=_module;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) CDUnknownBlockType modifyHandler; // @synthesize modifyHandler=_modifyHandler;
@property(copy, nonatomic) CDUnknownBlockType deleteBlock; // @synthesize deleteBlock=_deleteBlock;
@property(copy, nonatomic) NSString *activityId; // @synthesize activityId=_activityId;
@property(retain, nonatomic) PARSCircleInfo *circleInfo; // @synthesize circleInfo=_circleInfo;
- (void).cxx_destruct;
- (void)setMessageMode:(unsigned long long)arg1;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)didSelectMember:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)deleteMember:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showAlertController:(unsigned long long)arg1;
- (void)didSelectSettingsRowHandlerAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didEndDisplayingCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)requestMemberList;
- (void)requestCircleInfo;
- (void)fetchMemberListFromMemory;
- (void)checkMessageMode;
- (void)fetchUserConfig;
- (void)updateSJY;
- (void)popBack;
- (void)didReceiveMemoryWarning;
- (void)fetchCircleInfoFromMemory;
- (void)requestFriendCircleInfo;
- (void)fetchFriendCircleInfoFromMemery;
- (void)requestFriendMemberList;
- (void)fetchFriendMemberListFromMemory;
- (void)viewDidLoad;
- (id)initWithType:(unsigned long long)arg1 module:(long long)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

