//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "DetailInfoCellDeleteBtnDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, PARSMessageCenterInfo, UIButton, UITableView, UIView;

@interface PARSMessageDetailViewController : PARSBaseRefreshViewController <UITableViewDataSource, UITableViewDelegate, DetailInfoCellDeleteBtnDelegate>
{
    _Bool _needRefresh;
    _Bool _isEditing;
    id <PARSMessageDetailViewControllerDelegate> _delegate;
    UITableView *_tableView;
    UIView *_selectView;
    UIButton *_selectBtn;
    UIButton *_deleteBtn;
    UIButton *_managerBtn;
    double _contentHeight;
    PARSMessageCenterInfo *_info;
    NSArray *_messageInfos;
    NSArray *_selectedInfos;
}

@property(nonatomic) _Bool isEditing; // @synthesize isEditing=_isEditing;
@property(retain, nonatomic) NSArray *selectedInfos; // @synthesize selectedInfos=_selectedInfos;
@property(retain, nonatomic) NSArray *messageInfos; // @synthesize messageInfos=_messageInfos;
@property(nonatomic) _Bool needRefresh; // @synthesize needRefresh=_needRefresh;
@property(retain, nonatomic) PARSMessageCenterInfo *info; // @synthesize info=_info;
@property(nonatomic) double contentHeight; // @synthesize contentHeight=_contentHeight;
@property(retain, nonatomic) UIButton *managerBtn; // @synthesize managerBtn=_managerBtn;
@property(retain, nonatomic) UIButton *deleteBtn; // @synthesize deleteBtn=_deleteBtn;
@property(retain, nonatomic) UIButton *selectBtn; // @synthesize selectBtn=_selectBtn;
@property(retain, nonatomic) UIView *selectView; // @synthesize selectView=_selectView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <PARSMessageDetailViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)remarksCellShowContrntWithDic:(id)arg1 andCellIndexPath:(id)arg2;
- (void)updateCellBackView:(id)arg1 data:(id)arg2;
- (void)selectedDetailInfo:(id)arg1;
- (void)onLoadMore;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)managerBtnClcik:(id)arg1;
- (void)seleteAllMessage:(id)arg1;
- (void)deleteClick:(id)arg1;
- (id)parseMsgFieldData:(id)arg1;
- (void)dispatchWithMsgDetailInfo:(id)arg1;
- (id)updateCellStateWithInfo:(id)arg1 cell:(id)arg2 tableView:(id)arg3 indexPath:(id)arg4;
- (double)getLineNum:(id)arg1 font:(id)arg2 labelWidth:(double)arg3;
- (double)calculateDetailCellHeightWith:(id)arg1 indexPath:(id)arg2;
- (void)detailMsgDataAnalyzeWhenManagerClick;
- (void)detailMsgDataAnalyzeItemClickWithInfo:(id)arg1;
- (void)detailMsgDataAnalyzeWhenDeleteClick;
- (void)showBlankView;
- (void)removeResultView;
- (void)dealWithResult:(id)arg1;
- (void)loadMoreData;
- (void)refreshData;
- (void)loadCachedData;
- (void)loadData;
- (void)buildSubViews;
- (void)dealloc;
- (void)viewDidLoad;
- (id)initWithInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

