//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString;

@interface PARSDataAnalyticBeans : NSObject
{
    NSString *_batchId;
    NSArray *_eventArray;
}

@property(readonly, copy, nonatomic) NSArray *eventArray; // @synthesize eventArray=_eventArray;
@property(readonly, copy, nonatomic) NSString *batchId; // @synthesize batchId=_batchId;
- (void).cxx_destruct;
- (id)initWithBatchId:(id)arg1 andEventArray:(id)arg2;

@end

