//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PARSCirleWelfareInfo : NSObject
{
    NSString *_imageURL;
    NSString *_jumpUrl;
    NSString *_buryingPoint;
    NSString *_activityNo;
}

@property(readonly, copy, nonatomic) NSString *activityNo; // @synthesize activityNo=_activityNo;
@property(readonly, copy, nonatomic) NSString *buryingPoint; // @synthesize buryingPoint=_buryingPoint;
@property(readonly, copy, nonatomic) NSString *jumpUrl; // @synthesize jumpUrl=_jumpUrl;
@property(readonly, copy, nonatomic) NSString *imageURL; // @synthesize imageURL=_imageURL;
- (void).cxx_destruct;
- (id)initWithJson:(id)arg1;

@end

