//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSZoneConfBaseInfo.h"

@class NSArray, NSString;

@interface PARSZoneConfigInfo : PARSZoneConfBaseInfo
{
    NSString *_more;
    NSString *_moreUrl;
    NSArray *_items;
    NSString *_title;
    NSString *_bgImageUrl;
}

@property(copy, nonatomic) NSString *bgImageUrl; // @synthesize bgImageUrl=_bgImageUrl;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
@property(copy, nonatomic) NSString *moreUrl; // @synthesize moreUrl=_moreUrl;
@property(copy, nonatomic) NSString *more; // @synthesize more=_more;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (double)cellHeight;
- (id)initWithJson:(id)arg1;
- (id)initWithJson:(id)arg1 itemClass:(id)arg2;

@end

