//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PARSWealthProductPageTabViewDelegate.h"
#import "PARSWealthProductViewDelegate.h"

@class NSObject<PARSWealthProductContainerViewModelProtocol>, NSString, PARSResultView, PARSWealthProductPageTabView, UINavigationController, UIScrollView, UIView, UIViewController;

@interface PARSWealthProductContainerView : NSObject <PARSWealthProductPageTabViewDelegate, PARSWealthProductViewDelegate>
{
    struct CGRect _tabFrame;
    UINavigationController *navigationController;
    UIView *_parentView;
    PARSWealthProductPageTabView *_pageTabView;
    PARSResultView *_requestErrorView;
    PARSResultView *_emptyView;
    UIScrollView *_scrollNeedScrollToTop;
    UIViewController *_associateObject;
}

@property(nonatomic) __weak UIViewController *associateObject; // @synthesize associateObject=_associateObject;
@property(nonatomic) __weak UIScrollView *scrollNeedScrollToTop; // @synthesize scrollNeedScrollToTop=_scrollNeedScrollToTop;
@property(retain, nonatomic) PARSResultView *emptyView; // @synthesize emptyView=_emptyView;
@property(retain, nonatomic) PARSResultView *requestErrorView; // @synthesize requestErrorView=_requestErrorView;
@property(retain, nonatomic) PARSWealthProductPageTabView *pageTabView; // @synthesize pageTabView=_pageTabView;
@property(nonatomic) __weak UIView *parentView; // @synthesize parentView=_parentView;
@property(nonatomic) __weak UINavigationController *navigationController; // @synthesize navigationController;
- (void).cxx_destruct;
- (void)addTabView;
- (void)removeTabView;
- (void)searchScrollViewInView:(id)arg1;
- (void)viewDidAppear;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (void)viewDidDisappear;
- (void)safeRemoveFromSuperView:(id)arg1;
- (void)dettach;
- (void)attach:(id)arg1;
- (void)dealloc;
- (void)tabViewSeletedPageIndex:(id)arg1 selectedIndex:(unsigned long long)arg2;
- (id)tabViewPageOfPages:(id)arg1 indexOfPagers:(unsigned long long)arg2;
- (unsigned long long)tabViewNumberOfPages:(id)arg1;
- (void)initRAC;
- (void)bindViewModel:(id)arg1;
- (void)disposeRAC;
@property(nonatomic) __weak NSObject<PARSWealthProductContainerViewModelProtocol> *viewModel; // @dynamic viewModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

