//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, PARSWCPayPasscodeViewController;

@protocol PARSWCPayPasscodeViewDelegate <NSObject>
- (void)payPasscodeViewController:(PARSWCPayPasscodeViewController *)arg1 didFinishTypedPasswd:(NSString *)arg2;

@optional
- (void)payPasscodeViewControllerDidDismissed:(PARSWCPayPasscodeViewController *)arg1;
- (void)payPasscodeViewControllerDidCancel:(PARSWCPayPasscodeViewController *)arg1;
@end

