//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PARSWCPayPasscodeViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITextFieldDelegate.h"

@class NSString, PARSOldWangCaiTradePageViewModel, PARSWangCaiTradePage;

@interface PARSOldWangCaiTradeController : UIViewController <PARSWCPayPasscodeViewDelegate, UITextFieldDelegate, UITableViewDataSource>
{
    PARSWangCaiTradePage *_pageView;
    PARSOldWangCaiTradePageViewModel *_viewModel;
}

@property(retain, nonatomic) PARSOldWangCaiTradePageViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(retain, nonatomic) PARSWangCaiTradePage *pageView; // @synthesize pageView=_pageView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (_Bool)isValid:(id)arg1 withRegex:(id)arg2;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)payPasscodeViewControllerDidCancel:(id)arg1;
- (void)payPasscodeViewController:(id)arg1 didFinishTypedPasswd:(id)arg2;
- (void)hideAll;
- (void)binderToViewModel;
- (void)didTapRightButtonItem:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithTradeOutInfo:(id)arg1;
- (id)initWithTradeInInfo:(id)arg1;
- (id)initWithTradeType:(unsigned long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

