//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseRefreshViewController.h"

#import "PALifeHealthLineLXActionSheetDelegate.h"

@class MarqueeLabel, NSString, PARSActivityDetailModel, PARSHWEightPedometerDashBoardViewController, PARSHealthBodyInfo, PARSPedmoterWalkingButtonView, PARSPedmoterWalkingDonateView, PARSPedmoterWalkingMaronAndDonateView, PARSPedmoterWalkingMaronView, PARSPedmoterWalkingOperateClass, UIButton, UIImageView;

@interface PARSHealthPedmoterHomeEightViewController : PARSBaseRefreshViewController <PALifeHealthLineLXActionSheetDelegate>
{
    SEL _backToCircle;
    PARSHWEightPedometerDashBoardViewController *_pedometerDashBoardVC;
    UIButton *_settingButton;
    PARSHealthBodyInfo *_bodyInfo;
    PARSPedmoterWalkingButtonView *_btnView;
    PARSPedmoterWalkingDonateView *_donateBtnView;
    PARSPedmoterWalkingMaronView *_maronBtnView;
    PARSPedmoterWalkingMaronAndDonateView *_bothBtnView;
    UIButton *_walkingMotionBtn;
    UIButton *_walkingCourse;
    UIImageView *_walkingTrack;
    PARSActivityDetailModel *_activity;
    PARSPedmoterWalkingOperateClass *_operate;
    MarqueeLabel *_prizeListLabel;
}

@property(retain, nonatomic) MarqueeLabel *prizeListLabel; // @synthesize prizeListLabel=_prizeListLabel;
@property(retain, nonatomic) PARSPedmoterWalkingOperateClass *operate; // @synthesize operate=_operate;
@property(retain, nonatomic) PARSActivityDetailModel *activity; // @synthesize activity=_activity;
@property(retain, nonatomic) UIImageView *walkingTrack; // @synthesize walkingTrack=_walkingTrack;
@property(retain, nonatomic) UIButton *walkingCourse; // @synthesize walkingCourse=_walkingCourse;
@property(retain, nonatomic) UIButton *walkingMotionBtn; // @synthesize walkingMotionBtn=_walkingMotionBtn;
@property(retain, nonatomic) PARSPedmoterWalkingMaronAndDonateView *bothBtnView; // @synthesize bothBtnView=_bothBtnView;
@property(retain, nonatomic) PARSPedmoterWalkingMaronView *maronBtnView; // @synthesize maronBtnView=_maronBtnView;
@property(retain, nonatomic) PARSPedmoterWalkingDonateView *donateBtnView; // @synthesize donateBtnView=_donateBtnView;
@property(retain, nonatomic) PARSPedmoterWalkingButtonView *btnView; // @synthesize btnView=_btnView;
@property(retain, nonatomic) PARSHealthBodyInfo *bodyInfo; // @synthesize bodyInfo=_bodyInfo;
@property(retain, nonatomic) UIButton *settingButton; // @synthesize settingButton=_settingButton;
@property(retain, nonatomic) PARSHWEightPedometerDashBoardViewController *pedometerDashBoardVC; // @synthesize pedometerDashBoardVC=_pedometerDashBoardVC;
@property(nonatomic) SEL backToCircle; // @synthesize backToCircle=_backToCircle;
- (void).cxx_destruct;
- (_Bool)checkStepsPermissions;
- (void)requestPrizeList;
- (void)requestHealthWalkingTodayData;
- (void)requestDailyChallenges;
- (void)showAlertTips;
- (void)walkingCourseAction;
- (void)walkingMotionBtnAction;
- (void)useTheKit;
- (void)showKitAlertAuto:(_Bool)arg1;
- (void)checkAvailabilityKitWithTip:(id)arg1;
- (void)loadHistoryRecordDataWith:(id)arg1;
- (void)didClickOnButtonIndex:(long long)arg1;
- (void)backAction;
- (void)refreshData;
- (void)fetchBodyInfo;
- (void)sureBtnView;
- (void)setupSubviews;
- (void)reloadUI;
- (void)reloadKitSData;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithActivity:(id)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

