//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSArray, NSString;

@interface PARSElisStandardAddressRequest : PARSProtalBaseUserHTTPRequest
{
    NSArray *_infoList;
    NSString *_versionTime;
}

@property(copy, nonatomic) NSString *versionTime; // @synthesize versionTime=_versionTime;
@property(retain, nonatomic) NSArray *infoList; // @synthesize infoList=_infoList;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;
- (id)initWithUserId:(id)arg1 versionTime:(id)arg2 completion:(CDUnknownBlockType)arg3;

@end

