//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSCircleRankInfo, UIButton, UIImageView, UILabel;

@interface PARSHealthCircleRankingCell : UITableViewCell
{
    id <PARSHealthCircleDelegate> _delegate;
    UILabel *_rankingLabel;
    UIImageView *_avatarImageView;
    UILabel *_nameLabel;
    UILabel *_walkingStepsLabel;
    UILabel *_likeCountLabel;
    UIButton *_likeButton;
    UIButton *_talkButton;
    UIImageView *_medalImageView;
    PARSCircleRankInfo *_model;
    unsigned long long _rankingType;
}

@property(nonatomic) unsigned long long rankingType; // @synthesize rankingType=_rankingType;
@property(retain, nonatomic) PARSCircleRankInfo *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *medalImageView; // @synthesize medalImageView=_medalImageView;
@property(retain, nonatomic) UIButton *talkButton; // @synthesize talkButton=_talkButton;
@property(retain, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(retain, nonatomic) UILabel *likeCountLabel; // @synthesize likeCountLabel=_likeCountLabel;
@property(retain, nonatomic) UILabel *walkingStepsLabel; // @synthesize walkingStepsLabel=_walkingStepsLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UILabel *rankingLabel; // @synthesize rankingLabel=_rankingLabel;
@property(nonatomic) __weak id <PARSHealthCircleDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clickChat:(id)arg1;
- (void)clickLike:(id)arg1;
- (void)showSeparator:(_Bool)arg1;
- (void)setLikeHidden:(_Bool)arg1;
- (void)setRanking:(id)arg1 rankingType:(unsigned long long)arg2;
- (void)setWalkingStepsLabelConstraintsWithLikeHidden:(_Bool)arg1;
- (void)configMedalWithRankIndex:(long long)arg1;
- (void)setupSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

