//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIControl, UIImageView, UILabel;

@interface PARSSignInPrizeView : UIView
{
    long long _index;
    id _target;
    UIControl *_mainView;
    UILabel *_label;
    UIImageView *_lightImageView;
    UIImageView *_iconView;
    UILabel *_prizeLabel;
}

@property(retain, nonatomic) UILabel *prizeLabel; // @synthesize prizeLabel=_prizeLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(retain, nonatomic) UIImageView *lightImageView; // @synthesize lightImageView=_lightImageView;
@property(retain, nonatomic) UILabel *label; // @synthesize label=_label;
@property(retain, nonatomic) UIControl *mainView; // @synthesize mainView=_mainView;
@property(nonatomic) __weak id target; // @synthesize target=_target;
@property(nonatomic) long long index; // @synthesize index=_index;
- (void).cxx_destruct;
- (void)startRotation;
- (void)stopRotation;
- (void)rotate;
- (void)pressPrizeWithSender:(id)arg1;
- (void)refreshWithPrize:(id)arg1 isPrizeIndex:(_Bool)arg2;
- (void)layoutSubview;
- (id)initWithFrame:(struct CGRect)arg1;

@end

