//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseDataProvider.h"

@class TMCache;

@interface PARSBaseLRUCacheProvider : PARSBaseDataProvider
{
    TMCache *_tmCache;
}

@property(retain, nonatomic) TMCache *tmCache; // @synthesize tmCache=_tmCache;
- (void).cxx_destruct;
- (long long)version;
- (id)name;
- (id)initWithName:(id)arg1 rootPath:(id)arg2;

@end

