//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "PARSScrollTabControllerDelegate.h"

@class NSArray, NSString, PARSResultView, PARSScrollTabController;

@interface PARSPrizeViewController : PARSBaseViewController <PARSScrollTabControllerDelegate>
{
    PARSScrollTabController *_scrollTabController;
    NSArray *_tabModels;
    PARSResultView *_retryView;
    NSArray *_tabPrizeVcArr;
}

@property(retain, nonatomic) NSArray *tabPrizeVcArr; // @synthesize tabPrizeVcArr=_tabPrizeVcArr;
@property(retain, nonatomic) PARSResultView *retryView; // @synthesize retryView=_retryView;
@property(retain, nonatomic) NSArray *tabModels; // @synthesize tabModels=_tabModels;
@property(retain, nonatomic) PARSScrollTabController *scrollTabController; // @synthesize scrollTabController=_scrollTabController;
- (void).cxx_destruct;
- (void)tabController:(id)arg1 didSelectViewController:(id)arg2;
- (void)buildTabControllerWithTabs:(id)arg1;
- (void)removeRetryViewIfNeed;
- (void)fetchRemoteTabs;
- (void)fetchCachedTabs;
- (void)setupSubViews;
- (void)reloadDataForReceived:(id)arg1;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

