//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

#import "PARSVerticalScrollCycleViewDelegate.h"

@class NSArray, NSString, PARSVerticalScrollCycleView;

@interface PARSHPNoticeViewCell : UICollectionViewCell <PARSVerticalScrollCycleViewDelegate>
{
    _Bool _needReload;
    NSArray *_noticeInfos;
    id <PARSHPNoticeViewCellDelegate> _viewDelegate;
    PARSVerticalScrollCycleView *_noticeView;
}

@property(nonatomic) _Bool needReload; // @synthesize needReload=_needReload;
@property(retain, nonatomic) PARSVerticalScrollCycleView *noticeView; // @synthesize noticeView=_noticeView;
@property(nonatomic) __weak id <PARSHPNoticeViewCellDelegate> viewDelegate; // @synthesize viewDelegate=_viewDelegate;
@property(retain, nonatomic) NSArray *noticeInfos; // @synthesize noticeInfos=_noticeInfos;
- (void).cxx_destruct;
- (void)verticalScrollCycleViewClickAction:(long long)arg1;
- (void)reloadData;
- (void)buildSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

