//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString;

@interface PARSMyFundStatus : PARSBaseInfo
{
    NSString *_bankNo;
    NSString *_custNo;
    NSString *_idOccupyFlag;
    NSString *_fundRegFlag;
    NSString *_monetaryRegFlag;
    NSString *_passFlag;
    NSString *_customerId;
    NSString *_isOnroad;
    NSString *_occupyId;
    NSString *_cardFlag;
}

@property(copy, nonatomic) NSString *cardFlag; // @synthesize cardFlag=_cardFlag;
@property(copy, nonatomic) NSString *occupyId; // @synthesize occupyId=_occupyId;
@property(copy, nonatomic) NSString *isOnroad; // @synthesize isOnroad=_isOnroad;
@property(copy, nonatomic) NSString *customerId; // @synthesize customerId=_customerId;
@property(copy, nonatomic) NSString *passFlag; // @synthesize passFlag=_passFlag;
@property(copy, nonatomic) NSString *monetaryRegFlag; // @synthesize monetaryRegFlag=_monetaryRegFlag;
@property(copy, nonatomic) NSString *fundRegFlag; // @synthesize fundRegFlag=_fundRegFlag;
@property(copy, nonatomic) NSString *idOccupyFlag; // @synthesize idOccupyFlag=_idOccupyFlag;
@property(copy, nonatomic) NSString *custNo; // @synthesize custNo=_custNo;
@property(copy, nonatomic) NSString *bankNo; // @synthesize bankNo=_bankNo;
- (void).cxx_destruct;
- (_Bool)fundStatus;
- (id)initWithJson:(id)arg1;

@end

