//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "PARSAgentSearchDelegate.h"
#import "PARSDealSearchDelegate.h"

@class NSMutableArray, NSString, PARSAgentSearchTableViewController, PARSDealSearchTableViewController, UIView;

@interface PARSTradeSearchViewController : PARSBaseViewController <PARSAgentSearchDelegate, PARSDealSearchDelegate>
{
    long long _selectedIndex;
    PARSDealSearchTableViewController *_dealSearchController;
    PARSAgentSearchTableViewController *_agentSearchController;
    NSMutableArray *_topButtons;
    UIView *_indicateView;
}

@property(retain, nonatomic) UIView *indicateView; // @synthesize indicateView=_indicateView;
@property(retain, nonatomic) NSMutableArray *topButtons; // @synthesize topButtons=_topButtons;
@property(retain, nonatomic) PARSAgentSearchTableViewController *agentSearchController; // @synthesize agentSearchController=_agentSearchController;
@property(retain, nonatomic) PARSDealSearchTableViewController *dealSearchController; // @synthesize dealSearchController=_dealSearchController;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
- (void).cxx_destruct;
- (void)jumpToDealSearchDetailWithApplyNumber:(id)arg1;
- (void)jumpToAgentSearchDetailWithApplyNumber:(id)arg1;
- (void)tabButtonAction:(id)arg1;
- (void)switchToAgentSearch;
- (void)switchToDealSearch;
- (void)addTopTabWithSelectedIndex:(long long)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (id)initWithSelectedIndex:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

