//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewLogic.h"

@class NSArray, NSDecimalNumber, PARSUsableCouponsInfo, PARSViewLogicNotifyObserver;

@interface PARSCouponViewLogic : PARSBaseViewLogic
{
    _Bool _showTip;
    _Bool _isLoading;
    _Bool _isLoadingMore;
    _Bool _hasMore;
    _Bool _needUpdate;
    PARSViewLogicNotifyObserver *_errorsObserver;
    PARSViewLogicNotifyObserver *_delegatesObserver;
    PARSViewLogicNotifyObserver *_dataObserver;
    PARSViewLogicNotifyObserver *_tipsObserver;
    NSArray *_couponList;
    long long _totalPage;
    long long _currentPage;
    long long _type;
    NSArray *_showDetailIndexPaths;
    NSArray *_selectedIndexPaths;
    NSArray *_totalNum;
    NSArray *_selectedCouponList;
    PARSUsableCouponsInfo *_usableCouponInfo;
    unsigned long long _currentCouponStyle;
    NSDecimalNumber *_currentAmount;
}

@property(retain, nonatomic) NSDecimalNumber *currentAmount; // @synthesize currentAmount=_currentAmount;
@property(nonatomic) unsigned long long currentCouponStyle; // @synthesize currentCouponStyle=_currentCouponStyle;
@property(retain, nonatomic) PARSUsableCouponsInfo *usableCouponInfo; // @synthesize usableCouponInfo=_usableCouponInfo;
@property(retain, nonatomic) NSArray *selectedCouponList; // @synthesize selectedCouponList=_selectedCouponList;
@property(copy, nonatomic) NSArray *totalNum; // @synthesize totalNum=_totalNum;
@property(retain, nonatomic) NSArray *selectedIndexPaths; // @synthesize selectedIndexPaths=_selectedIndexPaths;
@property(retain, nonatomic) NSArray *showDetailIndexPaths; // @synthesize showDetailIndexPaths=_showDetailIndexPaths;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(nonatomic) long long currentPage; // @synthesize currentPage=_currentPage;
@property(readonly, nonatomic) long long totalPage; // @synthesize totalPage=_totalPage;
@property(nonatomic) _Bool needUpdate; // @synthesize needUpdate=_needUpdate;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(nonatomic) _Bool isLoadingMore; // @synthesize isLoadingMore=_isLoadingMore;
@property(nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
@property(retain, nonatomic) NSArray *couponList; // @synthesize couponList=_couponList;
@property(nonatomic) _Bool showTip; // @synthesize showTip=_showTip;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *tipsObserver; // @synthesize tipsObserver=_tipsObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *dataObserver; // @synthesize dataObserver=_dataObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *delegatesObserver; // @synthesize delegatesObserver=_delegatesObserver;
@property(retain, nonatomic) PARSViewLogicNotifyObserver *errorsObserver; // @synthesize errorsObserver=_errorsObserver;
- (void).cxx_destruct;
- (void)closeTipView;
- (void)confirmOrder;
- (void)refresh;
- (void)selectCouponWithIndexPath:(id)arg1;
- (void)didSelectRowAtIndexPath:(id)arg1;
- (void)jumpToActivity;
- (_Bool)shouldShowDetailWithIndexPath:(id)arg1;
- (long long)indexForIndexPath:(id)arg1 inIndexPathArray:(id)arg2;
- (void)showDetailWithIndexPath:(id)arg1;
- (void)fetchValidCouponsListWithMerchantCode:(id)arg1 orderAmount:(id)arg2 orderInfo:(id)arg3 couponList:(id)arg4;
- (void)fetchCouponWithType:(long long)arg1;
- (void)dataAnalyzeWhenJump;
- (void)dataAnalyzeWhenFresh;
- (id)init;

@end

