//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSPrizeDetailShowInfo, UILabel;

@interface PARSPrizeDetailCell : UITableViewCell
{
    PARSPrizeDetailShowInfo *_showInfo;
    UILabel *_titleLabel;
    UILabel *_valueLabel;
}

@property(nonatomic) __weak UILabel *valueLabel; // @synthesize valueLabel=_valueLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) PARSPrizeDetailShowInfo *showInfo; // @synthesize showInfo=_showInfo;
- (void).cxx_destruct;
- (void)showSeparator:(_Bool)arg1;
- (void)setupUI;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

