//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UILabel;

@interface PARSOrderDetailCell : UITableViewCell
{
    UILabel *_detailLable;
}

+ (id)cellWithTableView:(id)arg1;
@property(retain, nonatomic) UILabel *detailLable; // @synthesize detailLable=_detailLable;
- (void).cxx_destruct;

@end

