//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSZoneConfigHandler.h"

@class NSCache, NSMutableDictionary, PARSModuleItemInfoProvider, PARSModuleZoneInfoProvider;

@interface PARSModuleZoneHandler : PARSZoneConfigHandler
{
    PARSModuleZoneInfoProvider *_zoneProvider;
    PARSModuleItemInfoProvider *_itemInfoProvider;
    NSCache *_cache;
    NSMutableDictionary *_zoneMap;
}

@property(retain, nonatomic) NSMutableDictionary *zoneMap; // @synthesize zoneMap=_zoneMap;
@property(retain, nonatomic) NSCache *cache; // @synthesize cache=_cache;
@property(retain, nonatomic) PARSModuleItemInfoProvider *itemInfoProvider; // @synthesize itemInfoProvider=_itemInfoProvider;
@property(retain, nonatomic) PARSModuleZoneInfoProvider *zoneProvider; // @synthesize zoneProvider=_zoneProvider;
- (void).cxx_destruct;
- (void)updateItemInfo:(id)arg1 moduleId:(id)arg2 onZone:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)queryItemInfosWithModuleId:(id)arg1 zoneId:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)queryZoneBaseInfoWithModuleId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)queryZoneInfosWithModuleId:(id)arg1 result:(CDUnknownBlockType)arg2;
- (void)queryZoneInfosWithModuleId:(id)arg1 searchKey:(id)arg2 result:(CDUnknownBlockType)arg3;
- (void)updateCache:(id)arg1 moduleId:(id)arg2;
- (void)sortWithZoneInfos:(id)arg1 error:(id)arg2 resultBlock:(CDUnknownBlockType)arg3;
- (void)requestZoneInfosWithModuleId:(id)arg1 result:(CDUnknownBlockType)arg2;

@end

