//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PARSScrollTabViewDelegate.h"
#import "UIScrollViewDelegate.h"

@class NSArray, NSString, PARSScrollTabView, UIScrollView;

@interface PARSScrollTabController : UIViewController <UIScrollViewDelegate, PARSScrollTabViewDelegate>
{
    _Bool _disableBounces;
    PARSScrollTabView *_tabView;
    UIScrollView *_scrollView;
    NSArray *_viewControllers;
    UIViewController *_selectedViewController;
    unsigned long long _selectedIndex;
    id <PARSScrollTabControllerDelegate> _delegate;
    unsigned long long _style;
}

@property(nonatomic) unsigned long long style; // @synthesize style=_style;
@property(nonatomic) __weak id <PARSScrollTabControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool disableBounces; // @synthesize disableBounces=_disableBounces;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) PARSScrollTabView *tabView; // @synthesize tabView=_tabView;
- (void).cxx_destruct;
- (void)tabView:(id)arg1 didSelectIndex:(unsigned long long)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)updateTabTitle:(id)arg1 atIndex:(long long)arg2;
- (void)loadScrollContentAtIndex:(long long)arg1;
- (void)addAllViewControllers;
- (id)getTopTabView;
- (void)buildTabView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLoad;
- (id)initWithStyle:(unsigned long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

