//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSPayResultAnimationView.h"

@class CABasicAnimation, CAShapeLayer;

@interface PARSPaySuccessAnimationView : PARSPayResultAnimationView
{
    CAShapeLayer *_successLayer;
    CABasicAnimation *_successAnimation;
}

@property(retain, nonatomic) CABasicAnimation *successAnimation; // @synthesize successAnimation=_successAnimation;
@property(retain, nonatomic) CAShapeLayer *successLayer; // @synthesize successLayer=_successLayer;
- (void).cxx_destruct;
- (void)animationDidStop:(id)arg1 finished:(_Bool)arg2;
- (void)startAnimation;
- (id)initWithFrame:(struct CGRect)arg1;

@end

