//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

@class UIButton, UIImageView, UILabel;

@interface PARSUpgradeRemindViewController : PARSBaseViewController
{
    UIImageView *_headImageView;
    UILabel *_contentLabel;
    UIButton *_upgradeButton;
}

@property(retain, nonatomic) UIButton *upgradeButton; // @synthesize upgradeButton=_upgradeButton;
@property(retain, nonatomic) UILabel *contentLabel; // @synthesize contentLabel=_contentLabel;
@property(retain, nonatomic) UIImageView *headImageView; // @synthesize headImageView=_headImageView;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)updateAction;
- (void)initUI;
- (void)viewDidLoad;

@end

