//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseInfo.h"

@class NSString, PARSMainAccountInfo;

@interface PARSMainAccountStatusResult : PARSBaseInfo
{
    long long _status;
    NSString *_tipsMsg;
    PARSMainAccountInfo *_mainAccountInfo;
}

+ (id)hasOpenedOldWCAccountNotAddCardWithInfo:(id)arg1;
+ (id)hasOpenedOldWCAccountNotSetPwdWithInfo:(id)arg1;
+ (id)cancelOpenOldWCAccountWithInfo:(id)arg1;
+ (id)hasOpenedMainAccountNotSetPwdWithInfo:(id)arg1;
+ (id)cancelOpenMainAccountWithInfo:(id)arg1;
+ (id)cancelUpgradeMainAccountWithInfo:(id)arg1;
+ (id)noNeedToUpgradeMainAccountWithInfo:(id)arg1;
+ (id)hasDoneOpenedMainAccountWithInfo:(id)arg1;
+ (id)fetchMainAccountInfoFailedResult;
@property(retain, nonatomic) PARSMainAccountInfo *mainAccountInfo; // @synthesize mainAccountInfo=_mainAccountInfo;
@property(retain, nonatomic) NSString *tipsMsg; // @synthesize tipsMsg=_tipsMsg;
@property(nonatomic) long long status; // @synthesize status=_status;
- (void).cxx_destruct;

@end

