//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSBaseViewController.h"

#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class NSNotification, NSString, PARSAddressInfo, UIButton, UITableView, UITextField;

@interface PARSAddressAddAndModifyViewController : PARSBaseViewController <UITableViewDataSource, UITableViewDelegate, UITextFieldDelegate, UIGestureRecognizerDelegate>
{
    long long _type;
    CDUnknownBlockType _completionBlock;
    PARSAddressInfo *_addressInfo;
    UITableView *_mainTableview;
    UIButton *_rightBtn;
    UITextField *_userNameTextField;
    UITextField *_phoneTextField;
    UITextField *_postCodeTextField;
    UITextField *_areaTextField;
    UITextField *_addressTextField;
    UITextField *_currentTextField;
    NSNotification *_notification;
    PARSAddressInfo *_address;
}

@property(copy, nonatomic) PARSAddressInfo *address; // @synthesize address=_address;
@property(retain, nonatomic) NSNotification *notification; // @synthesize notification=_notification;
@property(retain, nonatomic) UITextField *currentTextField; // @synthesize currentTextField=_currentTextField;
@property(retain, nonatomic) UITextField *addressTextField; // @synthesize addressTextField=_addressTextField;
@property(retain, nonatomic) UITextField *areaTextField; // @synthesize areaTextField=_areaTextField;
@property(retain, nonatomic) UITextField *postCodeTextField; // @synthesize postCodeTextField=_postCodeTextField;
@property(retain, nonatomic) UITextField *phoneTextField; // @synthesize phoneTextField=_phoneTextField;
@property(retain, nonatomic) UITextField *userNameTextField; // @synthesize userNameTextField=_userNameTextField;
@property(retain, nonatomic) UIButton *rightBtn; // @synthesize rightBtn=_rightBtn;
@property(retain, nonatomic) UITableView *mainTableview; // @synthesize mainTableview=_mainTableview;
@property(retain, nonatomic) PARSAddressInfo *addressInfo; // @synthesize addressInfo=_addressInfo;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (void)keyboardHide:(id)arg1;
- (void)adjustView:(id)arg1;
- (void)keyboardShow:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (void)refreshRightBarBtn;
- (_Bool)checkValidate:(id)arg1;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)handleTap:(id)arg1;
- (_Bool)check;
- (void)addOrModifyAddress;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (void)showPickerView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)refreshCell:(id)arg1 indexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (void)resignKeyboard;
- (void)didReceiveMemoryWarning;
- (void)layoutRightBarBtn;
- (void)viewDidLoad;
- (id)initWithType:(long long)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

