//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSOldBaseUserHTTPRequest.h"

@class PARSActivityCommentInfo;

@interface PARSAddOrReplyCommentRequest : PARSOldBaseUserHTTPRequest
{
    PARSActivityCommentInfo *_commentInfo;
}

@property(retain, nonatomic) PARSActivityCommentInfo *commentInfo; // @synthesize commentInfo=_commentInfo;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

