//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PARSProtalBaseUserHTTPRequest.h"

@class NSString;

@interface PARSIntegralProductRequest : PARSProtalBaseUserHTTPRequest
{
    NSString *_productUrl;
    NSString *_prepose;
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *prepose; // @synthesize prepose=_prepose;
@property(copy, nonatomic) NSString *productUrl; // @synthesize productUrl=_productUrl;
- (void).cxx_destruct;
- (void)handleResponseResult:(id)arg1;
- (id)httpBody;
- (id)url;

@end

