//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class PARSMyInsuranceInfo, PARSResultView, UIButton, UIImageView, UILabel;

@interface PARSMyInsuranceTableViewCell : UITableViewCell
{
    id <PARSMyInsuranceTVCDelegate> _delegate;
    UIImageView *_iconView;
    UILabel *_titleLabel;
    UILabel *_detailLabel;
    UILabel *_dateLabel;
    UIButton *_renewalBtn;
    PARSResultView *_noneView;
    PARSResultView *_errorView;
    PARSMyInsuranceInfo *_info;
}

@property(retain, nonatomic) PARSMyInsuranceInfo *info; // @synthesize info=_info;
@property(retain, nonatomic) PARSResultView *errorView; // @synthesize errorView=_errorView;
@property(retain, nonatomic) PARSResultView *noneView; // @synthesize noneView=_noneView;
@property(retain, nonatomic) UIButton *renewalBtn; // @synthesize renewalBtn=_renewalBtn;
@property(retain, nonatomic) UILabel *dateLabel; // @synthesize dateLabel=_dateLabel;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *iconView; // @synthesize iconView=_iconView;
@property(nonatomic) __weak id <PARSMyInsuranceTVCDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)gotoRenewal;
- (void)reloadDataWithInfo:(id)arg1;
- (void)showNoneView;
- (void)showErrorView;
- (void)layout;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

