//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSString;

@interface PAServerResponse : NSObject
{
    long long _systime;
    long long _code;
    NSString *_cid;
    NSString *_data;
    NSMutableArray *_messageNotifications;
    NSMutableArray *_creditNotifications;
}

@property(readonly, nonatomic) NSMutableArray *creditNotifications; // @synthesize creditNotifications=_creditNotifications;
@property(readonly, nonatomic) NSMutableArray *messageNotifications; // @synthesize messageNotifications=_messageNotifications;
@property(readonly, nonatomic) NSString *data; // @synthesize data=_data;
@property(readonly, nonatomic) NSString *cid; // @synthesize cid=_cid;
@property(readonly, nonatomic) long long code; // @synthesize code=_code;
@property(readonly, nonatomic) long long systime; // @synthesize systime=_systime;
- (void).cxx_destruct;
- (id)initWithResponse:(id)arg1;

@end

