//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "PAZNTabBarDelegate.h"

@class NSArray, NSString, PAZNTabBar, UIView;

@interface PAZNTabBarController : UIViewController <PAZNTabBarDelegate>
{
    UIView *_contentView;
    _Bool _tabBarHidden;
    id <PAZNTabBarControllerDelegate> _delegate;
    NSArray *_viewControllers;
    UIViewController *_selectedViewController;
    unsigned long long _selectedIndex;
    PAZNTabBar *_tabBar;
}

@property(retain, nonatomic) PAZNTabBar *tabBar; // @synthesize tabBar=_tabBar;
@property(nonatomic, getter=isTabBarHidden) _Bool tabBarHidden; // @synthesize tabBarHidden=_tabBarHidden;
@property(nonatomic) unsigned long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) __weak UIViewController *selectedViewController; // @synthesize selectedViewController=_selectedViewController;
@property(copy, nonatomic) NSArray *viewControllers; // @synthesize viewControllers=_viewControllers;
@property(nonatomic) __weak id <PAZNTabBarControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tabBar:(id)arg1 didSelectItemAtIndex:(long long)arg2;
- (_Bool)tabBar:(id)arg1 shouldSelectItemAtIndex:(long long)arg2;
- (void)setTabBarHidden:(_Bool)arg1 animated:(_Bool)arg2;
- (id)contentView;
- (long long)indexForViewController:(id)arg1;
- (_Bool)shouldAutorotateToInterfaceOrientation:(long long)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (long long)preferredStatusBarUpdateAnimation;
- (long long)preferredStatusBarStyle;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

