//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVAudioSessionDelegate.h"

@class AVAudioPlayer, AVAudioSession, NSString;

@interface PAZQOPVideoManager : NSObject <AVAudioSessionDelegate>
{
    AVAudioPlayer *_avAudioPlayer;
    AVAudioSession *_session;
}

+ (id)shareVideoManager;
@property(retain, nonatomic) AVAudioSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVAudioPlayer *avAudioPlayer; // @synthesize avAudioPlayer=_avAudioPlayer;
- (void).cxx_destruct;
- (void)shake;
- (void)stopPlaySround;
- (void)playSround:(id)arg1 andType:(id)arg2;
- (void)stopPlay;
- (void)playCallScound:(id)arg1 andType:(id)arg2;
- (void)outputToNone;
- (void)outputToAudioPortSpeaker;
- (id)initSingleton;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

