//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PHAddressSelect : NSObject
{
    id <PHAddressSelectDelegate> _delegate;
    NSString *_JSONUpdateBaseURL;
    long long _fileDownloadFailRequestCount;
}

+ (id)sharedInterce;
@property(nonatomic) long long fileDownloadFailRequestCount; // @synthesize fileDownloadFailRequestCount=_fileDownloadFailRequestCount;
@property(copy, nonatomic) NSString *JSONUpdateBaseURL; // @synthesize JSONUpdateBaseURL=_JSONUpdateBaseURL;
@property(retain, nonatomic) id <PHAddressSelectDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (id)__readStringFromUserDefaultsWithKeyName:(id)arg1;
- (void)__saveDataToUserDefaultsWithString:(id)arg1 andKeyName:(id)arg2;
- (id)__getKeyNameFromFileName:(id)arg1;
- (void)__downloadJSONFileWithFileName:(id)arg1 URL:(id)arg2 targetPath:(id)arg3 Requestcount:(unsigned long long)arg4;
- (void)__downloadJSONFileWithFileName:(id)arg1 URL:(id)arg2 targetPath:(id)arg3 MD5:(id)arg4 Requestcount:(unsigned long long)arg5;
- (_Bool)__touchDirectory:(id)arg1;
- (id)__buildFilePathWithFileName:(id)arg1;
- (id)ph_filePathWithJSONName:(unsigned long long)arg1;
- (id)ph_addressShowAddressSelectForPickerViewWithJSONName:(unsigned long long)arg1;
- (id)ph_addressShowAddressSelectForTableViewControllerWithJSONName:(unsigned long long)arg1;
- (void)ph_updateOnlineAddressJSONWithJSONName:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateAddressJSON;

@end

