//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PHDeviceCollection : NSObject
{
}

+ (id)version;
+ (id)totalSpaceFree;
+ (id)totalSpace;
+ (id)networkType;
+ (id)ip;
+ (id)carrier;
+ (id)iOSCountryInfo;
+ (id)breakFlag;
+ (id)bootTime;
+ (id)cupType;
+ (id)cpuCount;
+ (id)cupSubType;
+ (id)screenRes;
+ (id)os;
+ (id)idfv;
+ (id)idfa;
+ (id)openUdid;

@end

