//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol PHH5ResourceUpdateDelegate <NSObject>
- (void)ph_h5ResourceUpdateWithUpdateResult:(unsigned long long)arg1 isForceUpdate:(_Bool)arg2;
@end

