//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PHKOInsuranceModel : NSObject
{
    long long _type;
    NSString *_customerId;
    NSString *_moduleName;
}

+ (id)insuranceWithType:(long long)arg1 customerId:(id)arg2 moduleName:(id)arg3;
@property(copy, nonatomic) NSString *moduleName; // @synthesize moduleName=_moduleName;
@property(copy, nonatomic) NSString *customerId; // @synthesize customerId=_customerId;
@property(nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithType:(long long)arg1 customerId:(id)arg2 moduleName:(id)arg3;

@end

