//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface PHNetworkPrivate : NSObject
{
}

+ (id)appVersionString;
+ (id)md5StringFromString:(id)arg1;
+ (void)addDoNotBackupAttribute:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (id)urlStringWithOriginUrlString:(id)arg1 appendParameters:(id)arg2;
+ (id)urlParametersStringFromParameters:(id)arg1;
+ (_Bool)checkJson:(id)arg1 withValidator:(id)arg2;

@end

