//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class LaunchEntity, NSDictionary, NSMutableArray, NSString, UIButton, UITableView;

@interface PHPreCreditInfoViewController : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    LaunchEntity *_entity;
    NSDictionary *_nameDic;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failBlock;
    UITableView *_precreTableView;
    UIButton *_comfirmButton;
    NSMutableArray *_datasourceArray;
}

@property(retain, nonatomic) NSMutableArray *datasourceArray; // @synthesize datasourceArray=_datasourceArray;
@property(retain, nonatomic) UIButton *comfirmButton; // @synthesize comfirmButton=_comfirmButton;
@property(retain, nonatomic) UITableView *precreTableView; // @synthesize precreTableView=_precreTableView;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) NSDictionary *nameDic; // @synthesize nameDic=_nameDic;
@property(retain, nonatomic) LaunchEntity *entity; // @synthesize entity=_entity;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)comfirm:(id)arg1;
- (void)textFieldDidChanged:(id)arg1;
- (void)viewDidLoad;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

