//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAudioPlayer, AVAudioSession;

@interface PHRIControlManager : NSObject
{
    float _audioDuration;
    AVAudioPlayer *_avAudioPlayer;
    AVAudioSession *_session;
}

+ (id)shareManager;
@property(nonatomic) float audioDuration; // @synthesize audioDuration=_audioDuration;
@property(retain, nonatomic) AVAudioSession *session; // @synthesize session=_session;
@property(retain, nonatomic) AVAudioPlayer *avAudioPlayer; // @synthesize avAudioPlayer=_avAudioPlayer;
- (void).cxx_destruct;
- (_Bool)isHeadsetPluggedIn;
- (void)setupAudioSession;
- (void)outputToNone;
- (void)outputToAudioPortSpeaker;
- (void)phri_stopSound;
- (void)phri_playSoundWithSoundName:(id)arg1 type:(id)arg2;
- (void)getAuthorityOfCameraAndMicroWithBlock:(CDUnknownBlockType)arg1;

@end

