//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface PHRIMcpModel : NSObject
{
    NSString *_extensionNum;
    NSString *_tokenKey;
    NSString *_domain;
    NSString *_IPAddress;
    NSString *_port;
    NSString *_password;
}

@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *port; // @synthesize port=_port;
@property(copy, nonatomic) NSString *IPAddress; // @synthesize IPAddress=_IPAddress;
@property(copy, nonatomic) NSString *domain; // @synthesize domain=_domain;
@property(copy, nonatomic) NSString *tokenKey; // @synthesize tokenKey=_tokenKey;
@property(copy, nonatomic) NSString *extensionNum; // @synthesize extensionNum=_extensionNum;
- (void).cxx_destruct;
- (id)description;

@end

