//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"

@class NSString, NSTimer, PHRIConfig, PHRIMcpModel;

@interface PHRIManager : NSObject <UIAlertViewDelegate>
{
    _Bool _needNotice;
    _Bool _isNetAvaible;
    _Bool _isReigster;
    id <PHRIManagerDelegate> _delegate;
    PHRIConfig *_riConfig;
    CDUnknownBlockType _finishBlock;
    NSString *_recordID;
    NSString *_routerId;
    NSString *_jobNumber;
    NSString *_priority;
    NSString *_queuingDetail;
    PHRIMcpModel *_mcpModel;
    NSTimer *_updateExtensionTimer;
}

+ (id)shareManager;
@property(nonatomic) _Bool isReigster; // @synthesize isReigster=_isReigster;
@property(retain, nonatomic) NSTimer *updateExtensionTimer; // @synthesize updateExtensionTimer=_updateExtensionTimer;
@property(retain, nonatomic) PHRIMcpModel *mcpModel; // @synthesize mcpModel=_mcpModel;
@property(copy, nonatomic) NSString *queuingDetail; // @synthesize queuingDetail=_queuingDetail;
@property(copy, nonatomic) NSString *priority; // @synthesize priority=_priority;
@property(copy, nonatomic) NSString *jobNumber; // @synthesize jobNumber=_jobNumber;
@property(copy, nonatomic) NSString *routerId; // @synthesize routerId=_routerId;
@property(copy, nonatomic) NSString *recordID; // @synthesize recordID=_recordID;
@property(nonatomic) _Bool isNetAvaible; // @synthesize isNetAvaible=_isNetAvaible;
@property(nonatomic, getter=isNeedNotice) _Bool needNotice; // @synthesize needNotice=_needNotice;
@property(copy, nonatomic) CDUnknownBlockType finishBlock; // @synthesize finishBlock=_finishBlock;
@property(retain, nonatomic) PHRIConfig *riConfig; // @synthesize riConfig=_riConfig;
@property(nonatomic) __weak id <PHRIManagerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)handleMainNotification:(id)arg1;
- (void)setupSDKCallBack:(id)arg1;
- (void)__hungupToDo;
- (void)releaseExtension;
- (void)updateExtension;
- (void)__remotePretrialFailed;
- (void)remotePretrial:(id)arg1;
- (void)__getRecordIdFailed;
- (void)getRecordId;
- (void)registerExtensionNumber;
- (void)__getExtensionNumberFailed;
- (void)getExtensionNumber;
- (void)startRemoteInterview;
- (void)startRemoteInterviewWithConfig:(id)arg1 needNotice:(_Bool)arg2 finishBlock:(CDUnknownBlockType)arg3;
- (void)getQueueDedailWithParams:(id)arg1;
- (void)getQueueDedailWithApplyNo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

