//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class Config, DeviceInfo, UIToolbar, UIView;

@interface PopupCameraViewController : UIViewController
{
    UIToolbar *toolBar;
    struct CGRect FrameRg;
    UIView *cameraImg;
    float myWidthImage;
    float myHeightImage;
    int orientationPre;
    int orientationCurrent;
    _Bool certHash;
    DeviceInfo *myDeinfo;
    Config *_myConfig;
}

@property(retain, nonatomic) Config *myConfig; // @synthesize myConfig=_myConfig;
- (void)notifyChange:(id)arg1;
- (struct CGRect)getScreen;
- (void)setScreen:(struct CGRect)arg1;
- (_Bool)getDicValue:(id)arg1 dic:(id)arg2;
- (void)noticeRemove;
- (void)dealloc;
- (void)PhotoClick;
- (void)cancel;
- (unsigned char)checkImageExit;
- (void)didReceiveMemoryWarning;
- (struct CGSize)imageScale:(struct CGSize)arg1 toSize:(struct CGSize)arg2;
- (id)cameraScale:(id)arg1 toSize:(struct CGSize)arg2;
- (id)getDataArray;
- (id)getData:(id)arg1 dic:(id)arg2;
- (void)setTemplate:(id)arg1 mydata:(id)arg2 signID:(id)arg3;
- (void)setTemplate:(id)arg1 mydata:(id)arg2;
- (id)hexStringFromData:(id)arg1;
- (id)getSha1StringFromNSData:(id)arg1;
- (void)SetSignerCameraDB:(id)arg1;
- (void)SetCameraImageDB:(id)arg1;
- (void)cameraUse;
- (void)cameraAgain;
- (void)noticeCameraAgain;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)init;
- (id)initIndex:(int)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

