//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface ProgressHUD : UIView
{
}

+ (id)allHUDsForView:(id)arg1;
+ (void)hideHUDForView:(id)arg1;
+ (unsigned long long)hideAllHUDsForView:(id)arg1;
+ (id)HUDForView:(id)arg1;
+ (id)showHUDInView:(id)arg1 withMessage:(id)arg2;
+ (id)showHUDInView:(id)arg1 withMessage:(id)arg2 alpha:(double)arg3;
- (id)initWithView:(id)arg1 withMessage:(id)arg2 alpha:(double)arg3;
- (id)initWithFrame:(struct CGRect)arg1 withMessage:(id)arg2 bkAlpha:(double)arg3;
- (id)initWithFrame:(struct CGRect)arg1 withMessage:(id)arg2;
- (id)initWithView:(id)arg1 withMessage:(id)arg2;

@end

