//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAVExtend.h"

@class QAVContext;

@interface QAVContextExtend : QAVExtend
{
    QAVContext *_context;
}

@property(retain, nonatomic) QAVContext *context; // @synthesize context=_context;
- (void)dealloc;

@end

