//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "QAVMultiParam.h"

@class NSData, NSString;

@interface QAVInternalEnterParam : QAVMultiParam
{
    int _bussType;
    int _relationType;
    NSString *_extraData;
    NSData *_freeFlowSignature;
}

@property(copy, nonatomic) NSData *freeFlowSignature; // @synthesize freeFlowSignature=_freeFlowSignature;
@property(copy, nonatomic) NSString *extraData; // @synthesize extraData=_extraData;
@property(nonatomic) int relationType; // @synthesize relationType=_relationType;
@property(nonatomic) int bussType; // @synthesize bussType=_bussType;
- (void)dealloc;
- (id)init;

@end

