//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface QAVRoomIntServerInfo : NSObject
{
    _Bool _tcp;
    unsigned short _port;
    unsigned int _ip;
}

@property(nonatomic) _Bool tcp; // @synthesize tcp=_tcp;
@property(nonatomic) unsigned short port; // @synthesize port=_port;
@property(nonatomic) unsigned int ip; // @synthesize ip=_ip;

@end

