//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RecordUpperViewController.h"

#import "AVAudioPlayerDelegate.h"
#import "AVAudioRecorderDelegate.h"

@class AVAudioPlayer, AVAudioRecorder, NSError, NSString, NSURL;

@interface RecordViewController : RecordUpperViewController <AVAudioPlayerDelegate, AVAudioRecorderDelegate>
{
    AVAudioRecorder *recorder;
    NSError *error;
    NSURL *urlPlay;
    int myOrientation;
    AVAudioPlayer *_avPlay;
}

@property(retain, nonatomic) AVAudioPlayer *avPlay; // @synthesize avPlay=_avPlay;
- (void)notifyChange:(id)arg1;
- (struct CGRect)getScreen;
- (struct CGRect)getDeviceScreen;
- (id)hexStringFromData:(id)arg1;
- (id)getSha1StringFromNSData:(id)arg1;
- (void)noticeRemove;
- (void)didReceiveMemoryWarning;
- (void)dismissRecord;
- (void)SetSignerSoundDB:(id)arg1;
- (id)getDataArray;
- (id)getData:(id)arg1 dic:(id)arg2;
- (void)setTemplate:(id)arg1 mydata:(id)arg2;
- (void)finishedRecord;
- (void)stopr;
- (void)timer;
- (void)record;
- (void)myplay;
- (void)mystop;
- (void)myrecord;
- (_Bool)setupAudioSession;
- (void)audio;
- (void)detectionVoice;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)tapView:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

