//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSTimer, UIColor, UILabel;

@interface SCLTimerDisplay : UIView
{
    double currentAngle;
    double currentTime;
    double timerLimit;
    double radius;
    double lineWidth;
    NSTimer *timer;
    CDUnknownBlockType completedBlock;
    _Bool _reverse;
    long long _buttonIndex;
    UIColor *_color;
    UILabel *_countLabel;
}

@property(retain, nonatomic) UILabel *countLabel; // @synthesize countLabel=_countLabel;
@property(nonatomic) _Bool reverse; // @synthesize reverse=_reverse;
@property(retain, nonatomic) UIColor *color; // @synthesize color=_color;
@property long long buttonIndex; // @synthesize buttonIndex=_buttonIndex;
@property double currentAngle; // @synthesize currentAngle;
- (void).cxx_destruct;
- (void)updateTimerButton:(id)arg1;
- (void)stopTimer;
- (void)cancelTimer;
- (void)startTimerWithTimeLimit:(int)arg1 completed:(CDUnknownBlockType)arg2;
- (void)drawRect:(struct CGRect)arg1;
- (void)updateFrame:(struct CGSize)arg1;
- (id)initWithOrigin:(struct CGPoint)arg1 radius:(double)arg2 lineWidth:(double)arg3;
- (id)initWithOrigin:(struct CGPoint)arg1 radius:(double)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

