//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SystemMessage : NSObject
{
}

+ (id)macaddress;
+ (id)getOSMainVer;
+ (id)escape:(id)arg1;
+ (id)systemMessage;
+ (_Bool)isJailbroken;
+ (id)getCarrierName;
+ (id)getDeviceVersion;
+ (id)product;
+ (id)manufact;
+ (id)getSystemResolution;
+ (id)getSystemVersion;
+ (id)getSystemName;
+ (id)getAppName;
+ (id)getAppPath;
+ (id)getAppPkg;
+ (id)getAppVersion;
+ (id)getNetType;
+ (id)getWorkPath;
+ (void)setLogPath:(id)arg1;
+ (id)getLogPath;

@end

