//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface Tiger : NSObject
{
}

+ (id)RcbnrPZKpcDZPFtybu:(id)arg1;
+ (id)CeqyYuiUwQpWrRKHqM:(const void *)arg1 length:(unsigned long long)arg2 padded:(_Bool)arg3;
+ (id)IEQCdTZgqSFPUBcPXs:(id)arg1 padded:(_Bool)arg2;
+ (id)zljsDkFwPxDMBDdbVm:(const void *)arg1 length:(unsigned long long)arg2;
+ (id)RmDTzYYwDEickXJCjp:(const void *)arg1 length:(unsigned long long)arg2 padded:(_Bool)arg3;
+ (id)ecGCjVwOqtrFkLgGeP:(id)arg1;
+ (id)hgjxiZnWpcCRAgYETf:(id)arg1 padded:(_Bool)arg2;
+ (id)KslWcAVPjZDRPIUban:(id)arg1;
+ (id)VNjlAxzgmsYulKGZLI:(const void *)arg1 length:(unsigned long long)arg2;
+ (id)MvLRSIGYkdaOxKvxnJ:(id)arg1;
+ (id)EQcGCRkhVmimWhIGZU:(const void *)arg1 length:(unsigned long long)arg2;
+ (id)JUFofRXhXYYwrcRbwY:(const void *)arg1 length:(unsigned long long)arg2;
+ (id)qIDaTKLVgLZRjweXdX:(id)arg1;
+ (id)PmnvGDCKKbOYLxaXLX:(id)arg1;
+ (unsigned long long)baseDecode:(const char *)arg1 srcLen:(unsigned long long)arg2 destBytes:(char *)arg3 destLen:(unsigned long long)arg4 charset:(const char *)arg5 requirePadding:(_Bool)arg6;
+ (unsigned long long)baseEncode:(const char *)arg1 srcLen:(unsigned long long)arg2 destBytes:(char *)arg3 destLen:(unsigned long long)arg4 charset:(const char *)arg5 padded:(_Bool)arg6;
+ (id)baseDecode:(const void *)arg1 length:(unsigned long long)arg2 charset:(const char *)arg3 requirePadding:(_Bool)arg4;
+ (id)baseEncode:(const void *)arg1 length:(unsigned long long)arg2 charset:(const char *)arg3 padded:(_Bool)arg4;

@end

