//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ILiveFirstFrameListener.h"
#import "ILiveMemStatusListener.h"
#import "ILiveRoomDisconnectListener.h"
#import "TIMMessageListener.h"

@class NSString, TILLiveConfig, TILLiveRoomOption, UIView;

@interface TILLiveManager : NSObject <TIMMessageListener, ILiveMemStatusListener, ILiveRoomDisconnectListener, ILiveFirstFrameListener>
{
    int _roomId;
    TILLiveConfig *_config;
    TILLiveRoomOption *_roomOption;
    id <ILVLiveIMListener> _imListener;
    id <ILVLiveAVListener> _avListener;
    UIView *_rootView;
}

+ (id)getInstance;
@property(retain, nonatomic) UIView *rootView; // @synthesize rootView=_rootView;
@property(nonatomic) int roomId; // @synthesize roomId=_roomId;
@property(nonatomic) __weak id <ILVLiveAVListener> avListener; // @synthesize avListener=_avListener;
@property(nonatomic) __weak id <ILVLiveIMListener> imListener; // @synthesize imListener=_imListener;
@property(retain, nonatomic) TILLiveRoomOption *roomOption; // @synthesize roomOption=_roomOption;
@property(retain, nonatomic) TILLiveConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (id)getVersion;
- (void)onNewMessage:(id)arg1;
- (void)onFirstFrameRecved:(int)arg1 height:(int)arg2 identifier:(id)arg3 srcType:(long long)arg4;
- (_Bool)onRoomDisconnect:(int)arg1;
- (_Bool)onEndpointsUpdateInfo:(long long)arg1 updateList:(id)arg2;
- (void)setAVListener:(id)arg1;
- (void)setIMListener:(id)arg1;
- (void)requestView:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)downToVideoMember:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)upToVideoMember:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)sendOtherMessage:(id)arg1 toUser:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)sendCustomMessage:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)sendTextMessage:(id)arg1 succ:(CDUnknownBlockType)arg2 failed:(CDUnknownBlockType)arg3;
- (void)removeAllAVRenderViews;
- (id)getAllAVRenderViews;
- (void)sendAVRenderViewToBack:(id)arg1 srcType:(long long)arg2;
- (void)bringAVRenderViewToFront:(id)arg1 srcType:(long long)arg2;
- (void)removeAVRenderView:(id)arg1 srcType:(long long)arg2;
- (id)getAVRenderView:(id)arg1 srcType:(long long)arg2;
- (_Bool)switchAVRenderView:(id)arg1 srcType:(long long)arg2 with:(id)arg3 anotherSrcType:(long long)arg4;
- (void)modifyAVRenderView:(struct CGRect)arg1 forIdentifier:(id)arg2 srcType:(long long)arg3;
- (id)addAVRenderView:(struct CGRect)arg1 forIdentifier:(id)arg2 srcType:(long long)arg3;
- (void)setAVRootView:(id)arg1;
- (void)quitRoom:(CDUnknownBlockType)arg1 failed:(CDUnknownBlockType)arg2;
- (void)switchRoom:(int)arg1 option:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)joinRoom:(int)arg1 option:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)createRoom:(int)arg1 option:(id)arg2 succ:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

