//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface TLV : NSObject
{
    unsigned char _version;
    unsigned short _type;
    int _length;
    NSData *_body;
}

@property(retain, nonatomic) NSData *body; // @synthesize body=_body;
@property(nonatomic) int length; // @synthesize length=_length;
@property(nonatomic) unsigned short type; // @synthesize type=_type;
@property(nonatomic) unsigned char version; // @synthesize version=_version;
- (void).cxx_destruct;

@end

