//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIActionSheet.h"

@interface UIActionSheet (Blocks)
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (CDUnknownBlockType)dismissalAction;
- (void)setDismissalAction:(CDUnknownBlockType)arg1;
- (long long)addButtonItem:(id)arg1;
- (id)initWithTitle:(id)arg1 cancelButtonItem:(id)arg2 destructiveButtonItem:(id)arg3 otherButtonItems:(id)arg4;
@end

