//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIColor.h"

@interface UIColor (XY)
+ (id)uxy_colorFromHex:(long long)arg1 alpha:(double)arg2;
+ (id)uxy_colorFromHexString:(id)arg1;
- (id)uxy_rgbaArray;
- (id)uxy_hexString;
- (id)uxy_blackOrWhiteContrastingColor;
@end

