//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIDevice.h"

@interface UIDevice (jkn_PPOSVersion)
- (int)jkn_deviceModel;
- (_Bool)is5_0OrLater;
- (_Bool)isios4OrLater;
- (_Bool)is4_2OrLater;
- (_Bool)is4_2;
- (_Bool)is4_1;
- (_Bool)is4_0;
- (_Bool)is3_2;
- (_Bool)is3_1;
- (_Bool)isios4;
- (_Bool)isiPadStyle;
- (_Bool)isiPad;
- (_Bool)isiPod;
@end

