//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@interface UIView (PATips)
- (void)hideManualTips;
- (void)showProgress:(double)arg1 tips:(id)arg2;
- (void)showMaskLoadingTips:(id)arg1;
- (void)showLoadingTips:(id)arg1;
- (void)showMaskLoadingTips;
- (void)showLoadingTips;
- (void)showTitle:(id)arg1 message:(id)arg2;
- (void)showTips:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showTips:(id)arg1;
- (_Bool)isLoading;
@end

