//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSError;

@interface URLResponse : NSObject
{
    int _tag;
    NSData *_data;
    NSError *_error;
}

+ (id)share;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSData *data; // @synthesize data=_data;
@property(nonatomic) int tag; // @synthesize tag=_tag;
- (void).cxx_destruct;

@end

