//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface UserDetailInfo : NSObject
{
    int sex;
    NSString *username;
    NSString *password;
    double height;
    double weight;
    NSString *realname;
    NSString *create_time;
    NSString *update_time;
}

@property(retain, nonatomic) NSString *update_time; // @synthesize update_time;
@property(retain, nonatomic) NSString *create_time; // @synthesize create_time;
@property(retain, nonatomic) NSString *realname; // @synthesize realname;
@property(nonatomic) double weight; // @synthesize weight;
@property(nonatomic) int sex; // @synthesize sex;
@property(nonatomic) double height; // @synthesize height;
@property(retain, nonatomic) NSString *password; // @synthesize password;
@property(retain, nonatomic) NSString *username; // @synthesize username;
- (void).cxx_destruct;

@end

