//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

@class LaunchEntity, NSString, UIButton, UITextField;

@interface UserInfoInputViewController : UIViewController
{
    NSString *_phone;
    LaunchEntity *_entity;
    CDUnknownBlockType _successBlock;
    CDUnknownBlockType _failBlock;
    UITextField *_phoneTxt;
    UITextField *_nameTxt;
    UITextField *_IdTxt;
    UIButton *_confirmButton;
    UIButton *_precreditButton;
}

@property(retain, nonatomic) UIButton *precreditButton; // @synthesize precreditButton=_precreditButton;
@property(retain, nonatomic) UIButton *confirmButton; // @synthesize confirmButton=_confirmButton;
@property(retain, nonatomic) UITextField *IdTxt; // @synthesize IdTxt=_IdTxt;
@property(retain, nonatomic) UITextField *nameTxt; // @synthesize nameTxt=_nameTxt;
@property(retain, nonatomic) UITextField *phoneTxt; // @synthesize phoneTxt=_phoneTxt;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType successBlock; // @synthesize successBlock=_successBlock;
@property(retain, nonatomic) LaunchEntity *entity; // @synthesize entity=_entity;
@property(copy, nonatomic) NSString *phone; // @synthesize phone=_phone;
- (void).cxx_destruct;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)precredit:(id)arg1;
- (void)confirm:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)clickBackBarButton:(id)arg1;
- (void)viewDidLoad;
- (id)init;

@end

