//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface WebViewURLManager : NSObject
{
}

- (id)__getHtmlEnv;
- (id)__decodeFromPercentEscapeString:(id)arg1;
- (_Bool)isNoWifiWithDescription:(id)arg1;
- (id)appendingHtmlEnvWithUrl:(id)arg1;
- (id)loadLocalHtml:(id)arg1;
- (_Bool)isEqulatoHttpWithURL:(id)arg1;
- (id)showNoWifiHtml;

@end

